### ISSUE TITLE
Elsa 2 - Startup issue with yessql (SqlTransaction has completed; it is no longer usable.) 

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1050]
It's not starting today but was running fine after upgrading yesterday to the latest non-rc. 
I'll try a few things, hopefully, it's just an annoying transient thing.
```
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck()
   at Microsoft.Data.SqlClient.SqlTransaction.Commit()
   at System.Data.Common.DbTransaction.CommitAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at YesSql.Session.CommitOrRollbackTransactionAsync()
   at YesSql.Session.CommitOrRollbackTransactionAsync()
   at YesSql.Session.SaveChangesAsync()
   at Elsa.Persistence.YesSql.Services.DataMigrationManager.RunAllAsync()
   at Elsa.Persistence.YesSql.Services.RunMigrations.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Unily.Management.UI.Program.Main(String[] args) in C:\UnilyManagement\Unily Management\Unily Management\Unily.Management.UI\Program.cs:line 22
[09:15:11 FTL] Unily.Management.UI start-up failed
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck()
   at Microsoft.Data.SqlClient.SqlTransaction.Commit()
   at System.Data.Common.DbTransaction.CommitAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at YesSql.Session.CommitOrRollbackTransactionAsync()
   at YesSql.Session.CommitOrRollbackTransactionAsync()
   at YesSql.Session.SaveChangesAsync()
   at Elsa.Persistence.YesSql.Services.DataMigrationManager.RunAllAsync()
   at Elsa.Persistence.YesSql.Services.RunMigrations.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

I have got use to seeing this error from last week, but it's not quite getting there this time I don't think: 
```
05/26/2021 09:54:51 +01:00 Running migration '"Elsa.Persistence.YesSql.Migrations"'
05/26/2021 09:54:51 +01:00 Error while running migration version 0 for '"Elsa.Persistence.YesSql.Migrations"'
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Elsa2_WorkflowDefinitions_WorkflowDefinitionIndex' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.CreateMapIndexTable(Type indexType, Action`1 table, String collection)
   at YesSql.Sql.SchemaBuilderExtensions.CreateMapIndexTable[T](ISchemaBuilder builder, Action`1 table, String collection)
   at Elsa.Persistence.YesSql.Migrations.Create()
```

**Comment by matt4446** [comment]
Here we are: 
Old value 
`{"$id":"1","Id":1,"DataMigrations":[{"$id":"2","DataMigrationClass":"Elsa.Persistence.YesSql.Migrations"}]}`
New value 
`{"$id":"1","Id":1,"DataMigrations":[{"$id":"2","DataMigrationClass":"Elsa.Persistence.YesSql.Migrations","Version":1}]}`

Copying in the new value to the old record under my `Elsa2` prefix fixed the startup issue.

**Comment by sfmskywalker** [comment]
Nice catch. I wonder if it has anything to do with the recent package upgrade of YesSQL 3.0.3 to 3.0.6. Anyway, thanks for sharing your findings!
