### ISSUE TITLE
Http send request Json parse error

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1076]
I try to make an http call to https://www.metaweather.com/api/location/search/?lattlong=45.777222,3.087025

I'm using the http request activity. When the server return response, Elsa throw the error:
`
Elsa.Services.WorkflowRunner[0]
      Failed to run activity f5bcf1b8-d663-4975-9d67-5d3f10f3cd92 of workflow 10c0b91946ea4cd997bbab113c8c10b2
      System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'.
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
         at Elsa.Activities.Http.Parsers.JsonHttpResponseBodyParser.ParseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
         at Elsa.Activities.Http.SendHttpRequest.OnExecuteAsync(ActivityExecutionContext context)
         at Elsa.ActivityTypeProviders.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityType>b__3>d.MoveNext()
      --- End of stack trace from previous location ---
         at Elsa.Services.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, RuntimeActivityInstance activity, CancellationToken cancellationToken)
`

this is the json of the activity
`{
      "$id": "26",
      "activityId": "f5bcf1b8-d663-4975-9d67-5d3f10f3cd92",
      "type": "SendHttpRequest",
      "displayName": "Send HTTP Request",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "persistOutput": false,
      "properties": [
        {
          "$id": "27",
          "name": "Url",
          "syntax": "Liquid",
          "expressions": {
            "$id": "28",
            "Literal": "https://www.metaweather.com/api/location/search/?lattlong=",
            "JavaScript": "",
            "Liquid": "https://www.metaweather.com/api/location/search/?lattlong={{ Variables.Latitude }},{{ Variables.Longitude }}"
          }
        },
        {
          "$id": "29",
          "name": "Method",
          "expressions": {
            "$id": "30",
            "Literal": "GET"
          }
        },
        {
          "$id": "31",
          "name": "Content",
          "expressions": {
            "$id": "32"
          }
        },
        {
          "$id": "33",
          "name": "ContentType",
          "expressions": {
            "$id": "34"
          }
        },
        {
          "$id": "35",
          "name": "Authorization",
          "expressions": {
            "$id": "36"
          }
        },
        {
          "$id": "37",
          "name": "ReadContent",
          "expressions": {
            "$id": "38",
            "Literal": "true"
          }
        },
        {
          "$id": "39",
          "name": "SupportedStatusCodes",
          "expressions": {
            "$id": "40"
          }
        }
      ]
    }`

**Comment by sfmskywalker** [comment]
Confirmed.
