### ISSUE TITLE
HttpRequest Activity null method when adding new

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1077]
When you add an HttRequest activity if you don't move the method and you publish/run the workflow Elsa throw:

```
 Elsa.Services.WorkflowRunner[0]
      Failed to run activity bcc16cb7-a128-4df2-ac71-228461a3fa31 of workflow a9111a89141f43c98ac67c9bb3c478f0
      System.ArgumentException: The value cannot be null or empty. (Parameter 'method')
         at System.Net.Http.HttpMethod..ctor(String method)
         at Elsa.Activities.Http.SendHttpRequest.CreateRequest()
         at Elsa.Activities.Http.SendHttpRequest.OnExecuteAsync(ActivityExecutionContext context)
         at Elsa.ActivityTypeProviders.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityType>b__3>d.MoveNext()
      --- End of stack trace from previous location ---
         at Elsa.Services.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, RuntimeActivityInstance activity, Cancellatio
```

You need to set the method to post then set to get, publish the workflow to fix the problem.

**Comment by sfmskywalker** [comment]
Indeed. This is a wider issue as it applies not only to the SendHttpRequest activity, but to all activities that have a dropdown list / multi text input editor (and possibly other controls too).

**Comment by sfmskywalker** [comment]
This is fixed.
