### ISSUE TITLE
JsonSerializationException after resuming workflow 

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1141]
I have some activities that will suspend the workflow until its _input_ for the activity has been reviewed. I would then start off the activity again with: 
![image](https://user-images.githubusercontent.com/1550939/122374099-fedf0600-cf59-11eb-8319-dedb840d4ced.png)

Once the activity completes it saves and suspends on the next activity, but now it's in a different state 
Any ideas? 

Long boring error: 
```
[2021-06-17T09:00:53.912Z] Error: Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Collections.Generic.Dictionary`2+KeyCollection[System.String,System.Object]. Path 'ActivityData.ebcb8d0d-1d9f-447c-ac6f-5aeed9727d01.Keys.$values', line 1, position 1523.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Elsa.Persistence.YesSql.CustomJsonContentSerializer.Deserialize(String content, Type type)
   at YesSql.Session.Get[T](IList`1 documents, String collection)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore.FindDocumentAsync(ISession session, WorkflowInstance entity, CancellationToken cancellationToken)
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.SaveAsync(T entity, CancellationToken cancellationToken)
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.SaveAsync(T entity, CancellationToken cancellationToken)
   at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.SaveAsync(WorkflowInstance entity, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.SaveWorkflowAsync(WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.Handle(WorkflowExecuted notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken)
````

Not sure how I got to this as it seemed to be working for a bit. 

Activity data jumps from:

``` JSON 
"ActivityData": {
    "$id": "4",
    "ebcb8d0d-1d9f-447c-ac6f-5aeed9727d01": {
      "$id": "5",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "ScriptName": "EnvironmentNamingAzureToOctopus",
      "_Lifecycle": {
        "$id": "6",
        "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
        "Executing": true,
        "Executed": true
      },
      "RequireUserInput": false,
      "PossibleOutcomes": {
        "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "Done",
          "True"
        ]
      }
    },
    "2be67dd3-84ad-4e44-90bf-fddb66bb544d": {
      "$id": "7",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "ScriptName": "CreateOctopusEnvironment",
      "RequireUserInput": true,
      "_Lifecycle": {
        "$id": "8",
        "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
        "Executing": true,
        "Executed": true
      },
      "PossibleOutcomes": {
        "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "Done",
          "True"
        ]
      }
    }
  }
```

Once resumed on the second activity it now looks like: 

``` JSON 
"ActivityData": {
    "$id": "4",
    "ebcb8d0d-1d9f-447c-ac6f-5aeed9727d01": {
      "$id": "5",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$id": "6",
        "$type": "System.Collections.Generic.GenericEqualityComparer`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib"
      },
      "Count": 4,
      "Keys": {
        "$type": "System.Collections.Generic.Dictionary`2+KeyCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "ScriptName",
          "_Lifecycle",
          "RequireUserInput",
          "PossibleOutcomes"
        ]
      },
      "Values": {
        "$type": "System.Collections.Generic.Dictionary`2+ValueCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "EnvironmentNamingAzureToOctopus",
          {
            "$id": "7",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          },
          false,
          {
            "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
            "$values": [
              "Done",
              "True"
            ]
          }
        ]
      }
    },
    "2be67dd3-84ad-4e44-90bf-fddb66bb544d": {
      "$id": "8",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$ref": "6"
      },
      "Count": 4,
      "Keys": {
        "$type": "System.Collections.Generic.Dictionary`2+KeyCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "ScriptName",
          "RequireUserInput",
          "_Lifecycle",
          "PossibleOutcomes"
        ]
      },
      "Values": {
        "$type": "System.Collections.Generic.Dictionary`2+ValueCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "CreateOctopusEnvironment",
          true,
          {
            "$id": "9",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          },
          {
            "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
            "$values": [
              "Done",
              "True"
            ]
          }
        ]
      }
    }
  }
```

**Comment by sfmskywalker** [comment]
Could it be that te received input when resuming already is a dictionary-like object (`ExpandoObject`, `JObject` or `Dictionary<string, object?>`)? In which case you shouldn't deserialize it, but maybe just transform it to the desired type.

**Comment by matt4446** [comment]
I have a feeling the input is not the problem (and I've had those fun and games with expando object vs why are you a dictionary between activities a couple of months ago 😂)
I think its closer to the yessql level. I need to check, but I'm pretty sure if I update the variables instead (at a blazor component) as an example it similarly goes bang once its saved and then reloaded. Something trivial like `workflowInstance.Variables.Add("bob", "says hi")`. I could see the custom resolver is hiding in the background in its store so I don't expect it to behave any differently than within the persistence layer... So something odd is going on somewhere. This was on a build before the latest changes different output storages and then updating to it to the latest made no difference. 
Everything was working fine until I did something at 13.30 ish on Thursday (when the last successful test instance got through). I've not been able to track what helps it yet. Oddly it corruption started on staging before it started on localhost which I found to be a bit perplexing.

**Comment by matt4446** [comment]
A few days later ... Yep, I've taken the start out after its been blocked so it now just updates a single variable which is: 
`ActivityApproved`

Which then changes 
![image](https://user-images.githubusercontent.com/1550939/123093488-ab6e2b80-d423-11eb-9732-412514fe517b.png)

> After run + workflow suspended: 
``` JSON 
{
  "$id": "1",
  "InstanceId": "50fbc52f3a9a468b8bd8eff4a9b3ce57",
  "DefinitionId": "940e5b9c1a3345f89ab55785468a75cd",
  "Version": 6,
  "WorkflowStatus": "Suspended",
  "CorrelationId": "blocked input-2021-06-23T12:04:29",
  "CreatedAt": "2021-06-23T12:04:30.3539858Z",
  "LastExecutedAt": "2021-06-23T12:04:32.1740483Z",
  "Variables": {
    "$id": "2",
    "Data": {
      "Set": "A:23/06/2021 12:04:31",
      "ActivityApproved": null,
      "InputRequiredForActivityId": "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5",
      "ApproveInput": "{\r\n  \"Set\": \"A:23/06/2021 12:04:31\"\r\n}"
    }
  },
  "Output": {
    "$id": "3",
    "$type": "Elsa.Services.Models.WorkflowOutputReference, Elsa.Abstractions",
    "ActivityId": "f74ea332-f05c-4e2b-801a-04c113e63c60"
  },
  "ActivityData": {
    "$id": "4",
    "f74ea332-f05c-4e2b-801a-04c113e63c60": {
      "$id": "5",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "ScriptName": "TestInputA",
      "RequireUserInput": false,
      "PossibleOutcomes": {
        "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "Done",
          "True"
        ]
      },
      "_Lifecycle": {
        "$id": "6",
        "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
        "Executing": true,
        "Executed": true
      },
      "Output": {
        "$id": "7",
        "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
        "Set": "A:23/06/2021 12:04:31"
      }
    },
    "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5": {
      "$id": "8",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "ScriptName": "TestInputB",
      "RequireUserInput": true,
      "PossibleOutcomes": {
        "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "Done",
          "True"
        ]
      },
      "_Lifecycle": {
        "$id": "9",
        "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
        "Executing": true,
        "Executed": true
      }
    }
  },
  "BlockingActivities": [
    {
      "$id": "10",
      "ActivityId": "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5",
      "ActivityType": "RunCodeActivity"
    }
  ],
  "ScheduledActivities": [],
  "Scopes": [],
  "Id": 374
}
```

> After updating variable on the above-suspended workflow using `Elsa.Persistence.IWorkflowInstanceStore` 
``` JSON 
{
  "$id": "1",
  "InstanceId": "50fbc52f3a9a468b8bd8eff4a9b3ce57",
  "DefinitionId": "940e5b9c1a3345f89ab55785468a75cd",
  "Version": 6,
  "WorkflowStatus": "Suspended",
  "CorrelationId": "blocked input-2021-06-23T12:04:29",
  "CreatedAt": "2021-06-23T12:04:30.3539858Z",
  "LastExecutedAt": "2021-06-23T12:04:32.1740483Z",
  "Variables": {
    "$id": "2",
    "Data": {
      "Set": "A:23/06/2021 12:04:31",
      "ActivityApproved": "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5",
      "InputRequiredForActivityId": "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5",
      "ApproveInput": "{\r\n  \"Set\": \"A:23/06/2021 12:04:31\"\r\n}"
    }
  },
  "Output": {
    "$id": "3",
    "$type": "Elsa.Services.Models.WorkflowOutputReference, Elsa.Abstractions",
    "ActivityId": "f74ea332-f05c-4e2b-801a-04c113e63c60"
  },
  "ActivityData": {
    "$id": "4",
    "f74ea332-f05c-4e2b-801a-04c113e63c60": {
      "$id": "5",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$id": "6",
        "$type": "System.Collections.Generic.GenericEqualityComparer`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib"
      },
      "Count": 5,
      "Keys": {
        "$type": "System.Collections.Generic.Dictionary`2+KeyCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "ScriptName",
          "RequireUserInput",
          "PossibleOutcomes",
          "_Lifecycle",
          "Output"
        ]
      },
      "Values": {
        "$type": "System.Collections.Generic.Dictionary`2+ValueCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "TestInputA",
          false,
          {
            "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
            "$values": [
              "Done",
              "True"
            ]
          },
          {
            "$id": "7",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          },
          {
            "$id": "8",
            "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
            "Set": "A:23/06/2021 12:04:31"
          }
        ]
      }
    },
    "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5": {
      "$id": "9",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$ref": "6"
      },
      "Count": 4,
      "Keys": {
        "$type": "System.Collections.Generic.Dictionary`2+KeyCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "ScriptName",
          "RequireUserInput",
          "PossibleOutcomes",
          "_Lifecycle"
        ]
      },
      "Values": {
        "$type": "System.Collections.Generic.Dictionary`2+ValueCollection[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
        "$values": [
          "TestInputB",
          true,
          {
            "$type": "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib",
            "$values": [
              "Done",
              "True"
            ]
          },
          {
            "$id": "10",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          }
        ]
      }
    }
  },
  "BlockingActivities": [
    {
      "$id": "11",
      "ActivityId": "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5",
      "ActivityType": "RunCodeActivity"
    }
  ],
  "ScheduledActivities": [],
  "Scopes": [],
  "Id": 374
}
```

**Comment by matt4446** [comment]
configuring a slightly modified serializer for the yessql store seems to have worked: 

``` csharp
services.AddElsa(options =>
            {
                var hangFireConnectionString = configuration.GetConnectionString("HangfireConnection");
                var sp = new SerilogLoggerProvider(Log.Logger, false);
                //options.UseEntityFrameworkPersistence(ef => ef.UseSqlite());
                options
                    .UseYesSqlPersistence(config =>
                    {
                        config
                            .UseLogger(sp.CreateLogger("Elsa"))
                            .UseSqlServer(connectionString)
                            .SetTablePrefix("Elsa2_")
                            .ContentSerializer = new MyCustomJsonContentSerializer();
                        //.UseDefaultIdGenerator();
                    });
                    ... 
       });
```

Which has one change: 
`TypeNameHandling = TypeNameHandling.Auto` -> `TypeNameHandling = TypeNameHandling.Objects` 
And is working for the moment. 

``` csharp
JsonSettings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Objects,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple
            };
```

It's able to go through three alterations and reruns: 
``` json
{
  "$id": "1",
  "$type": "Elsa.Persistence.YesSql.Documents.WorkflowInstanceDocument, Elsa.Persistence.YesSql",
  "InstanceId": "e394bc45bd784ddaa4f1e6e34f69a2d7",
  "DefinitionId": "940e5b9c1a3345f89ab55785468a75cd",
  "Version": 6,
  "WorkflowStatus": "Finished",
  "CorrelationId": "blocked input-2021-06-23T21:11:36",
  "CreatedAt": "2021-06-23T21:11:38.1136131Z",
  "LastExecutedAt": "2021-06-23T21:11:56.8829811Z",
  "FinishedAt": "2021-06-23T21:11:56.8848754Z",
  "Variables": {
    "$id": "2",
    "$type": "Elsa.Models.Variables, Elsa.Abstractions",
    "Data": {
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Set": "A:23/06/2021 21:11:48:23/06/2021 21:11:52",
      "ActivityApproved": null,
      "InputRequiredForActivityId": "106314f4-dfe7-4bdb-a147-1d64a2fa6dd1",
      "ApproveInput": "{\r\n  \"Set\": \"A:23/06/2021 21:11:48:23/06/2021 21:11:52\"\r\n}"
    }
  },
  "Output": {
    "$id": "3",
    "$type": "Elsa.Services.Models.WorkflowOutputReference, Elsa.Abstractions",
    "ActivityId": "106314f4-dfe7-4bdb-a147-1d64a2fa6dd1"
  },
  "ActivityData": {
    "$id": "4",
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
    "f74ea332-f05c-4e2b-801a-04c113e63c60": {
      "$id": "5",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$id": "6",
        "$type": "System.Collections.Generic.GenericEqualityComparer`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib"
      },
      "Count": 4,
      "Keys": [
        "Comparer",
        "Count",
        "Keys",
        "Values"
      ],
      "Values": [
        {
          "$id": "7",
          "$type": "System.Collections.Generic.GenericEqualityComparer`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib"
        },
        5,
        [
          "ScriptName",
          "RequireUserInput",
          "PossibleOutcomes",
          "_Lifecycle",
          "Output"
        ],
        [
          "TestInputA",
          false,
          [
            "Done",
            "True"
          ],
          {
            "$id": "7",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          },
          {
            "$id": "8",
            "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
            "Set": "A:23/06/2021 21:11:48"
          }
        ]
      ]
    },
    "7c8f26d5-ad3f-43e4-9d3e-2d0502b743b5": {
      "$id": "8",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$ref": "6"
      },
      "Count": 9,
      "Keys": [
        "Comparer",
        "Count",
        "Keys",
        "Values",
        "ScriptName",
        "RequireUserInput",
        "PossibleOutcomes",
        "_Lifecycle",
        "Output"
      ],
      "Values": [
        {
          "$ref": "7"
        },
        4,
        [
          "ScriptName",
          "RequireUserInput",
          "PossibleOutcomes",
          "_Lifecycle"
        ],
        [
          "TestInputB",
          true,
          [
            "Done",
            "True"
          ],
          {
            "$id": "10",
            "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
            "Executing": true,
            "Executed": true
          }
        ],
        "TestInputB",
        true,
        [
          "Done",
          "True"
        ],
        {
          "$id": "9",
          "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
          "Executing": true,
          "Executed": true
        },
        {
          "$id": "10",
          "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
          "Set": "A:23/06/2021 21:11:48:23/06/2021 21:11:52"
        }
      ]
    },
    "106314f4-dfe7-4bdb-a147-1d64a2fa6dd1": {
      "$id": "11",
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
      "Comparer": {
        "$ref": "6"
      },
      "Count": 4,
      "Keys": [
        "ScriptName",
        "RequireUserInput",
        "PossibleOutcomes",
        "_Lifecycle"
      ],
      "Values": [
        "TestInputC",
        true,
        [
          "Done",
          "True"
        ],
        {
          "$id": "12",
          "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
          "Executing": true,
          "Executed": true
        }
      ],
      "ScriptName": "TestInputC",
      "RequireUserInput": true,
      "PossibleOutcomes": [
        "Done",
        "True"
      ],
      "_Lifecycle": {
        "$id": "13",
        "$type": "Elsa.Models.ActivityLifecycle, Elsa.Core",
        "Executing": true,
        "Executed": true
      },
      "Output": {
        "$id": "14",
        "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
        "Set": "A:23/06/2021 21:11:48:23/06/2021 21:11:52:23/06/2021 21:11:56"
      }
    }
  },
  "BlockingActivities": [],
  "ScheduledActivities": [],
  "Scopes": [],
  "Id": 1
}
```

While debugging it was a bit unhappy with sharing and inspecting newtonsoft coming from this library `The type 'Newtonsoft.Json.JsonConvert' exists in both`: 
`<PackageReference Include="Octopus.Client" Version="11.2.3319" />` 
This coincides with the `it stopped working on Thursday` changes. But installing the latest JSON version in the project hasn't changed anything `13.0.1` (persistence serializer from elsa yessql). So I'm still using the custom serializer for now.

**Comment by sfmskywalker** [comment]
So the issue seems to be that the JSON serializer settings for YesSQL includes type names for the expando object, which is a dictionary, which doesn't roundtrip properly. By specifying `TypeNameHandling.Objects`, it treats the expand object differently when it serializes it.

My only concern with this is: what happens if we now try to store an array of objects, where each element might be any sort of type. Will the serializer still serialize type information for each element?

**Comment by sfmskywalker** [comment]
@matt4446 are you OK with your workaround, or do you happen to have a sample project that repros the issue that I can dig into?

**Comment by matt4446** [comment]
Mostly (probably good enough, I've had time to get some of my more complicated parts working). Reading the serialised JSON is a bit horrific though (ignoring the expandos) and when it goes back to an object (WorkflowDefinition) it becomes:
A Dictionary's ValueCollection which is annoying to work with. 

With: `ActivityData['guid']` instead of being a Dictionary<string,object> it's a ValueColleciton of a dictionary: 
Dictionary. Dictoinary<string, Dictionary<string, object>> -> Dictionary<string, Dicttary.ValueCollection> 

The reason for looking at Activity Data: 
When coming back to a workflow it's nice to see what you _were_ doing. I can improve on that though rather than lazily plopping that serialized activity data back in a tab for the poor user 😅. 

I've not tried adding other Activities like the JavaSript Activity to see if they are happy with everything going on. I'll create an example if I find issues down the line.
