### ISSUE TITLE
Send HTTP Request Exception

### ISSUE THREAD

**Issue by PiotrFerenc** [elsa-workflows/elsa-core#1191]
Maybe I do somethings wrong... 🤨

I try to send GET Request and create response with data from api. 
[workflow-definition-hello-world.json.txt](https://github.com/elsa-workflows/elsa-core/files/6740934/workflow-definition-hello-world.json.txt)

Version:
`2.0.0.159`
-

Activities: Send HTTP Request
URL: https://api.nbp.pl/api/cenyzlota?format=json
Exeption:
  VS Output: 
  ```
  System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'.
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
       at Elsa.Activities.Http.Parsers.JsonHttpResponseBodyParser.ParseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
       at Elsa.Activities.Http.SendHttpRequest.OnExecuteAsync(ActivityExecutionContext context)
       at Elsa.ActivityTypeProviders.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityType>b__3>d.MoveNext()
    --- End of stack trace from previous location ---
       at Elsa.Services.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, RuntimeActivityInstance activity, CancellationToken cancellationToken)
    Elsa.Handlers.LogWorkflowExecution: Warning: An error occurred while executing activity 6c6925e3-7bd2-4722-885c-df1806df7b69. Entering Faulted state

```
Designer:
```
Fault

System.InvalidCastException
Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'.
{
 "exception": {
  "type": "System.InvalidCastException",
  "message": "Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'.",
  "stackTrace": "   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)\r\n   at Elsa.Activities.Http.Parsers.JsonHttpResponseBodyParser.ParseAsync(HttpResponseMessage response, CancellationToken cancellationToken)\r\n   at Elsa.Activities.Http.SendHttpRequest.OnExecuteAsync(ActivityExecutionContext context)\r\n   at Elsa.ActivityTypeProviders.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityType>b__3>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Elsa.Services.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, RuntimeActivityInstance activity, CancellationToken cancellationToken)",
  "innerException": null
 },
 "message": "Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'.",
 "faultedActivityId": "6c6925e3-7bd2-4722-885c-df1806df7b69",
 "activityInput": {
  "path": "/hello-world",
  "method": "GET",
  "queryString": {},
  "headers": {
   "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
   "Accept-Encoding": "gzip, deflate, br",
   "Accept-Language": "en-US,en;q=0.9,pl;q=0.8",
   "Cache-Control": "max-age=0",
   "Connection": "keep-alive",
   "Cookie": "Rider-4d457dbf=182bd734-60a1-4959-ad88-79e0c9a98f38",
   "Host": "localhost:5000",
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
   "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
   "sec-ch-ua-mobile": "?0",
   "Upgrade-Insecure-Requests": "1",
   "Sec-Fetch-Site": "none",
   "Sec-Fetch-Mode": "navigate",
   "Sec-Fetch-User": "?1",
   "Sec-Fetch-Dest": "document"
  },
  "body": null
 },
 "resuming": false
}
```

API Response:
```
[
{
"data": "2021-06-30",
"cena": 213.99
}
]
```

**Comment by PiotrFerenc** [comment]
Yes, but last version on Nuget is  2.0.0.159

https://www.nuget.org/packages/Elsa/

**Comment by tomy2105** [comment]
I believe @sfmskywalker  was talking about https://www.myget.org/feed/elsa-2/package/nuget/Elsa

**Comment by PiotrFerenc** [comment]
@tomy2105 💪 2.1.0-preview.330 

but:
 workflow working but when i go to http://localhost:5000/workflow-instances I have Exception like bellow

VS Output
```
Newtonsoft.Json.JsonSerializationException: Type specified in JSON 'Elsa.Activities.Http.Models.HttpRequestModel, Elsa.Activities.Http, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with 'Elsa.Services.Models.WorkflowOutputReference, Elsa.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. Path 'output.$type', line 5, position 81.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkWorkflowInstanceStore.OnLoading(ElsaContext dbContext, WorkflowInstance entity)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.ReadShadowProperties(TContext dbContext, T entity)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.<>c__DisplayClass12_1.<FindManyAsync>b__1(T x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.<>c__DisplayClass12_0.<<FindManyAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.FindManyAsync(ISpecification`1 specification, IOrderBy`1 orderBy, IPaging paging, CancellationToken cancellationToken)
   at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
   at Elsa.Server.Api.Endpoints.WorkflowInstances.List.Handle(String workflowDefinitionId, Nullable`1 workflowStatus, Nullable`1 orderBy, String searchTerm, Int32 page, Int32 pageSize, CancellationToken cancellationToken)
   at lambda_method824(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
and in Webbrowser console :
```
p-e04cc726.js:1 GET http://localhost:5000/v1/workflow-instances?orderBy=Started&pageSize=15 500 (Internal Server Error)
(anonymous) @ p-e04cc726.js:1
j @ p-e04cc726.js:1
O @ p-e04cc726.js:1
Promise.then (async)
S.request @ p-e04cc726.js:1
f.forEach.S.<computed> @ p-e04cc726.js:1
(anonymous) @ p-e04cc726.js:1
list @ p-e04cc726.js:1
loadWorkflowInstances @ p-aa71e17a.entry.js:1
componentWillLoad @ p-aa71e17a.entry.js:1
async function (async)
componentWillLoad @ p-aa71e17a.entry.js:1
le @ p-2ef56300.js:1
Q @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
je @ p-2ef56300.js:1
Se @ p-2ef56300.js:1
requestAnimationFrame (async)
raf @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
K @ p-2ef56300.js:1
o @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
async function (async)
(anonymous) @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
jmp @ p-2ef56300.js:1
connectedCallback @ p-2ef56300.js:1
E @ p-2ef56300.js:1
F @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
Y @ p-2ef56300.js:1
X @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
oe @ p-2ef56300.js:1
Q @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
je @ p-2ef56300.js:1
Se @ p-2ef56300.js:1
requestAnimationFrame (async)
raf @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
K @ p-2ef56300.js:1
o @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
async function (async)
(anonymous) @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
jmp @ p-2ef56300.js:1
connectedCallback @ p-2ef56300.js:1
E @ p-2ef56300.js:1
F @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
Y @ p-2ef56300.js:1
X @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
oe @ p-2ef56300.js:1
Q @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
je @ p-2ef56300.js:1
Se @ p-2ef56300.js:1
requestAnimationFrame (async)
raf @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
K @ p-2ef56300.js:1
(anonymous) @ p-2ef56300.js:1
set @ p-2ef56300.js:1
(anonymous) @ p-bba9e891.entry.js:1
o @ p-bba9e891.entry.js:1
(anonymous) @ p-bba9e891.entry.js:1
notifyListeners @ p-bba9e891.entry.js:1
O @ p-bba9e891.entry.js:1
(anonymous) @ p-bba9e891.entry.js:1
confirmTransitionTo @ p-bba9e891.entry.js:1
push @ p-bba9e891.entry.js:1
handleClick @ p-bba9e891.entry.js:1
p-e04cc726.js:1 Uncaught (in promise) Error: Request failed with status code 500
    at y (p-e04cc726.js:1)
    at p-e04cc726.js:1
    at XMLHttpRequest.a.onreadystatechange (p-e04cc726.js:1)
```

**Comment by sfmskywalker** [comment]
Perhaps you are trying to load in existing workflow instances created with pre-Elsa 2.1.0 code? The quickest way to find out is to delete the workflow instances (create a backup if you don't want to lose them first).

**Comment by PiotrFerenc** [comment]
@sfmskywalker yes. I remove old database and almost work.

1. remove old database
2. import workflow
3. execute workflow

result:
Workflow Instances -> there is my instance by I can't view details.

` Uncaught (in promise) TypeError: Cannot read property 'data' of undefined`


Alfer click Workflow Registry

`http://localhost:5000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-dae205e4.entry.js net::ERR_ABORTED 404 (Not Found)`

**Comment by sfmskywalker** [comment]
That’s odd. Any chance you can send me your solution plus workflow definition JSON?

**Comment by PiotrFerenc** [comment]
https://1drv.ms/u/s!AsyUCHvhjmpQ2wGuX-fdDjZSN8KK?e=aOTKEj

**Comment by sfmskywalker** [comment]
Perfect, thank you. I can indeed reproduce.

**Comment by sfmskywalker** [comment]
I pushed a fix just now, and will be available from MyGet as soon as the current build succeeds.

**Comment by rangga98** [comment]
sorry sir, when i try to click workflow instance or another, it throw an error like this, i don't know what to do, can you tell me what is it?. oh ya, i run elsa with this command:
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:5000' -p 14000:80 elsaworkflows/elsa-dashboard-and-server:latest

![Screenshot_2](https://user-images.githubusercontent.com/69419754/147382052-be2d552d-2bee-4bbe-919d-ad77bc4b0850.jpg)

**Comment by sfmskywalker** [comment]
@rangga98 Thank you for letting me know. However it's best if you create a new issue instead of reporting an issue unrelated to the current issue, which is not only unrelated but also closed. Thank you for understanding.
