### ISSUE TITLE
Bug?: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected 

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#131]
What i did... Create a workflow... Create a HTTP Request. Create an HTTP Response as next step. Set return value to javascript and put "lastResult" as return value.
Since i don't know how to use the javascript part (no docs) i thought this would be the object from the HTTP Request... Am i wrong or is this a bug? Do i have to return a string?

`
fail: Elsa.Services.ActivityInvoker[0]
      Error while invoking activity 2f0c9520-2c4f-477b-8b05-742ca5b6e32c of workflow ef781df5535c4d89a8287a3cb9c1f942
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Engine' with type 'Jint.Engine'. Path 'Target.Engine.Global'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Elsa.Scripting.JavaScript.Services.JavaScriptExpressionEvaluator.ConvertValue(JsValue value, Type targetType) in D:\Dev\andale-online\Elsa\elsa-core\src\scripting\Elsa.Scripting.JavaScript\Services\JavaScriptExpressionEvaluator.cs:line 113
   at Elsa.Scripting.JavaScript.Services.JavaScriptExpressionEvaluator.EvaluateAsync(String expression, Type type, WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken) in D:\Dev\andale-online\Elsa\elsa-core\src\scripting\Elsa.Scripting.JavaScript\Services\JavaScriptExpressionEvaluator.cs:line 44
   at Elsa.Expressions.WorkflowExpressionEvaluator.EvaluateAsync(IWorkflowExpression expression, Type type, WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken) in D:\Dev\andale-online\Elsa\elsa-core\src\core\Elsa.Core\Expressions\WorkflowExpressionEvaluator.cs:line 26
   at Elsa.Extensions.WorkflowExpressionEvaluatorExtensions.EvaluateAsync[T](IWorkflowExpressionEvaluator evaluator, IWorkflowExpression`1 expression, WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken) in D:\Dev\andale-online\Elsa\elsa-core\src\core\Elsa.Abstractions\Extensions\WorkflowExpressionEvaluatorExtensions.cs:line 17
   at Elsa.Activities.Http.Activities.WriteHttpResponse.OnExecuteAsync(WorkflowExecutionContext workflowContext, CancellationToken cancellationToken) in D:\Dev\andale-online\Elsa\elsa-core\src\activities\Elsa.Activities.Http\Activities\WriteHttpResponse.cs:line 145
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction) in D:\Dev\andale-online\Elsa\elsa-core\src\core\Elsa.Core\Services\ActivityInvoker.cs:line 61
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1798.4152000000001ms 202 application/xml

`

**Comment by sfmskywalker** [comment]
Sounds like a bug - the `lastResult()` should return the `HttpRequestModel` stored by the `ReceiveHttpRequest` activity, and should be able to be written as an HTTP response.

**Comment by sfmskywalker** [comment]
Yeah I see. The `WriteHttpResponse.Content` property is of type `WorkflowExpression<string>`, which means it will expect an expression that returns a string value. Right now it's trying to deserialize the object's JSON value into a "string" type, which fails (although I do get a different error than you are, so my test is different - we'll probably need to dig into your exact scenario further).

In any case, I'll see if I can make a fix that even if the expression returns an object while a string is expected, the object is simply converted to its string representation.

**Comment by sfmskywalker** [comment]
I pushed an update that fixes the issue in my scenario. Please let me know what happens in your case.
