### ISSUE TITLE
[BUG] workflow-studio can't be build

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#1334]
- go to `elsa-core/src/designer/elsa-workflows-studio`
- delete `node_modules` folder if it exists
- run `npm install`
- run `npm run build`

```
> @elsa-workflows/elsa-workflows-studio@2.1.14 build:tailwind:prod /mnt/c/Projects/GitHub/elsa-core/src/designer/elsa-workflows-studio
> cross-env NODE_ENV=production tailwind build -i ./tailwind.css -o ./src/globals/tailwind.css

/mnt/c/Projects/GitHub/elsa-core/src/designer/elsa-workflows-studio/node_modules/tailwindcss/lib/jit/corePlugins.js:242
  ...Object.fromEntries(Object.entries(corePlugins).map(([pluginName, plugin]) => {
            ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/mnt/c/Projects/GitHub/elsa-core/src/designer/elsa-workflows-studio/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Projects/GitHub/elsa-core/src/designer/elsa-workflows-studio/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @elsa-workflows/elsa-workflows-studio@2.1.14 build:tailwind:prod: `cross-env NODE_ENV=production tailwind build -i ./tailwind.css -o ./src/globals/tailwind.css`
npm ERR! Exit status 1
```

**Comment by jwillmer** [comment]
Since I reported the bug some commit has fixed it - not sure which!
