### ISSUE TITLE
MasstTransit WorkflowConsumer cannot consume scoped service IWorkflowInvoker

### ISSUE THREAD

**Issue by petedavis** [elsa-workflows/elsa-core#134]
Issue running Sample08 project

Not too sure how to fix this immediately as I'm sure the workflow invoker needs to be scoped to web requests. However this then makes it an issue trying to consume it form the WorkflowConsumer in MassTransit activity.

```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder] Lifetime: Singleton ImplementationType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder]': Cannot consume scoped service 'Elsa.Services.IWorkflowInvoker' from singleton 'Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder]'.) (Error while validating the service descriptor 'ServiceType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.OrderShipped] Lifetime: Singleton ImplementationType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.OrderShipped]': Cannot consume scoped service 'Elsa.Services.IWorkflowInvoker' from singleton 'Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.OrderShipped]'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Sample08.Program.Main(String[] args) in C:\Users\pda\source\repos\elsa-core\src\samples\Sample08\Program.cs:line 8

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder] Lifetime: Singleton ImplementationType: Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder]': Cannot consume scoped service 'Elsa.Services.IWorkflowInvoker' from singleton 'Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder]'.

Inner Exception 2:
InvalidOperationException: Cannot consume scoped service 'Elsa.Services.IWorkflowInvoker' from singleton 'Elsa.Activities.MassTransit.Consumers.WorkflowConsumer`1[Sample08.Messages.CreateOrder]'.
```

**Comment by sfmskywalker** [comment]
Good catch. The consumer itself needs to be resolved from a scope. I’ll have a look at the MT setup.

**Comment by petedavis** [comment]
Ahh yes. I think you need to use the Endpoint configuration method that takes an IConsumerFactory rather than an instance or type

**Comment by sfmskywalker** [comment]
Yes exactly. Thanks for looking!

**Comment by sfmskywalker** [comment]
@petedavis I assigned you to this issue to clarify that you picked it up (thanks for that 🙏 )
