### ISSUE TITLE
elsa workflow issue  Could not load type 'Elsa.Metadata.ActivityDescriptor' from assembly 'Elsa.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by vabs212** [elsa-workflows/elsa-core#1396]
Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      Could not load type 'Elsa.Metadata.ActivityDescriptor' from assembly 'Elsa.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Services.Models.IActivity' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
      Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Elsa.Metadata.ActivityDescriptor' from assembly 'Elsa.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Services.Models.IActivity' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.EnsureRazorPagesServices(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapFallbackToPage(IEndpointRouteBuilder endpoints, String page)
   at ElsaUserRegistrationPOC.Startup.<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in D:\Elsa\ElsaUserRegistrationPOC\ElsaUserRegistrationPOC\Startup.cs:line 109
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at ElsaUserRegistrationPOC.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\Elsa\ElsaUserRegistrationPOC\ElsaUserRegistrationPOC\Startup.cs:line 104
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
System.TypeLoadException: Could not load type 'Elsa.Metadata.ActivityDescriptor' from assembly 'Elsa.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Services.Models.IActivity' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null'.

**Comment by sfmskywalker** [comment]
It looks like you're using mixed package versions. Make sure to use only Elsa packages that have same version.
