### ISSUE TITLE
Workflow instance signalling between instances  

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1403]
Two workflows set up in a similar fashion to Master and Child workflows

Workflow instance A -> Requires approval from Workflow B -> B's instance sends a signal to for A with the  Approve / Reject kind of thing 
'A' will start off more instances .... etc' 

# Workflow 1

``` JSON 
{
  "$id": "1",
  "definitionId": "24ef635f586d495db26d61f0030f12c9",
  "versionId": "c4b1dbc3c9c54e2ba5d2f12823f21984",
  "name": "/api/me/pressMyButtons",
  "displayName": "/api/me/pressMyButtons",
  "version": 11,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "005a9652-deff-435a-900b-37dbab51c4e6",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/api/me/pressMyButtons"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "13",
      "activityId": "97f736f2-ee5f-4100-bf4e-12477acb8abb",
      "type": "SendSignal",
      "displayName": "Send Signal",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "14",
          "name": "Signal",
          "expressions": {
            "$id": "15",
            "Literal": "pressed-buttons"
          }
        },
        {
          "$id": "16",
          "name": "CorrelationId",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "17",
            "JavaScript": ""
          }
        },
        {
          "$id": "18",
          "name": "Input",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "19",
            "Literal": "",
            "JavaScript": "return correlationId;"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "20",
      "activityId": "9b480252-8783-4d22-840b-d52f69e5b3e6",
      "type": "SignalReceived",
      "displayName": "Signal Received",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "21",
          "name": "Signal",
          "expressions": {
            "$id": "22",
            "Literal": "touching"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "23",
      "activityId": "9a8c179a-b69b-4a27-b83c-7ccaf361ce48",
      "type": "SetName",
      "displayName": "Set Name",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "24",
          "name": "Value",
          "expressions": {
            "$id": "25",
            "Literal": "Touched - Done"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "26",
      "activityId": "1f42c9d9-64fb-49ba-821f-de05da98698d",
      "type": "Fork",
      "displayName": "Fork",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "27",
          "name": "Branches",
          "expressions": {
            "$id": "28",
            "Json": "[\"send\",\"wait\"]"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "29",
      "activityId": "2da84386-5cd9-4abf-8dd8-9d4665288d0b",
      "type": "Join",
      "displayName": "Join",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "30",
          "name": "Mode",
          "expressions": {
            "$id": "31"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "32",
      "activityId": "0fa88f26-1c1f-4759-8990-ece6bec8e11a",
      "type": "Correlate",
      "displayName": "Correlate",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "33",
          "name": "Value",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "34",
            "JavaScript": "return \"bob-\" + new Date();"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "35",
      "sourceActivityId": "1f42c9d9-64fb-49ba-821f-de05da98698d",
      "targetActivityId": "97f736f2-ee5f-4100-bf4e-12477acb8abb",
      "outcome": "send"
    },
    {
      "$id": "36",
      "sourceActivityId": "1f42c9d9-64fb-49ba-821f-de05da98698d",
      "targetActivityId": "9b480252-8783-4d22-840b-d52f69e5b3e6",
      "outcome": "wait"
    },
    {
      "$id": "37",
      "sourceActivityId": "9b480252-8783-4d22-840b-d52f69e5b3e6",
      "targetActivityId": "2da84386-5cd9-4abf-8dd8-9d4665288d0b",
      "outcome": "Done"
    },
    {
      "$id": "38",
      "sourceActivityId": "2da84386-5cd9-4abf-8dd8-9d4665288d0b",
      "targetActivityId": "9a8c179a-b69b-4a27-b83c-7ccaf361ce48",
      "outcome": "Done"
    },
    {
      "$id": "39",
      "sourceActivityId": "97f736f2-ee5f-4100-bf4e-12477acb8abb",
      "targetActivityId": "2da84386-5cd9-4abf-8dd8-9d4665288d0b",
      "outcome": "Done"
    },
    {
      "$id": "40",
      "sourceActivityId": "005a9652-deff-435a-900b-37dbab51c4e6",
      "targetActivityId": "0fa88f26-1c1f-4759-8990-ece6bec8e11a",
      "outcome": "Done"
    },
    {
      "$id": "41",
      "sourceActivityId": "0fa88f26-1c1f-4759-8990-ece6bec8e11a",
      "targetActivityId": "1f42c9d9-64fb-49ba-821f-de05da98698d",
      "outcome": "Done"
    }
  ],
  "id": "c4b1dbc3c9c54e2ba5d2f12823f21984"
}
```  

# Workflow 2 

``` JSON 
{
  "$id": "1",
  "definitionId": "1d0ebb4f8ff0498ab6697ef1408a93fb",
  "versionId": "60975d2dcad74f78a999717e109242e8",
  "name": "pressed-buttons -> touching",
  "displayName": "pressed-buttons -> touching",
  "version": 7,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "2491d556-02f1-4182-bd6e-46c4b9e0ba29",
      "type": "SignalReceived",
      "displayName": "Signal Received",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Signal",
          "expressions": {
            "$id": "6",
            "Literal": "pressed-buttons"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "7",
      "activityId": "73e3464f-7f3f-4625-b68c-45c184fe7599",
      "type": "SendSignal",
      "displayName": "Send Signal",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "8",
          "name": "Signal",
          "expressions": {
            "$id": "9",
            "Literal": "touching"
          }
        },
        {
          "$id": "10",
          "name": "CorrelationId",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "11",
            "JavaScript": "//from input\r\nreturn getVariable(\"previousId\");"
          }
        },
        {
          "$id": "12",
          "name": "Input",
          "expressions": {
            "$id": "13",
            "Literal": "hi"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "14",
      "activityId": "08b19e4d-69ac-4868-b2ec-647af2cdc9f4",
      "type": "StartAt",
      "displayName": "Start at",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "15",
          "name": "Instant",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "16",
            "JavaScript": "var now = currentInstant();\r\nvar tenMoreSeconds = now.Plus(Duration.FromSeconds(10));\r\nreturn tenMoreSeconds;"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "17",
      "activityId": "1774b190-a264-4a65-be7d-c13d0c71dcff",
      "type": "SetVariable",
      "displayName": "Set Variable",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "18",
          "name": "VariableName",
          "expressions": {
            "$id": "19",
            "Literal": "previousId"
          }
        },
        {
          "$id": "20",
          "name": "Value",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "21",
            "JavaScript": "return input;"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "22",
      "sourceActivityId": "08b19e4d-69ac-4868-b2ec-647af2cdc9f4",
      "targetActivityId": "73e3464f-7f3f-4625-b68c-45c184fe7599",
      "outcome": "Done"
    },
    {
      "$id": "23",
      "sourceActivityId": "2491d556-02f1-4182-bd6e-46c4b9e0ba29",
      "targetActivityId": "1774b190-a264-4a65-be7d-c13d0c71dcff",
      "outcome": "Done"
    },
    {
      "$id": "24",
      "sourceActivityId": "1774b190-a264-4a65-be7d-c13d0c71dcff",
      "targetActivityId": "08b19e4d-69ac-4868-b2ec-647af2cdc9f4",
      "outcome": "Done"
    }
  ],
  "id": "60975d2dcad74f78a999717e109242e8"
}
```

### Workflow A
![image](https://user-images.githubusercontent.com/1550939/129973921-15432afe-7b4f-4d9b-b365-576309bbf804.png)

### Workflow B
![image](https://user-images.githubusercontent.com/1550939/129973845-08636426-1534-48d5-b67c-927c8ec68f34.png)
 
## Run through 

1. Without a delaying 'start at' activity workflow B completes. No errors, but Workflow A doesn't resume. 
2. With the delaying 'start at' activity workflow B suspends, wakes up after 10 seconds but then errors at the send signal activity (after the delay): 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Activities.Signaling.SignalReceivedBookmarkProvider.GetBookmarksInternalAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken)+MoveNext()
   at Elsa.Activities.Signaling.SignalReceivedBookmarkProvider.GetBookmarksInternalAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Elsa.Activities.Signaling.SignalReceivedBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken)
   at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkIndexer.ExtractBookmarksAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, IEnumerable`1 blockingActivities, CancellationToken cancellationToken)
   at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
   at Elsa.Services.Bookmarks.BookmarkIndexer.IndexBookmarksAsync(IEnumerable`1 workflowInstances, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkIndexer.IndexBookmarksAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Handlers.UpdateBookmarks.Handle(WorkflowInstanceSaved notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.SaveAsync(WorkflowInstance entity, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.SaveWorkflowAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.Handle(WorkflowInputUpdated notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowResumer.ResumeWorkflowAsync(WorkflowInstance workflowInstance, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowInstanceExecutor.ExecuteAsync(WorkflowInstance workflowInstance, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(String workflowInstanceId, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(String workflowInstanceId, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(String workflowInstanceId, String activityId, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowLaunchpad.ExecutePendingWorkflowsAsync(IEnumerable`1 pendingWorkflows, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowLaunchpad.CollectAndExecuteWorkflowsAsync(WorkflowsQuery query, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Activities.Signaling.Services.Signaler.TriggerSignalAsync(String signal, Object input, String workflowInstanceId, String correlationId, CancellationToken cancellationToken)
   at Elsa.Activities.Signaling.SendSignal.OnExecuteAsync(ActivityExecutionContext context)
   at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken)

```

**Comment by sfmskywalker** [comment]
I tried it with the latest changes, and this now all works flawlessly.

In fact, you can now even get rid of the fork and join activities:

![image](https://user-images.githubusercontent.com/938393/130226556-c8754bd6-012c-4c1c-a005-66836084fe46.png)

That works even without the timer in the child workflow 😃
