### ISSUE TITLE
Failed to run workflow - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1432]
Rare one: 
No repo steps other than a workflow instance trying to start as the website warmups 
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Elsa.Persistence.InMemory.InMemoryStore`1.FindManyAsync(ISpecification`1 specification, IOrderBy`1 orderBy, IPaging paging, CancellationToken cancellationToken)
   at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
   at Elsa.Persistence.InMemory.InMemoryStore`1.DeleteManyAsync(ISpecification`1 specification, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkIndexer.IndexBookmarksAsync(IEnumerable`1 workflowInstances, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkIndexer.IndexBookmarksAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Handlers.UpdateBookmarks.Handle(WorkflowInstanceSaved notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.SaveAsync(WorkflowInstance entity, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.SaveWorkflowAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Handlers.PersistWorkflow.Handle(WorkflowExecutionPassCompleted notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunCoreAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken)
```

**Comment by sfmskywalker** [comment]
Do you have a sample project I can use to reproduce? I just tried to run a workflow during server startup and using the in-memory provider, but I'm not getting this issue.

**Comment by matt4446** [comment]
I imagine I could tempt one of the console samples to reproduce it, but I expect it will be far from consistent. Not sure when I'll get the chance to quite yet though.

**Comment by sfmskywalker** [comment]
Yeah I tried to do that as well. But I understand if you're busy so no rush.
