### ISSUE TITLE
[Notice of Breaking change] Quartz.Serialization.Json 3.3.3 breaks Elsa.Activities.Temporal.Quartz

### ISSUE THREAD

**Issue by shykln** [elsa-workflows/elsa-core#1454]
Hi there,

After spending a long time looking for the problem, I found that Quartz.Serialization.Json 3.3.3 would break Elsa.Activities.Temporal.Quartz. 

I guess the reason was that UseJobFactory does not exist in Quartz.SchedulerBuilder anymore.
The following error would be thrown if you are using 3.3.3. But you would be fine if you are using 3.3.2:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Quartz.SchedulerBuilder.UseJobFactory()'.
  Source=Quartz.Extensions.DependencyInjection
  StackTrace:
   at Quartz.ServiceCollectionQuartzConfigurator.UseJobFactory[T](Action`1 configure)
   at Quartz.ServiceCollectionQuartzConfigurator.UseMicrosoftDependencyInjectionScopedJobFactory(Action`1 configure)
   at Elsa.TimersOptionsExtensions.ConfigureQuartz(IServiceCollectionQuartzConfigurator quartz, Action`1 configureQuartz)
   at Elsa.TimersOptionsExtensions.<>c__DisplayClass0_0.<UseQuartzProvider>b__0(IServiceCollectionQuartzConfigurator configure)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, NameValueCollection properties, Action`1 configure)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, Action`1 configure)
   at Elsa.TimersOptionsExtensions.UseQuartzProvider(TimersOptions timersOptions, Boolean registerQuartz, Action`1 configureQuartzOptions, Action`1 configureQuartz, Action`1 configureQuartzHostedService)
   at Elsa.ElsaOptionsExtensions.<>c__DisplayClass0_0.<AddQuartzTemporalActivities>b__0(TimersOptions timer)
   at Elsa.Activities.Temporal.CommonTemporalActivityServices.AddCommonTemporalActivities(ElsaOptionsBuilder options, Action`1 configure)
   at Elsa.ElsaOptionsExtensions.AddQuartzTemporalActivities(ElsaOptionsBuilder options, Action`1 configureQuartzOptions, Action`1 configureQuartz, Action`1 configureQuartzHostedService)
   at WorkflowServer.Startup.<>c__DisplayClass7_0.<ConfigureServices>b__0(ElsaOptionsBuilder elsa) in C:\Users\Kylin\source\repos\DistributedCluster\WorkflowServer\Startup.cs:line 35
   at Microsoft.Extensions.DependencyInjection.ElsaServiceCollectionExtensions.AddElsaCore(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.DependencyInjection.ElsaServiceCollectionExtensions.AddElsa(IServiceCollection services, Action`1 configure)
   at WorkflowServer.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Kylin\source\repos\DistributedCluster\WorkflowServer\Startup.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WorkflowServer.Program.Main(String[] args) in C:\WorkflowServer\Program.cs:line 16
```

**Comment by sfmskywalker** [comment]
Thanks for the headsup 👍🏻
