### ISSUE TITLE
Workflow resume from 'start at' activity and context fidelity set to activity

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1490]
After setting the workflow context fidelity to activity it fails to load the context before it evaluates the expression on the start at activity. 

[conttext-startat-bug-ElsaQuickstarts.Server.DashboardAndServer.zip](https://github.com/elsa-workflows/elsa-core/files/7122641/conttext-startat-bug-ElsaQuickstarts.Server.DashboardAndServer.zip)

start the workflow with 
`/context-test` 

![image](https://user-images.githubusercontent.com/1550939/132371679-c653a0fa-643d-4ce1-9c5b-a3c508e7b3ea.png)

```
fail: Rebus.Retry.PoisonQueues.PoisonQueueErrorHandler[0]
      Moving message with ID "bf2e7834-8c70-46b2-8948-b276ecf742ce" to error queue "error"
      System.AggregateException: 5 unhandled exceptions (An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.) (An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.) (An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.) (An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.) (An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.)
       ---> Elsa.Exceptions.CannotSetActivityPropertyValueException: An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.
       ---> Elsa.Exceptions.ExpressionEvaluationException: Failed to evaluate expression
       ---> Jint.Runtime.JavaScriptException: Cannot read property 'When' of null
         at <anonymous>:1:54
         --- End of inner exception stack trace ---
         at Elsa.Expressions.ExpressionEvaluator.EvaluateAsync(String expression, String syntax, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.ExpressionActivityPropertyValueProvider.GetValueAsync(ActivityExecutionContext context, CancellationToken cancellationToken)
         at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.ActivityActivator.ActivateActivityAsync(ActivityExecutionContext context, Type type, CancellationToken cancellationToken)
         at Elsa.Providers.ActivityTypes.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityTypeAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
```

**Comment by sfmskywalker** [comment]
Thanks for the great repro!
