### ISSUE TITLE
Elsa.Activities.Http 2.3.0 causing ArgumentNullException in Asp.Net Core 3.1 project

### ISSUE THREAD

**Issue by OvyDev** [elsa-workflows/elsa-core#1585]
A quick summary and/or background
Argument Null Exception encountered when running "Elsa Server" quickstart using .net core 3.1  

    System.ArgumentNullException: Value cannot be null. (Parameter 'configure')
       at Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions.AddAuthorizationCore(IServiceCollection services, Action`1 configure)
       at Microsoft.Extensions.DependencyInjection.PolicyServiceCollectionExtensions.AddAuthorization(IServiceCollection services, Action`1 configure)
       at Microsoft.Extensions.DependencyInjection.PolicyServiceCollectionExtensions.AddAuthorization(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.AddAuthorizationServices(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.AddAuthorization(IMvcCoreBuilder builder)
       at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddElsaApiEndpoints(IServiceCollection services, Action`1 configureApiOptions)
       at DemoElsa.Demo.Startup.ConfigureServices(IServiceCollection services) in C:\Source\Local\DemoElsa.Demo\DemoElsa.Demo\Startup.cs:line 43
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.&lt;&gt;c__DisplayClass9_0.&lt;Invoke&gt;g__Startup|0(IServiceCollection serviceCollection)
       at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.&lt;&gt;c__DisplayClass8_0.&lt;Build&gt;b__0(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.&lt;&gt;c__DisplayClass12_0.&lt;UseStartup&gt;b__0(HostBuilderContext context, IServiceCollection services)
       at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
       at Microsoft.Extensions.Hosting.HostBuilder.Build()
       at DemoElsa.Demo.Program.Main(String[] args) in C:\Source\Local\DemoElsa.Demo\DemoElsa.Demo\Program.cs:line 16

Steps to reproduce : 
Follow the Elsa Server quickstart using .Net Core 3.1. The exception happen immediately after running.

`services.AddElsaApiEndpoints()` eventually called 
`PolicyServiceCollectionExtensions.AddAuthorization(configure)` with configure = null, and finally
`AuthorizationServiceCollectionExtensions.AddAuthorizationCore(configure)` causing Argument Null Exception.
`PolicyServiceCollectionExtensions.AddAuthorization(configure)` is from

      #region Assembly Microsoft.AspNetCore.Authorization.Policy, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
while `AuthorizationServiceCollectionExtensions.AddAuthorizationCore(configure)` is from

      #region Assembly Microsoft.AspNetCore.Authorization, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

In Asp.Net Core 3.1 `AddAuthorization()` calls `AddAuthorization(configure:null)` which then called `AddAuthorizationCore(configure)`, while in v5.0 it directly calls `AddAuthorizationCore()`. 
In AspNetCore.Authorization v5.0, `AddAuthorizationCore(configure)` requires passing non null configure (unlike in v3.1) thus the Argument Null Exception.

**Comment by mohdali** [comment]
@OvyDev I already submitted a PR and it is merged #1568 , you can get it in the preview releases
