### ISSUE TITLE
 bookmarkFinder.FindBookmarksAsync<Activity>(correlationId) returns all of that type

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1604]
Finding bookmarks by correlation id doesn't seem to filter by correlation id;
correlationId : Bookmarks-2021-10-05 15:48:34Z
```
var all = await bookmarkFinder.FindBookmarksAsync<Activities.RunCodeActivity>(correlationId: correlationId);
```

![image](https://user-images.githubusercontent.com/1550939/136058753-c9a87658-83c3-4ccd-a159-355a5fc06723.png)

The two records above being two different correlations roughly ~2 mins from each other where I should only be expecting the latter. 

Speaking of bookmarks... 
They never seem to go into the yessql store. Is there an option to persist them that I've missed? 
![image](https://user-images.githubusercontent.com/1550939/136059859-eac6dfd4-7eba-4c23-a371-c5ddc18ea0af.png)

And they all disappear when the app restarts

**Comment by matt4446** [comment]
beginning at: 
![image](https://user-images.githubusercontent.com/1550939/136377688-b7faee3b-6e2a-4d9e-a42c-746a3305efb2.png)


```
10/07/2021 12:20:30 +01:00 Unhandled exception rendering component: "An expression of non-boolean type specified in a context where a condition is expected, near 'or'."
Microsoft.Data.SqlClient.SqlException (0x80131904): An expression of non-boolean type specified in a context where a condition is expected, near 'or'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.FindManyAsync(ISpecification`1 specification, IOrderBy`1 orderBy, IPaging paging, CancellationToken cancellationToken)
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.FindManyAsync(ISpecification`1 specification, IOrderBy`1 orderBy, IPaging paging, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkFinder.FindBookmarksAsync(String activityType, IEnumerable`1 bookmarks, String correlationId, String tenantId, CancellationToken cancellationToken)
```

**Comment by matt4446** [comment]
Its failed sql
``` sql
exec sp_executesql N'SELECT DISTINCT [Elsa2_Bookmarks_Document].* FROM [Elsa2_Bookmarks_Document] INNER JOIN [Elsa2_Bookmarks_BookmarkIndex] AS [BookmarkIndex_a1] ON [BookmarkIndex_a1].[DocumentId] = [Elsa2_Bookmarks_Document].[Id] WHERE ((([BookmarkIndex_a1].[TenantId] IS NULL) and ([BookmarkIndex_a1].[ActivityType] = @p0)) and (@p1 or ([BookmarkIndex_a1].[CorrelationId] = @p2)))',N'@p0 nvarchar(4000),@p1 bit,@p2 nvarchar(4000)',@p0=N'RunCodeActivity',@p1=0,@p2=N'Bookmarks-2021-10-06 08:15:35Z'
```

Messages:
```
Msg 4145, Level 15, State 1, Line 1
An expression of non-boolean type specified in a context where a condition is expected, near 'or'.

Completion time: 2021-10-08T16:50:38.1811600+01:00
```

**Comment by matt4446** [comment]
The later problem was with the collect and execute 😁. 
![image](https://user-images.githubusercontent.com/1550939/136636481-bc1793bf-a2e8-4179-b701-2eb35588c9b9.png)

The bookmarking part seems to be functioning ok in the demo project.

**Comment by sfmskywalker** [comment]
Well I certainly wouldn’t want to bereft you of your fun :D

Feel free to use linqkit - it may prove useful in other areas as well.
