### ISSUE TITLE
AutoMapper.AutoMapperMappingException: Error mapping types

### ISSUE THREAD

**Issue by cfrelet** [elsa-workflows/elsa-core#1615]
Hi,
I'm facing the same issue as explained in #209 I think. It seems fixed though. But I'm using Elsa 2.2.1. Maybe not included in that version.
If you have any quick fix in my code structure I would be happy to do it.

In my Startup.cs project I declare a mapper:

```
//automapper
	var mapperConfig = new MapperConfiguration(
		cfg =>
		{
			cfg.CreateMap<QuoteRequestContract, QuoteRequest>();
		});
	var mapper = mapperConfig.CreateMapper();
	services.AddSingleton(mapper);
```

The startup also include the start of Elsa server + dashboard using mongo DB. (I tried to move the mapper before or after it doesn't change the behavior)
```
// Elsa services.
var elsaSection = Configuration.GetSection("Elsa");
services
.AddElsa(
	elsa => elsa
		.UseMongoDbPersistence(
			opts =>
			{
				opts.ConnectionString = mongoDbPath + "/" + mongoDbName;
				opts.DatabaseName = mongoDbName;
			})
		.AddConsoleActivities()
		.AddHttpActivities(elsaSection.GetSection("Http").Bind)
		.AddQuartzTemporalActivities()
		.AddWorkflowsFrom<Startup>()
		// Add custom activities
		.AddActivitiesFrom<PricingRfq>());

// Elsa API endpoints.
services.AddElsaApiEndpoints();

// For Elsa Dashboard.
services.AddRazorPages();
```
The error I get when clicking on "Workflow Definitions" 
![image](https://user-images.githubusercontent.com/45927310/136523506-b8536c2e-1a9f-4374-aa17-f13315da903b.png)

```
Is the following:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      AutoMapper.AutoMapperMappingException: Error mapping types.

      Mapping types:
      Object -> IList`1
      System.Object -> System.Collections.Generic.IList`1[[Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel, Elsa.Server.Api, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null]]
       ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

      Mapping types:
      WorkflowDefinition -> WorkflowDefinitionSummaryModel
      Elsa.Models.WorkflowDefinition -> Elsa.Server.Api.Endpoints.WorkflowDefinitions.WorkflowDefinitionSummaryModel
         at lambda_method106(Closure , WorkflowDefinition , WorkflowDefinitionSummaryModel , ResolutionContext )
         at lambda_method105(Closure , Object , IList`1 , ResolutionContext )
         --- End of inner exception stack trace ---
         at lambda_method105(Closure , Object , IList`1 , ResolutionContext )
         at Elsa.Server.Api.Endpoints.WorkflowDefinitions.List.Handle(Nullable`1 page, Nullable`1 pageSize, Nullable`1 version, CancellationToken cancellationToken)
         at lambda_method97(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IOptions`1 options, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
The weird thing is if I start with a clean DB the workflow load properly the first time I load the json and then it get stuck. after a couple of stop/start even without touching the json part. So I'm quite confused.

**Comment by cfrelet** [comment]
it's all good for me. thx a lot
