### ISSUE TITLE
how to use sqlServer in Sample19?

### ISSUE THREAD

**Issue by zsanhong** [elsa-workflows/elsa-core#174]
I want to use sqlServer in Sample19,So I change the appsettings.json:
"ConnectionStrings": {
        "SqlServer": "Data Source=.;Integrated Security=SSPI;Initial Catalog=MyTest;"
    },
and in the fold of Sample19 ,I run the cmd as :
SET EF_CONNECTIONSTRING="Data Source=.;Integrated Security=SSPI;Initial Catalog=MyTest;"
dotnet ef database update --context ElsaContext   
and I got the wrong msg:

System.ArgumentException: Keyword not supported: '"data source'.
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Keyword not supported: '"data source'.

so ,How to use sqlServer in the example? thanks

**Comment by sfmskywalker** [comment]
Make sure to also update the `AddElsa` call in `Startup`. It needs to be changed to use SqlServer.

In any case, I’ll add a sample project using SqlServer.

**Comment by zsanhong** [comment]
Yes,I also change the Startup.cs:
  services
                // Add workflow services.
                .AddElsa(x => x.AddEntityFrameworkStores(x => x.UseSqlServer(Configuration.GetConnectionString("SqlServer"))))

**Comment by LeePepe** [comment]
I have similar problems. I want to use sqlserver and  `Startup` is changed. But when I try to call  `WorkflowDefinitionStore.ListAsync`. It throw an exception. 

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'WorkflowDefinitionVersions'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowDefinitionStore.ListAsync(VersionOptions version, CancellationToken cancellationToken)
```

**Comment by sfmskywalker** [comment]
It looks like the WorkflowDefinitionVersions table doesn’t exist. If so, make sure to run the migrations first. Let me know if you need help with that.

**Comment by zsanhong** [comment]
please add a sqlServer example,thank!

**Comment by sfmskywalker** [comment]
Hi @zsanhong , please check out the new [Sample22](https://github.com/elsa-workflows/elsa-core/tree/develop/src/samples/Sample22) for a working example.

Make sure to first run the SqlServer migrations against your SQL Server (or use the containerized version if you like).

E.g.

```bash
SET EF_CONNECTIONSTRING="Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;"
dotnet ef database update --context SqlServerContext
```

Notice the `--context` option - this is key to selecting the desired EF provider. 
More details: https://github.com/elsa-workflows/elsa-core/blob/develop/src/persistence/Elsa.Persistence.EntityFrameworkCore/README.md

**Comment by zsanhong** [comment]
SET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;
dotnet ef database update --context SqlServerContext

and it works. so remember not to add "" in  SET EF_CONNECTIONSTRING=

**Comment by kashish237** [comment]
> Make sure to also update the `AddElsa` call in `Startup`. It needs to be changed to use SqlServer.
> 
> In any case, I’ll add a sample project using SqlServer.

Hi,
Please share the link of sample project using SQL Server.

**Comment by kashish237** [comment]
> It looks like the WorkflowDefinitionVersions table doesn’t exist. If so, make sure to run the migrations first. Let me know if you need help with that.

How to run migration first. Please add proper documentation

**Comment by sfmskywalker** [comment]
Hi @kashish237 ,

I just updated [my comment](https://github.com/elsa-workflows/elsa-core/issues/174#issuecomment-558837378) with updated links to both the sample as well as the readme about how to run EF migrations.

Hope that helps.

**Comment by TarekSalha** [comment]
Hi guys,
for all lonely souls building the ef core migration using vscode and powershell instead of cmd:
You need to interchange the `SET EF_CONNECTIONSTRING` command with
`$env:EF_CONNECTIONSTRING="Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;"`

**Comment by naveen-sharma-source** [comment]
No DbContext named 'SqlServerContext' was found.This is the error i am getting following the instruction mention above by all the users.Can you please help me in recifying the issue.

**Comment by sfmskywalker** [comment]
What is the current directory under which you issued the dotnet ef tool command?

**Comment by naveen-sharma-source** [comment]
Hi Thanks for reply.

I am working on sample 22.and run the commands under same folder where csproj file exist.

**SET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;
dotnet ef database update --context SqlServerContext**

**Comment by sfmskywalker** [comment]
I see. Try running the command from `src\persistence\Elsa.Persistence.EntityFrameworkCore` instead.

**Comment by naveen-sharma-source** [comment]
Wow. Work Like magic.Thanks a lot.
 
Now this leads to one question.Can you please help in that. How can we do these steps in productions. as we cannot take the code to production servers.

**Comment by HarshadPansuriya8460** [comment]
Sample22 Demo link is broken.  I want to connect Elsa workflow with EntityFramework Core with Sql Server Demo

**Comment by sfmskywalker** [comment]
Thanks, I just fixed the links. Note: these reference samples in Elsa 1 and aren't applicable to Elsa 2. For Elsa 2, please checkout this example: https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/persistence/Elsa.Samples.Persistence.EntityFramework

**Comment by NithisNevi** [comment]
I am getting an issue like Microsoft.Data.SqlClient.SqlException: 'Invalid object name 'Elsa.Workflow Instances while trying to connect with the DB. Any inputs is appreciated !
