### ISSUE TITLE
Bug in SqlServer migration?

### ISSUE THREAD

**Issue by zsanhong** [elsa-workflows/elsa-core#197]
In the fold Elsa.Persistence.EntityFrameworkCore,I run the cmd:
 SET EF_PROVIDER=SqlServer
SET EF_CONNECTIONSTRING="Server=localhost; Database=elsadb; Trusted_Connection=True;"
dotnet ef database update
but I get the wrong msg:
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [elsadb];
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='60']
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
    ALTER DATABASE [elsadb] SET READ_COMMITTED_SNAPSHOT ON;
END;
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [__EFMigrationsHistory] (
    [MigrationId] nvarchar(150) NOT NULL,
    [ProductVersion] nvarchar(32) NOT NULL,
    CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Applying migration '20191116105145_InitialCreate'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [WorkflowDefinitionVersions] (
    [Id] INTEGER NOT NULL,
    [VersionId] TEXT NULL,
    [DefinitionId] TEXT NULL,
    [Version] INTEGER NOT NULL,
    [Name] TEXT NULL,
    [Description] TEXT NULL,
    [Variables] TEXT NULL,
    [IsSingleton] INTEGER NOT NULL,
    [IsDisabled] INTEGER NOT NULL,
    [IsPublished] INTEGER NOT NULL,
    [IsLatest] INTEGER NOT NULL,
    CONSTRAINT [PK_WorkflowDefinitionVersions] PRIMARY KEY ([Id])
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [WorkflowInstances] (
    [Id] INTEGER NOT NULL,
    [InstanceId] TEXT NULL,
    [DefinitionId] TEXT NULL,
    [Version] INTEGER NOT NULL,
    [Status] TEXT NOT NULL,
    [CorrelationId] TEXT NULL,
    [CreatedAt] TEXT(48) NOT NULL,
    [StartedAt] TEXT(48) NULL,
    [FinishedAt] TEXT(48) NULL,
    [FaultedAt] TEXT(48) NULL,
    [AbortedAt] TEXT(48) NULL,
    [Scopes] TEXT NULL,
    [Input] TEXT NULL,
    [ExecutionLog] TEXT NULL,
    [Fault] TEXT NULL,
    CONSTRAINT [PK_WorkflowInstances] PRIMARY KEY ([Id])
);
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [WorkflowInstances] (
    [Id] INTEGER NOT NULL,
    [InstanceId] TEXT NULL,
    [DefinitionId] TEXT NULL,
    [Version] INTEGER NOT NULL,
    [Status] TEXT NOT NULL,
    [CorrelationId] TEXT NULL,
    [CreatedAt] TEXT(48) NOT NULL,
    [StartedAt] TEXT(48) NULL,
    [FinishedAt] TEXT(48) NULL,
    [FaultedAt] TEXT(48) NULL,
    [AbortedAt] TEXT(48) NULL,
    [Scopes] TEXT NULL,
    [Input] TEXT NULL,
    [ExecutionLog] TEXT NULL,
    [Fault] TEXT NULL,
    CONSTRAINT [PK_WorkflowInstances] PRIMARY KEY ([Id])
);
Microsoft.Data.SqlClient.SqlException (0x80131904): 第 7 个列、参数或变量: 不能对数据类型 text 指定列宽。
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 1591
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlInternalConnection.cs:line 618
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1169
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1719
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 2857
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1395
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery() in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 974
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:7051440a-ef14-4099-a858-d4910d2297db
Error Number:2716,State:1,Class:16
第 7 个列、参数或变量: 不能对数据类型 text 指定列宽。

is this a bug? thanks

**Comment by zsanhong** [comment]
for run the "dotnet ef database update" cmd, I add 
  <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
 in Elsa.Persistence.EntityFrameworkCore.csproj file
would anyone run the cmd and tell me what's the msg?

**Comment by sfmskywalker** [comment]
Turns out the issue is that these migrations were created using the Sqlite provider, which don't work when executing against SQL Server.

To fix this, I generated two sets of migrations: one for Sqlite and one for SQL Server as per the documentation [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli).

To run the migrations do SQL Server, do:

```bash
SET EF_CONNECTIONSTRING="Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;"
dotnet ef database update --context SqlServerContext
```

Make sure to use your own connection string.

I just added [Sample22](https://github.com/elsa-workflows/elsa-core/tree/develop/src/samples/Sample22) showing how to setup a connection to SQL Server.

It contains a docker-compose file that starts SQL Server in a container. You can use the abve connection string to run the migrations against that server, and then run Sample22 to see the DB connection working (it will simply store a workflow definition in the WorkflowDefinitionVersions table).

Let me know how it goes!

**Comment by zsanhong** [comment]
In the fold Elsa.Persistence.EntityFrameworkCore,I run the cmd
SET EF_CONNECTIONSTRING="Server=localhost;Database=Elsa;Trusted_Connection=True;"
then I run  cmd 
dotnet ef database update --context SqlServerContext

and I got msg :
System.ArgumentException: Keyword not supported: '"server'.
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Common\src\Microsoft\Data\Common\DbConnectionOptions.Common.cs:line 586
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\Common\DbConnectionOptions.cs:line 25
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnectionString.cs:line 221
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnectionFactory.cs:line 142
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Common\src\Microsoft\Data\ProviderBase\DbConnectionFactory.cs:line 200
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnectionHelper.cs:line 72
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 452
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString) in E:\agent1\_work\31\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 124
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Keyword not supported: '"server'.

**Comment by sfmskywalker** [comment]
Try

SET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Password=Secret_password123!;

Without quotes around the connection string. I made a mistake when pasting in the example. I’ll update the readme as well.

**Comment by zsanhong** [comment]
It works. thank you, sfmskywalker.Great job

**Comment by Harshgupta71** [comment]
I am still facing the same issue 

![image](https://user-images.githubusercontent.com/16573894/95242888-d1906480-07dd-11eb-9d13-3382fb47352f.png)

**Comment by prxy15** [comment]
> I am still facing the same issue
> 
> ![image](https://user-images.githubusercontent.com/16573894/95242888-d1906480-07dd-11eb-9d13-3382fb47352f.png)

hi,maybe this can help you 

open powershell,
in powershell write this:

`$Env:EF_CONNECTIONSTRING = "Server=(localdb)\MSSQLLocalDB;Database=OrquestadorDB;User=ELSA;Password=ELSAADMIN!;"`

(this work for SqlServer Express from visual studio 2019 community)

then check if env var was ok:

`$Env:EF_CONNECTIONSTRING
`
and run migrations in same powershell window

`dotnet ef database update --context SqlServerContext
`

**Comment by BenRodney** [comment]
Did you ever get this to work? I have exactly the same problem......
