### ISSUE TITLE
Update to use YamlDotNet nuget package

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#225]
I'm currently going through package dependencies of Elsa so we can get our commercial team to approve usage. I noticed that `Elsa.Core` uses package [YamlDotNet.NetStandard 4.0.0](https://www.nuget.org/packages/YamlDotNet.NetStandard/4.0.0). This has been unlisted and doesn't have a link to licence information.
Is it possible to switch over to [YamlDotNet](https://www.nuget.org/packages/YamlDotNet/) which looks like it's from the same author, but does include licence info? 
I'm happy to make the change if you think it's ok @sfmskywalker.

**Comment by sfmskywalker** [comment]
By all means, go for it.

**Comment by jamesdoran** [comment]
Is the Yaml formatter required? By default the dashboard and all samples use Json. It is a public type though.

The reason I ask is that I've just tested the existing `YamlTokenFormatter` using `Sample20` and got an exception. I changed the code as follows to use the YamlTokenFormatter:
```csharp
// Test serialization.
var yaml1 = serializer.Serialize(executionContext1.Workflow.ToInstance(), YamlTokenFormatter.FormatName);
var yaml2 = serializer.Serialize(executionContext2.Workflow.ToInstance(), YamlTokenFormatter.FormatName);

Console.WriteLine(yaml1);
Console.WriteLine(yaml2);

// Test deserialization.
// Exception occurs here
var workflowInstance1 = serializer.Deserialize<WorkflowInstance>(yaml1, YamlTokenFormatter.FormatName);
var workflowInstance2 = serializer.Deserialize<WorkflowInstance>(yaml2, YamlTokenFormatter.FormatName);
```

Exception details:

```csharp
Newtonsoft.Json.JsonSerializationException: Cannot convert value to NodaTime.Instant ---> NodaTime.Utility.InvalidNodaDataException: Unexpected token parsing Instant. Expected String, got Date.
  at at NodaTime.Serialization.JsonNet.NodaPatternConverter`1.ReadJsonImpl(JsonReader reader, JsonSerializer serializer)
  at at NodaTime.Serialization.JsonNet.NodaConverterBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
  --- End of inner exception stack trace ---
  at at NodaTime.Serialization.JsonNet.NodaConverterBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
  at at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
  at at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
  at at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
  at at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
  at at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
  at Elsa.Serialization.WorkflowSerializer.Deserialize[T](JToken token) in D:\repos\elsa-core\src\core\Elsa.Core\Serialization\WorkflowSerializer.cs:43
  at Elsa.Serialization.WorkflowSerializer.Deserialize[T](String data, String format) in D:\repos\elsa-core\src\core\Elsa.Core\Serialization\WorkflowSerializer.cs:38
  at Sample20.Program.Main(String[] args) in D:\repos\elsa-core\src\samples\Sample20\Program.cs:46
  at at Sample20.Program.<Main>(String[] args)
```

I can look into the problem, but thought I'd check to see if it can be removed instead first.

**Comment by sfmskywalker** [comment]
I see. I added it at the start of the project to provide an option to developers to include workflows as YAML files. I still would like to have that option, but at the same time it’s not worth it if it’s currently blocking you. Perhaps comment out everything YAML, and I’ll look into solving the serialization issue at a later time.

**Comment by jamesdoran** [comment]
I understand. No worries. I’ll take a look at fixing the issue.

**Comment by sfmskywalker** [comment]
That's amazing, thank you. I just had a quick glance at the `YamlTokenFormatter`, and I think it's a simple matter of specifying a properly-configured `JsonSerializerSettings` object as is done in `JsonTokenFormatter`. It would probably exactly the same settings, but with an additional `ExpandoObjectConverter` added to the Converters collection of the settings.

**Comment by jamesdoran** [comment]
Thanks so much for looking into it, that’ll save me a heap of time :)

**Comment by jamesdoran** [comment]
Thanks again for the guidance. Wasn't quite a copy and paste of the json settings. Found I needed to remove CamelCasePropertyNamesContractResolver as the yaml already had correct casing, and it was forcing the activity state jtokens to be camel too which then caused deserialization exceptions when the workflow was running.

I'll close this one create a PR

**Comment by sfmskywalker** [comment]
I’m glad you could fix it. Thanks a lot!
