### ISSUE TITLE
Problem adding Elsa dashboard to MVC

### ISSUE THREAD

**Issue by akghasemi** [elsa-workflows/elsa-core#2414]
Hi,
I have Mvc  project in configure in startup when I call 
app.UseHttpActivities();

I get this error in all the pages in my application 

26.10.2021 16:48:32.571 [ERROR] [Microsoft.AspNetCore.Server.Kestrel] [Microsoft.AspNetCore.Http.DefaultHttpContext] [Microsoft.AspNetCore.Http.DefaultHttpContext] - Connection id "0HMCOHUI2QFA6", Request id "0HMCOHUI2QFA6:00000003": An unhandled exception was thrown by the application.
System.InvalidOperationException: Cannot resolve 'Microsoft.AspNetCore.Authorization.IAuthorizationService' from root provider because it requires scoped service 'Microsoft.AspNetCore.Authorization.IAuthorizationHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddHttpServices>b__1_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)
   at lambda_method19(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at NetinsightWebPortalExt.Middleware.Api.FetchSessionInformationMiddleware.Invoke(HttpContext httpContext, ISessionObject session, IUserInfoCheckUp userInfoChecker, NiContext context, ILog logger, IConfiguration configuration) in D:\SourceCodes\netinsight Web Portal 2.0\NetinsightWebPortal2_Elsa2\NetinsightWebPortalExt\Middleware\Api\FetchSessionInformationMiddleware.cs:line 65
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

and I don't know where it is coming from

**Comment by sfmskywalker** [comment]
Others have complained about this as well but I can't seem to reproduce it. Perhaps you can send me a (sample) project demonstrating this issue?
