### ISSUE TITLE
An unhandled exception occurred while processing the request - Elsa Dashboard(Version-01.2.1.19)

### ISSUE THREAD

**Issue by vmr1689** [elsa-workflows/elsa-core#243]
Opening the dashboard url \elsa\home has been throwing internal server error when creating ASP.Net Core MVC web application (.NET core version 3.1.1).

Elsa - Version-01.2.1.19
Elsa Dashboard -Version-01.2.1.19
![Elsa Dashboard Error 1](https://user-images.githubusercontent.com/55023964/72867734-ec7d8000-3d05-11ea-9e0e-959fd3c0096f.PNG)
![Elsa Dashboard Error 2](https://user-images.githubusercontent.com/55023964/72867735-ec7d8000-3d05-11ea-8d65-e35f3d474c02.PNG)

**Comment by vmr1689** [comment]
Issue has solved by reinstalling visual studio 2019 16.4.3

**Comment by vmr1689** [comment]
The above issue has been reproduced in platform Windows 7 but not in Windows 10. 

The thread 0x2650 has exited with code 0 (0x0).
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "18014398523977498630", Request ID "80000007-0003-fa00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
Could not find Windows Runtime type 'Windows.Storage.Streams.IBuffer'.
Could not find Windows Runtime type 'Windows.Storage.Streams.InputStreamOptions'.
Could not find Windows Runtime type 'Windows.Storage.Streams.IInputStream'.
Could not find Windows Runtime type 'Windows.Storage.Streams.IOutputStream'.
Could not find Windows Runtime type 'Windows.Storage.Streams.IRandomAccessStream'.
Could not find Windows Runtime type 'Windows.Storage.Streams.IInputStream'.
Could not find Windows Runtime type 'Windows.Storage.Streams.InputStreamOptions'.
Could not find Windows Runtime type 'Windows.Storage.CreationCollisionOption'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at Scrutor.TypeSourceSelector.<>c.<InternalFromAssemblies>b__20_0(Assembly asm)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Scrutor.LifetimeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy strategy)
   at Scrutor.ServiceTypeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Scrutor.ImplementationTypeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Scrutor.TypeSourceSelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Elsa.Dashboard.Extensions.ActivityDefinitionListExtensions.Discover(ActivityDefinitionList list, Action`1 selector)
   at Elsa.Dashboard.Extensions.ActivityDefinitionListExtensions.DiscoverActivities(ElsaDashboardOptions options)
   at Elsa.Dashboard.Extensions.DashboardServiceCollectionExtensions.<>c.<AddElsaDashboard>b__0_0(ElsaDashboardOptions x)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at AspNetCore.Areas_Elsa_Views_Shared_CustomScripts.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Areas_Elsa_Views_Shared__Layout.<ExecuteAsync>b__22_1()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Areas_Elsa_Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Foundation.IAsyncInfo'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.IBuffer'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.InputStreamOptions'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.IInputStream'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.IOutputStream'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.IRandomAccessStream'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.IInputStream'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.Streams.InputStreamOptions'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Storage.CreationCollisionOption'.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
The program '[8704] iisexpress.exe' has exited with code -1 (0xffffffff).

Please provide solutions...

**Comment by sfmskywalker** [comment]
I’ve seen this before. It happens when trying to scan all referenced assemblies for a given type using Scrutor. There is a method that uses this when registering the Dashboard services, trying to discover all IActivity implementations automatically to describe them so that they are available from the activity picker in the designer. 

I’ll think of a solution. Meanwhile, you can work around this by passing along the assemblies to scan manually, instead of automatically scanning al referenced assemblies. I’ll provide an example as soon as I’m behind a computer.

**Comment by sfmskywalker** [comment]
Here's how you would specify what assemblies to scan to "discover" available activities:

```csharp
services.AddElsaDashboard(options => options
    .Configure(x => x.ActivityDefinitions.Discover(t => t
        .FromAssembliesOf(typeof(SetVariable) /*, additional types from different assemblies*/))));
```

The above example only looks for activities in Elsa.Core (since that's where `SetVariable` exists). If you have custom activities, you will need to include that assembly a well, e.g. `typeof(MyCustomActivity)`.

**Comment by vmr1689** [comment]
Thank you so much. I will try the above steps for this issue. 

Is it a temporary solution for windows 7 or will it get fixed in any future version?

**Comment by sfmskywalker** [comment]
It depends on if I can figure out why the exception occurs during assembly scanning, and if I can catch & ignore such exceptions. So, we'll have to see :)

**Comment by sfmskywalker** [comment]
Just as an update: this issue will be gone with the release of Elsa 2.
