### ISSUE TITLE
NullReferenceException with mongodb persistance on a workflow with cron job.

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [elsa-workflows/elsa-core#2597]
dotnet 5.0 api
Elsa 2.3.0 packages with mongodb persistance

Steps to reproduce:
1) Create a workflow with a cron activity, publish workflow.
2) check the boxes to persits workflow (by the way, i'm not sure what they mean but would be nice to have this documented as well, in which cases we should do this or that checkbox...)

![image](https://user-images.githubusercontent.com/94364525/146374580-f1ffcbfa-f376-4c8d-a2f4-d144346050d1.png)

Stacktrace:
`warn: Elsa.Services.Workflows.WorkflowRunner[0]
      Failed to run workflow 747308675ffb491ea6c24536aebc9c3c
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Services.Models.SaveWorkflowContext.get_ContextType()
         at Elsa.Services.WorkflowContexts.WorkflowContextManager.SaveContextAsync(SaveWorkflowContext context, CancellationToken cancellationToken)
         at Elsa.Handlers.PersistWorkflowContext.SaveWorkflowContextAsync(WorkflowExecutionContext workflowExecutionContext, WorkflowContextFidelity fidelity, Boolean always, CancellationTo
ken cancellationToken)
         at Elsa.Handlers.PersistWorkflowContext.Handle(ActivityExecuted notification, CancellationToken cancellationToken)
         at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.WorkflowRunner.RunCoreAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.WorkflowRunner.RunAsync(`

**Comment by sfmskywalker** [comment]
Can't reproduce with current version (master). Perhaps you can try with the 2.4 preview packages [available from MyGet](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-feeds#myget)?

**Comment by sfmskywalker** [comment]
Actually, I **can** reproduce the issue - I just didn't look good enough 😄 

Although it's not really an issue (it's a warning), it is better to handle the case where a workflow is not configured with a workflow context type instead of catching an exception.

I will push a fix.
