### ISSUE TITLE
App crashes when I want to receive masstransit messages

### ISSUE THREAD

**Issue by fthmlymz** [elsa-workflows/elsa-core#2646]
Hi,

I downloaded the elsa-core source code and compiled it without any problems. I created a new asp.net core .net 6.0 web api project. later on
Elsa.Activities.Masstransit
Elsa.Activities.Http
Elsa.Core
Elsa.Designer.Components.Web

I gave it as a reference.

I set the content of the WebApi project as follows.

I created a new workflow with Elsa.designer. I added "ReceiveMassTransitMessage" as the first item and saved immediately. After publishing, I got an error as below.

In summary; When I add "ReceiveMassTransitMessage" on the designer and publish it, the application crashes. What could be the reason for this, how can we solve it

**program.cs-startup.cs**

````
using Elsa.Activities.MassTransit.Extensions;
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Elsa.Persistence.EntityFramework.SqlServer;
using MainDashboard.API.Consumers;
using MainDashboard.API.Data;
using MassTransit;

var builder = WebApplication.CreateBuilder(args);
ConfigurationManager configuration = builder.Configuration;
IWebHostEnvironment environment = builder.Environment;



builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();




#region Elsa connection strings 
var connectionString = builder.Configuration.GetConnectionString("ElsaDbConnection");
builder.Services
   .AddDbContextFactory<DataContext>(options => options.UseSqlServer(connectionString))
   .AddCors(cors => cors.AddDefaultPolicy(policy => policy.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin()))
   .AddElsa(elsa => elsa
       .UseEntityFrameworkPersistence(ef => ef.UseSqlServer(connectionString))
       .AddJavaScriptActivities()
       .AddHttpActivities(builder.Configuration.GetSection("Elsa").GetSection("Server").Bind)
       .AddEmailActivities(builder.Configuration.GetSection("Elsa").GetSection("Smtp").Bind)
       .AddMassTransitActivities())
   .AddElsaApiEndpoints();
builder.Services.AddElsaSwagger();
#endregion


#region RabbitMQ connection conf.
builder.Services.AddMassTransit(x =>
{
    x.AddConsumer<WfConsumer>();

    x.UsingRabbitMq((context, cfg) =>
    {
        cfg.Host(builder.Configuration["RabbitMQ:Host"], "/", host =>
        {
            host.Username(builder.Configuration["RabbitMQ:Username"]);
            host.Password(builder.Configuration["RabbitMQ:Password"]);
        });

        cfg.ReceiveEndpoint("created-document", e =>
        {
            e.ConfigureConsumer<WfConsumer>(context);
        });
    });
});
builder.Services.AddMassTransitHostedService();
#endregion




#region Razor page defaults
builder.Services.AddRazorPages();
builder.Services.AddControllers();
builder.Services.AddControllers();
#endregion





#region Default app
var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MainDashboard.API v1"));
}
app.UseStaticFiles();
app.UseRouting();
app.UseCors();
app.UseHttpActivities();
app.UseHttpsRedirection();
app.UseAuthorization();
app.UseAuthentication();
app.MapControllers();
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapFallbackToPage("/_Host");
});

app.Run();
#endregion
````

````
warn: Rebus.Retry.ErrorTracking.InMemErrorTracker[0]
      Unhandled exception 5 while handling message with ID "a974514f-7ad2-46a2-a34a-29646b32d6d4"
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
fail: Rebus.Retry.PoisonQueues.PoisonQueueErrorHandler[0]
      Moving message with ID "a974514f-7ad2-46a2-a34a-29646b32d6d4" to error queue "error"
      System.AggregateException: 5 unhandled exceptions (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)<---

       ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)<---

       ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)<---

       ---> (Inner Exception #4) System.NullReferenceException: Object reference not set to an instance of an object.
         at Elsa.Activities.MassTransit.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\activities\Elsa.Activities.MassTransit\Bookmarks\MessageReceivedBookmark.cs:line 17
         at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\elsa-core\src\core\Elsa.Abstractions\Services\Bookmarks\BookmarkProvider.cs:line 50
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 87
         at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForActivityBlueprintAndWorkflowProvider.cs:line 53
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext() in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 60
      --- End of stack trace from previous location ---
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 65
         at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggersForBlueprintsProvider.cs:line 46
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 50
         at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken) in C:\Users\malfx001\Desktop\Workshop\LibraryPackage\wflow-core\src\core\Elsa.Core\Services\Triggers\TriggerIndexer.cs:line 40
         at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
         at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
         at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)<---

````

![resim_2022-01-01_220927](https://user-images.githubusercontent.com/87203103/147858275-40788620-2478-4ad2-9f29-d652261ae91b.png)

**Comment by pvanroos** [comment]
Was this fixed?

**Comment by sfmskywalker** [comment]
Looking at the history of this issue, it doesn't look that way. Unless a fix was pushed without this issue being updated, which happens from time to time. Please give it a try, and let me know if you get the same (or any other) issue.

**Comment by pvanroos** [comment]
Hi @sfmskywalker 

I'm sorry.  I fixed my issue and now my wf is triggering with a MT published message.  I like to kick off wfs with messaging.

**Comment by sfmskywalker** [comment]
No worries, I'm happy to hear it's working. Then I suppose we may just as well close this issue, what do you think?
