### ISSUE TITLE
Upgrade to 2.4.2.1 - YesSql & dependency issues Unable to resolve service for type 'Elsa.Services.IIdGenerator'

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#2708]
A missing dependency? 
I have added `services.AddSingleton<Elsa.Services.IIdGenerator, Elsa.Services.IdGenerator>();` to the startup and it seems to be fine after that. It looks like the issue is more likely fixed three days ago with the startup improvements though. 

```
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore': Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore'.) (Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore': Unable to resolve service for type 'Elsa.Services.
IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore'.) (Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowExecutionLogStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowExecutionLogStore': Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowExecutionLogStore'.) (Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql.Stores.YesSqlBookmarkStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlBookmarkStore': Unable to resolve service
for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlBookmarkStore'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore': Unable to resolve service f
or type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowDefinitionStore'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persi
stence.YesSql.Stores.YesSqlWorkflowDefinitionStore'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain call
SiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, T
ype implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, Call
SiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain call
SiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, Ser
viceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Unily.Management.UI.Program.Main(String[] args) in C:\Users\MGreen\source\repos\Unily Management\Unily Management\Unily.Management.UI\Prog
ram.cs:line 22
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql
.Stores.YesSqlWorkflowInstanceStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore': Unable to
resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowInstanceStore'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persi
stence.YesSql.Stores.YesSqlWorkflowInstanceStore'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain call
SiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, T
ype implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, Call
SiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain call
SiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---

 ---> (Inner Exception #2) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql
.Stores.YesSqlWorkflowExecutionLogStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlWorkflowExecutionLogStore': Un
able to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlWorkflowExecuti
onLogStore'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persi
stence.YesSql.Stores.YesSqlWorkflowExecutionLogStore'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain call
SiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, T
ype implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, Call
SiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain call
SiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---

 ---> (Inner Exception #3) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Persistence.YesSql
.Stores.YesSqlBookmarkStore Lifetime: Scoped ImplementationType: Elsa.Persistence.YesSql.Stores.YesSqlBookmarkStore': Unable to resolve service
for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persistence.YesSql.Stores.YesSqlBookmarkStore'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Services.IIdGenerator' while attempting to activate 'Elsa.Persi
stence.YesSql.Stores.YesSqlBookmarkStore'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain call
SiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, T
ype implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, Call
SiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain call
SiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   
   ```

**Comment by sfmskywalker** [comment]
Should be fixed, if not please do reopen!
