### ISSUE TITLE
Elsa 2.4.2.1 broken with MediatR 10.0

### ISSUE THREAD

**Issue by robymarcellino** [elsa-workflows/elsa-core#2720]
When a net5 assembly importing Elsa 2.4.2.1 already depends on MediatR 10.0, then the following code:

```
// Note: ScanWorkflow and ColorAdjustmentActivity are application-specific types.
public static class HostBuilderExtensions
{
  public static IHostBuilder ConfigureScanContext ( this IHostBuilder hostBuilder )
  {
    return hostBuilder.ConfigureServices ( services => services
      .AddElsa ( options => options
        .AddWorkflow<ScanWorkflow> ()
        .AddActivity<ColorAdjustmentActivity> () ) );
  }
}
```
raises exception
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'MediatR.INotification' from assembly 'MediatR, Version=10.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.
  Source=Elsa.Core
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ElsaServiceCollectionExtensions.AddWorkflowsCore(ElsaOptionsBuilder elsaOptions)
   at Microsoft.Extensions.DependencyInjection.ElsaServiceCollectionExtensions.AddElsaCore(IServiceCollection services, Action`1 configure)
```

I presume this is due because MediatR 10 has moved interface `MediatR.INotification` from assembly MediatR to assembly MediatR.Contracts.

**Comment by sfmskywalker** [comment]
Yeah exactly. We'll be upgrading soon.

**Comment by sfmskywalker** [comment]
I just pushed an update that upgrades to Mediatr 10.0.1.
