### ISSUE TITLE
MongoDb Persistence Provider Failing on 2.5.0

### ISSUE THREAD

**Issue by ejlevin1** [elsa-workflows/elsa-core#2735]
When following instructions [here](https://elsa-workflows.github.io/elsa-core/docs/installation/installing-persistence#mongodb), my server will startup but error out on the DI container trying to create the MongoDbTriggerStore.  It appears that the IMongoCollection items should be registered with the DI container, but currently aren't.  Stack trace:

```
[13:37:56 FTL] An unhandled exception occured.
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore Lifetime: Singleton ImplementationType: Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore': Unable to resolve service for type 'MongoDB.Driver.IMongoCollection`1[Elsa.Models.Trigger]' while attempting to activate 'Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore Lifetime: Singleton ImplementationType: Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore': Unable to resolve service for type 'MongoDB.Driver.IMongoCollection`1[Elsa.Models.Trigger]' while attempting to activate 'Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'MongoDB.Driver.IMongoCollection`1[Elsa.Models.Trigger]' while attempting to activate 'Elsa.Persistence.MongoDb.Stores.MongoDbTriggerStore'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

```

If I explicitly add those as singletons to the DI container, the ASP.NET core app starts up correctly, and I see the mongodb present within my mongo instance.  Note that I also had to manually register the Bson serialization types as well -- I was getting a deserialization error with NodaTime.Instant otherwise.  Seems as though there is something that should be getting called that isn't in the current startup flow.  Please let me know how I can help!

Original Code (startup.cs)
```
            services
                .AddElsa(
                    elsa => elsa
                        .UseMongoDbPersistence(options =>
                        {
                            options.ConnectionString = "mongodb://mongodb:27017/Elsa";
                        })
                        .AddConsoleActivities()
                        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                        .AddEmailActivities(elsaSection.GetSection("Smtp").Bind)
                        .AddConsoleActivities()
                        .AddUserTaskActivities()
                        .AddJavaScriptActivities()
                        .AddQuartzTemporalActivities()
                        .AddWorkflowsFrom<Startup>()
                        .AddActivitiesFrom<Startup>()
                    );
```

Working Code (startup.cs)
```
            var mongoContext = new ElsaMongoDbContext(new OptionsWrapper<ElsaMongoDbOptions>(new ElsaMongoDbOptions()
            {
                ConnectionString = "mongodb://mongodb:27017/Elsa"
            }));
            services.AddSingleton(mongoContext.Bookmarks);
            services.AddSingleton(mongoContext.Triggers);
            services.AddSingleton(mongoContext.WorkflowDefinitions);
            services.AddSingleton(mongoContext.WorkflowInstances);
            services.AddSingleton(mongoContext.WorkflowExecutionLog);

            BsonSerializer.RegisterSerializer(VariablesSerializer.Instance);
            BsonSerializer.RegisterSerializer(JObjectSerializer.Instance);
            BsonSerializer.RegisterSerializer(ObjectSerializer.Instance);
            BsonSerializer.RegisterSerializer(TypeSerializer.Instance);
            BsonSerializer.RegisterSerializer(new InstantSerializer());

            services
                .AddElsa(
                    elsa => elsa
                        .UseMongoDbPersistence(options =>
                        {
                            options.ConnectionString = "mongodb://mongodb:27017/Elsa";
                        })
                        .AddConsoleActivities()
                        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                        .AddEmailActivities(elsaSection.GetSection("Smtp").Bind)
                        .AddConsoleActivities()
                        .AddUserTaskActivities()
                        .AddJavaScriptActivities()
                        .AddQuartzTemporalActivities()
                        .AddWorkflowsFrom<Startup>()
                        .AddActivitiesFrom<Startup>()
                    );
```

**Comment by sfmskywalker** [comment]
Hi Eric, this issue was solved recently via [this PR](https://github.com/elsa-workflows/elsa-core/pull/2731) and just became available from MyGet. The fix will also be part of 2.5.1 on NuGet later this week.

To install the prerelease from MyGet, checkout [these instructions](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-feeds#myget).
