### ISSUE TITLE
2.6.0 YesSQL - Missing Mapping Type for Trigger -> TriggerDocument 

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#2906]
Requires something like: 
`CreateMap<Elsa.Models.Trigger, Elsa.Persistence.YesSql.Documents.TriggerDocument>()
            .ForMember(d => d.TriggerId, d => d.MapFrom(s=> s.Id))
            .ForMember(d => d.Id, d=> d.Ignore())
            .ReverseMap()
            .ForMember(d=> d.Id, d=> d.MapFrom(s=> s.TriggerId));`
in
https://github.com/elsa-workflows/elsa-core/blob/2ec915dabed9ffd03e9c9101e95a04f2438c1ed7/src/persistence/Elsa.Persistence.YesSql/Mapping/AutoMapperProfile.cs

```
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Trigger -> TriggerDocument
Elsa.Models.Trigger -> Elsa.Persistence.YesSql.Documents.TriggerDocument
   at lambda_method269(Closure , Trigger , TriggerDocument , ResolutionContext )
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.SaveAsync(T entity, CancellationToken cancellationToken)
   at Elsa.Persistence.YesSql.Stores.YesSqlStore`2.SaveAsync(T entity, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken)
   at Elsa.StartupTasks.IndexTriggers.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
```

**Comment by sfmskywalker** [comment]
@matt4446 Any chance I can get you to create a PR with this mapping? :)

**Comment by matt4446** [comment]
Possibly tomorrow

**Comment by sfmskywalker** [comment]
Fantastic - thank you!
