### ISSUE TITLE
Rebus RabbitMq on AWS amqps

### ISSUE THREAD

**Issue by vargaendre** [elsa-workflows/elsa-core#3033]
Hi,

I would like to ask a little help.

I am setting up multinode hosting in our devserver (plan to do it also in production later). I am trying to use Rebus with RabbitMq on AWS Amazon MQ but I am running into connectivity issues.

AWS provides an endpoint for RabbitMq with amqp**s** protocol. In the Elsa tutorial for Multinode hosting one can see the setting which contains only a querystring. If I set that querystring as an amqp**s** URI then I get the below error on startup:
`
Unhandled exception. Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler
---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
---> System.IO.IOException: connection.start was never received, likely due to a network timeout
`

All works well on my local machine with docker-compose and amqp protocol.

I found some information while googling this error and all seemed to suggest enabling SSL mode. I found options for that in Rebus code, but I don't know how I could do that in Elsa. 
Could you please help me with this issue?

**Comment by sfmskywalker** [comment]
You are probably using the `UseRabbitMq` extension method, which encapsulates direct access to the Rebus configurer lambda.
What you can do is use `UseServiceBus` directly, which gives you full access to Rebus' API. For example, from our startup/program:

```csharp
services.AddElsa(elsa => elsa.UseServiceBus(context => context.Configurer.Transport(t => t.UseRabbitMq(connectionString, context.QueueName).Ssl(new SslSettings(true, "some server name"))));
```

**Comment by vargaendre** [comment]
HI @sfmskywalker 
Thank you so much for the quick response! That's exactly what I was looking for, but I couldn't figure out the interfaces by myself.
I am now trying it out and will let you know how it goes.

**Comment by vargaendre** [comment]
Hi @sfmskywalker 
Unfortunately, it still does not work.
I get an error like below:
````
Unhandled exception. Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace --- 
(...)
````
The interesting part is `error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version`

I am trying to reach an AWS public RabbitMq via amqps from my localhost, wit a setup created with docker-compose.

**Comment by sfmskywalker** [comment]
Good to know, thanks for sharing!
