### ISSUE TITLE
TypeConverter cannot convert from Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by ethermine** [elsa-workflows/elsa-core#308]
Hi ! 

I've been having quite some trouble with the elsa-2.0 , I know it's currently under works , but I'd like some hint on where to look 🙏  .
I tried creating a simple http workflow (httpRequest and then httpResponse).
When i hit the : http://localhost:11000/hello , it trigger the start activity , but then it crashed when trying to parse the state definition from database I think.

Here's the error : 

> System.NotSupportedException: TypeConverter cannot convert from Newtonsoft.Json.Linq.JObject.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(Object value)
   at Elsa.Models.Variables.GetVariable[T](String name) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Abstractions\Models\Variables.cs:line 48
   at Elsa.Extensions.StateExtensions.GetState[T](Variables state, String key, Func`1 defaultValue) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Abstractions\Extensions\StateExtensions.cs:line 17
   at Elsa.Services.Activity.GetState[T](Func`1 defaultValue, String name) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Abstractions\Services\Activity.cs:line 36
   at Elsa.Activities.Console.WriteDebug.get_Text() in C:\Users\admin\source\repos\elsa-core\src\activities\Elsa.Activities.Console\Activities\WriteDebug\WriteDebug.cs:line 35
   at Elsa.Activities.Console.WriteDebug.OnExecuteAsync(ActivityExecutionContext context, CancellationToken cancellationToken) in C:\Users\admin\source\repos\elsa-core\src\activities\Elsa.Activities.Console\Activities\WriteDebug\WriteDebug.cs:line 55
   at Elsa.Services.WorkflowHost.RunAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Core\Services\WorkflowHost.cs:line 178
   at Elsa.Services.WorkflowHost.BeginWorkflow(WorkflowExecutionContext workflowExecutionContext, IActivity activity, Object input, CancellationToken cancellationToken) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Core\Services\WorkflowHost.cs:line 143
   at Elsa.Services.WorkflowHost.RunAsync(Workflow workflow, WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Core\Services\WorkflowHost.cs:line 97
   at Elsa.Services.WorkflowHost.RunWorkflowAsync(Workflow workflow, String activityId, Object input, String correlationId, CancellationToken cancellationToken) in C:\Users\admin\source\repos\elsa-core\src\core\Elsa.Core\Services\WorkflowHost.cs:line 86
   at Elsa.Activities.Http.RequestHandlers.Handlers.TriggerRequestHandler.InvokeWorkflowsToStartAsync(IEnumerable`1 items) in C:\Users\admin\source\repos\elsa-core\src\activities\Elsa.Activities.Http\RequestHandlers\Handlers\TriggerRequestHandler.cs:line 83
   at Elsa.Activities.Http.RequestHandlers.Handlers.TriggerRequestHandler.HandleRequestAsync() in C:\Users\admin\source\repos\elsa-core\src\activities\Elsa.Activities.Http\RequestHandlers\Handlers\TriggerRequestHandler.cs:line 51
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler) in C:\Users\admin\source\repos\elsa-core\src\activities\Elsa.Activities.Http\Middleware\RequestHandlerMiddleware.cs:line 18
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

And here's the state json from the database of the WriteReponse actity : 

> {"Content":{"Value":{"Expression":"Hello , World !","Type":"Literal"}}}

Again , I'd really apreciate any help ! Thanks !  😅

**Comment by ethermine** [comment]
To add some details , when I run the sample `Elsa.Samples.HelloWorldHttp` everythings works.
But when I used a workflow stored in database I got the `TypeConverter` error ..
The httpRequest  activity works fine , but I thinks somethings when evaluating the expression it does not like what cames from the database

**Comment by sfmskywalker** [comment]
H @ethermine , indeed there are many issues with the current stat of Elsa 2.0. But I'm fixing them.

**Comment by ethermine** [comment]
Hi ! Yeah no worries , I wasn't sure if it I was doing something wrong or not 👍
