### ISSUE TITLE
Docker command fails with Unhandled exception. System.IO.IOException on mac, M1.

### ISSUE THREAD

**Issue by jkind** [elsa-workflows/elsa-core#3114]
If I try to run the docker command I get a File.IO exception when running on Mac, M1.
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -e ASPNETCORE_ENVIRONMENT='Development' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest

`Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ElsaDashboard.Samples.AspNetCore.Monolith.Program.Main(String[] args) in /source/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/Program.cs:line 10
qemu: uncaught target signal 6 (Aborted) - core dumped`

**Comment by jdevillard** [comment]
Seems that not everything seems to be implemented on Mac https://github.com/dotnet/aspnetcore/issues/38876.
Have you try to disable the reload configuration on change as explain in the issue ?
