### ISSUE TITLE
Could not load type 'Elsa.Metadata.ActivityDescriptor' 

### ISSUE THREAD

**Issue by gayancc** [elsa-workflows/elsa-core#3119]
Can someone help me with this issue? 

```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load type 'Elsa.Metadata.ActivityDescriptor' from assembly 'Elsa.Core, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Services.Models.IActivity' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Elsa.Models.WorkflowDefinitionVersion' from assembly 'Elsa.Abstractions, Version=2.8.2.0, Culture=neutral, PublicKeyToken=null'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Harmony.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddAppMvc(IServiceCollection services)
```

![image](https://user-images.githubusercontent.com/399961/172668443-c95e4440-1eb0-4088-b19f-d8b394d2715a.png)

**Comment by gayancc** [comment]
Actually, issue is with `Elsa.Dashboard`  package when I removed that worked. any reasonÉ
