### ISSUE TITLE
ReadTimeOut Newtonsoft deserializer

### ISSUE THREAD

**Issue by reiven93** [elsa-workflows/elsa-core#3126]
Hi, I'm just doing a tutorial to try Elsa features. I have a custom activity that zips a filestream. Then, I want to return that stream as HttpResponse as the tutorial says to download it, but I got this error

`Newtonsoft.Json.JsonSerializationException: Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'.
 ---> System.InvalidOperationException: Timeouts are not supported on this stream.
   at System.IO.Stream.get_ReadTimeout()
   at lambda_method653(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
`

My activity is like this:
![image](https://user-images.githubusercontent.com/46783038/173417972-7951ecba-718e-424b-b431-34791427121c.png)
And the HttpResponse in the workflow is:
![image](https://user-images.githubusercontent.com/46783038/173418148-cc134789-ef76-44d9-9459-a4e03a4e7855.png)
With custom headers:
![image](https://user-images.githubusercontent.com/46783038/173418267-801ed0ab-3b93-498f-a94e-877c8774b1f1.png)

**Comment by reiven93** [comment]
Resolved changing content storage
![image](https://user-images.githubusercontent.com/46783038/173574493-67142156-ff6c-44a4-8301-791a30182e89.png)
