### ISSUE TITLE
Evaluating ELSA. Encountered exception when run dotnet ElsaQuickstarts.Server.Dashboard.dll

### ISSUE THREAD

**Issue by PeterHuang-ST** [elsa-workflows/elsa-core#3205]
I am currently evaluating ELSA workflow. One of the items I'm evaluating is the dashboard. I followed the instruction in the  dashboard quickstart 

https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard

When I run dotnet ElsaQuickstarts.Server.Dashboard.dll and attempt to access the server using Chrome with the address https://localhost:5001 or https://localhost:5001/_Host. Its encountering the following exceptions in bold below.  I build with VS-2022 profession and  I use .net 5 as the examples are in .net 5 format.  

However when I debug this directly on Visual studio 2022 itself, I'm able to access the page when I use https://localhost:57035/_Host. But of course we would need to be able to run the server directly on a command prompt. This also failed when I run donet ElsaQuickstarts.Server.Dashboard.dll  on powershell as well.  Please advise on this issue. 

PS C:\Users\phuang\PersonalTest\ElsaQuickstarts.Server.Dashboard\bin\Debug\net5.0> dotnet ElsaQuickstarts.Server.Dashboard.dll
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\phuang\PersonalTest\ElsaQuickstarts.Server.Dashboard\bin\Debug\net5.0
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      **Connection id "0HMJ6IATK8HA5", Request id "0HMJ6IATK8HA5:00000001": An unhandled exception was thrown by the application.
      Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

      /Index
      /_Host
      /_Host**
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by sfmskywalker** [comment]
Looks like the quickstart sample may be outdated. I'll take a look.

**Comment by sfmskywalker** [comment]
Strangely enough I'm not getting any issues when I try and setup the dashboard.  It looks like there may be a folder name on your system called `_Host` that causes the endpoint ambiguity.
