### ISSUE TITLE
SQL Command Activity failing in 2.9

### ISSUE THREAD

**Issue by taurisjoe** [elsa-workflows/elsa-core#3364]
Hi Guys,

First off, thanks for building a wonderful workflow tool.  Elsa has a ton of potential with what I'm working on.  

I've generally been working with 2.8.2 over the last month and built a few ETL style workflows,  In doing so I've leveraged the SQL Command activity.  After upgrading to 2.9.0 earlier this week, one of my SQL centric workflows started failing and the stack trace is below.  I tested reverting back to 2.8.2 and the below issue goes away.  I also tried deleting and recreating the SQL Command activity in that workflow in case some changes were made in the activity itself to no avail.  

2.9.1 is available on nuget and it has the same issue.  

Let me know if you need any more information.  

```
warn: Elsa.Services.Workflows.WorkflowRunner[0]
      Failed to run activity 7f97cb6d-ff2d-4e73-9cdb-e8d79ddbe256 of workflow 5c05d82293e44d53a470342dd1330049
      System.ArgumentException: Unsupported database type: MSSQL Server
         at Elsa.Activities.Sql.Factory.SqlClientFactory.CreateClient(CreateSqlClientModel createSqlClient)
         at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.ExecuteCommand()
         at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.OnExecute(ActivityExecutionContext context)
         at Elsa.Services.Activity.OnExecuteAsync(ActivityExecutionContext context)
         at Elsa.Services.Activity.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Services.Workflows.WorkflowRunner.<>c.<.cctor>b__19_0(ActivityExecutionContext context, IActivity activity)
         at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken)
Elsa.Services.Workflows.WorkflowRunner: Warning: Failed to run activity 7f97cb6d-ff2d-4e73-9cdb-e8d79ddbe256 of workflow 5c05d82293e44d53a470342dd1330049

System.ArgumentException: Unsupported database type: MSSQL Server
   at Elsa.Activities.Sql.Factory.SqlClientFactory.CreateClient(CreateSqlClientModel createSqlClient)
   at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.ExecuteCommand()
   at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.OnExecute(ActivityExecutionContext context)
   at Elsa.Services.Activity.OnExecuteAsync(ActivityExecutionContext context)
   at Elsa.Services.Activity.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Services.Workflows.WorkflowRunner.<>c.<.cctor>b__19_0(ActivityExecutionContext context, IActivity activity)
   at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken)
warn: Elsa.Handlers.LogWorkflowExecution[0]
      An error occurred while executing activity 7f97cb6d-ff2d-4e73-9cdb-e8d79ddbe256. Entering Faulted state
      System.ArgumentException: Unsupported database type: MSSQL Server
         at Elsa.Activities.Sql.Factory.SqlClientFactory.CreateClient(CreateSqlClientModel createSqlClient)
         at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.ExecuteCommand()
         at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.OnExecute(ActivityExecutionContext context)
         at Elsa.Services.Activity.OnExecuteAsync(ActivityExecutionContext context)
         at Elsa.Services.Activity.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Services.Workflows.WorkflowRunner.<>c.<.cctor>b__19_0(ActivityExecutionContext context, IActivity activity)
         at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken)
Elsa.Handlers.LogWorkflowExecution: Warning: An error occurred while executing activity 7f97cb6d-ff2d-4e73-9cdb-e8d79ddbe256. Entering Faulted state

System.ArgumentException: Unsupported database type: MSSQL Server
   at Elsa.Activities.Sql.Factory.SqlClientFactory.CreateClient(CreateSqlClientModel createSqlClient)
   at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.ExecuteCommand()
   at Elsa.Activities.Sql.Activities.ExecuteSqlCommand.OnExecute(ActivityExecutionContext context)
   at Elsa.Services.Activity.OnExecuteAsync(ActivityExecutionContext context)
   at Elsa.Services.Activity.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Services.Workflows.WorkflowRunner.<>c.<.cctor>b__19_0(ActivityExecutionContext context, IActivity activity)
   at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken)
info: Elsa.Services.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks for workflow instance 5c05d82293e44d53a470342dd1330049
Elsa.Services.Bookmarks.BookmarkIndexer: Information: Indexing bookmarks for workflow instance 5c05d82293e44d53a470342dd1330049
info: Elsa.Services.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks for workflow instance 5c05d82293e44d53a470342dd1330049 in 00:00:00.0996551
Elsa.Services.Bookmarks.BookmarkIndexer: Information: Indexed 0 bookmarks for workflow instance 5c05d82293e44d53a470342dd1330049 in 00:00:00.0996551
```

**Comment by BenSeymourODB** [comment]
@sfmskywalker thanks for addressing this: we had just started trying to use the new SQL activities, and were running into this issue.
