### ISSUE TITLE
Elsa 2.8.2 and 2.9.1 are incompatible with AutoMapper 12.0.0 and this is only visible at runtime!

### ISSUE THREAD

**Issue by Bergam64** [elsa-workflows/elsa-core#3369]
Hello Elsa Team!

I've recently upgraded the following NuGet packages in all my projects, including in those using `Elsa` (initially 2.8.2):
- `AutoMapper` 11.0.1 => 12.0.0
- `AutoMapper.Extensions.EnumMapping` 2.0.1 => 3.0.1
- `AutoMapper.Extensions.Microsoft.DependencyInjection` 11.0.0 => 12.0.0

I was able to rebuilt all my solutions without any issue, and no issue was visible at runtime in my own code.

Launching my Elsa server and executing a few workflows didn't report any issue, but finally I realized that **I couldn't open a workflow instance anymore** and the following **error stack** was visible in the debugger each time I tried:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.Object> AutoMapper.IMappingOperationOptions.get_Items()'.
   at Elsa.Server.Api.Services.WorkflowBlueprintMapper.<>c__DisplayClass5_0.<MapAsync>b__4(IMappingOperationOptions`2 options)
   at AutoMapper.Mapper.MapWithOptions[TSource,TDestination](TSource source, TDestination destination, Action`1 opts, Type sourceType, Type destinationType)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination, Action`1 opts)
   at AutoMapper.Mapper.Map[TDestination](Object source, Action`1 opts)
   at Elsa.Server.Api.Services.WorkflowBlueprintMapper.MapAsync(IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Server.Api.Endpoints.WorkflowRegistry.Get.Handle(String id, Nullable`1 versionOptions, CancellationToken cancellationToken)
   at lambda_method1042(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.HandleNoWorkflowsFoundAsync(HttpContext httpContext, IList`1 pendingWorkflows, Nullable`1 basePath)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IOptions`1 options, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IRouteMatcher routeMatcher, ITenantAccessor tenantAccessor, IEnumerable`1 contentParsers)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Notes:
- This morning, I've upgraded to latest Elsa (**2.9.1**), hoping that it would solve the incompatibility issue, but **it didn't**.
- All my projects are targeting .NET 6.
- In case this is relevant, all my workflows are built by code (not with the designer).
- As a **temp workaround**, I've downgraded `AutoMapper` back to 11.0.1, `AutoMapper.Extensions.EnumMapping` back to 2.0.1 and `AutoMapper.Extensions.Microsoft.DependencyInjection`back to 11.0.0, and this has fixed the issue for now.

Can you please investigate and fix this, so that more recent versions of `AutoMapper` can finally be used?

Thanks in advance.

**Comment by Nico-VanHaaster** [comment]
We have had very similar issue and ending up having to add custom mapping profiles. The only issue we have found in compatability was Automapper changed a property from `IDictionary<string, object>` to `Dictionary<string,object>` however when upgrading Elsa to v12.0.0 had no issues.

Our workaround (although not pretty) was to create new Mappers for the `IWorkflowBlueprintMapper` and `ActivityBlueprintConverter` using the same code (copy and pasted with no changes) and overriding some of the services after the `AddElsa` statements such as.

```
services.AddScoped<IWorkflowBlueprintMapper, ElsaWorkflowBlueprintMapper>();

services.TryRemoveServiceOfType<ActivityBlueprintConverter>() //note custom call.
    .AddSingleton<ElsaActivityBlueprintConverter>()
    .AddSingleton<ActivityBlueprintConverter>(sp => sp.GetRequiredService<ElsaActivityBlueprintConverter>());
```

The mappers do nothing different from the current Elsa mappers.
