### ISSUE TITLE
Error "relation "elsa.triggers" does not exist" when DeleteManyAsync Version Elsa 2.9.1  

### ISSUE THREAD

**Issue by tchivs** [elsa-workflows/elsa-core#3383]
The database is using Npgsql，Error when running after upgrading to the latest version

Error details are as follows：
```

Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "elsa.triggers" does not exist
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.<>c__DisplayClass11_0.<<DeleteManyAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DeleteManyAsync(ISpecification`1 specification, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.DeleteTriggersAsync(String workflowDefinitionId, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken)
   at Elsa.StartupTasks.IndexTriggers.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at CommandCenter.ServicesHost.Program.Main(String[] args) in D:\SourceCode\incident-dispatch-service\IncidentDispatchService\Code\CommandCenter.WebServicesHost\Program.cs:line 108
   at CommandCenter.ServicesHost.Program.<Main>(String[] args)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "elsa.triggers" does not exist
    Position: 13
    File: parse_relation.c
    Line: 1159
    Routine: parserOpenTable
```

find after locating The generated SQL is incorrect
```sql
DELETE FROM Elsa.Triggers WHERE "WorkflowDefinitionId" = $1
```
postgres is case sensitive ,so The correct statement should be
```sql
DELETE FROM "Elsa"."Triggers" WHERE "WorkflowDefinitionId" = $1
```

locate [`EntityFrameworkStore.cs` ](https://github.com/elsa-workflows/elsa-core/blob/0eb9014e16fd5a46549b84a993f63b9e1147c121/src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Stores/EntityFrameworkStore.cs#L143)

![image](https://user-images.githubusercontent.com/20809329/197986096-7a03e5fb-0353-4f7b-ae3d-99fa3f17b9a7.png)

The following points should also be modified

![image](https://user-images.githubusercontent.com/20809329/197986299-4471b793-5250-4825-b410-e317b0d51a9e.png)

**Comment by tchivs** [comment]
Need to rewrite a GetSchemaQualifiedTableName myself, add quotes to the table name, but I can't submit a PR at work now
