### ISSUE TITLE
SendHttpRequest does not work

### ISSUE THREAD

**Issue by andyevans2000** [elsa-workflows/elsa-core#345]
When a SendHttpRequest activity is run it throws an exception (created using the designer)

Newtonsoft.Json.JsonSerializationException: Error converting value "text/html" to type 'Elsa.Expressions.WorkflowExpression`1[System.String]'. Path 'contentType'.
 ---> System.ArgumentException: Could not cast or convert from System.String to Elsa.Expressions.WorkflowExpression`1[System.String].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Elsa.Extensions.StateExtensions.GetState[T](JObject state, String key, Func`1 defaultValue)
   at Elsa.Services.ActivityBase.GetState[T](Func`1 defaultValue, String name)
   at Elsa.Activities.Http.Activities.SendHttpRequest.get_ContentType()
   at Elsa.Activities.Http.Activities.SendHttpRequest.CreateRequestAsync(WorkflowExecutionContext workflowContext, CancellationToken cancellationToken)
   at Elsa.Activities.Http.Activities.SendHttpRequest.OnExecuteAsync(WorkflowExecutionContext workflowContext, CancellationToken cancellationToken)
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)

**Comment by futureneo86** [comment]
Hi sfmskywalker , did you fix this bug? I need to use SendHttpRequest to post an action after receive request
