### ISSUE TITLE
Designer method setOutcomes causes exception

### ISSUE THREAD

**Issue by AdamJohnSwan** [elsa-workflows/elsa-core#3555]
Using the `setOutcomes` method in a javascript input will cause an `InvalidCastException`

I put together a test workflow definition to show what I mean.
[set-outcomes-fail.txt](https://github.com/elsa-workflows/elsa-core/files/10271835/set-outcomes-fail.txt) (change to `.json` since Github only allows uploading txt files)

To test it run the `src\samples\dashboard\aspnetcore\ElsaDashboard.Samples.AspNetCore.Monolith` project, import the workflow definition above, and then publish it.

Then hit the endpoint to trigger the workflow

```
curl --request GET \
  --url https://localhost:15265/workflows/start
```

You will get this exception:

```
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Jint.Runtime.Interop.DefaultTypeConverter.Convert(Object value, Type type, IFormatProvider formatProvider)
   at Jint.Runtime.Interop.DelegateWrapper.Call(JsValue thisObject, JsValue[] jsArguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Engine.<>c__DisplayClass65_0.<Execute>g__DoInvoke|0()
   at Jint.Engine.ExecuteWithConstraints[T](Func`1 callback)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Evaluate(String source)
   at Elsa.Scripting.JavaScript.Services.JintJavaScriptEvaluator.ExecuteExpressionAndGetResult(Engine engine, String expression) in C:\\Users\\user\\sources\\elsa-core\\src\\scripting\\Elsa.Scripting.JavaScript\\Services\\JintJavaScriptEvaluator.cs:line 67
   at Elsa.Scripting.JavaScript.Services.JintJavaScriptEvaluator.EvaluateAsync(String expression, Type returnType, ActivityExecutionContext context, Action`1 configureEngine, CancellationToken cancellationToken) in C:\\Users\\user\\sources\\elsa-core\\src\\scripting\\Elsa.Scripting.JavaScript\\Services\\JintJavaScriptEvaluator.cs:line 41
   at Elsa.Activities.JavaScript.RunJavaScript.OnExecuteAsync(ActivityExecutionContext context) in C:\\Users\\user\\sources\\elsa-core\\src\\scripting\\Elsa.Scripting.JavaScript\\Activities\\RunJavaScript\\RunJavaScript.cs:line 69
   at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken) in C:\\Users\\user\\sources\\elsa-core\\src\\core\\Elsa.Core\\Services\\Workflows\\WorkflowRunner.cs:line 384
```

**Comment by AdamJohnSwan** [comment]
PR with fix got merged so I am closing this issue.
