### ISSUE TITLE
Request failed with status code 500 when running the designer  

### ISSUE THREAD

**Issue by Kawthar-Ebrahim** [elsa-workflows/elsa-core#3688]
I am using the last release of Elsa within my ASP.NET6 project, and I am facing the below when trying to access the dashboard (designers) tabs.
![image](https://user-images.githubusercontent.com/54577484/217514614-a0d609be-d5fe-4e91-8f32-e53833131da7.png)

**Comment by Sverre-W** [comment]
Could you also provide the logs from the Elsa server? Without the logs from the server it's rather hard to know what the problem is.

**Comment by steverb38** [comment]
Could be related:
After updating from Elsa 2.9.3 to 2.10.1, this is the exception I got when going to the workflow-definition page (using MongoDB for persistence):

```
An unhandled exception has occurred while executing the request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Elsa.Persistence.MongoDb.Serializers.ObjectSerializer' to type 'MongoDB.Bson.Serialization.Serializers.ObjectSerializer'.
   at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor(IDiscriminatorConvention discriminatorConvention, IBsonSerializer`1 interfaceSerializer)
   at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor(IDiscriminatorConvention discriminatorConvention)
   at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at MongoDB.Bson.Serialization.BsonSerializationProviderBase.CreateSerializer(Type serializerType, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Bson.Serialization.BsonSerializationProviderBase.CreateGenericSerializer(Type serializerTypeDefinition, Type[] typeArguments, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Bson.Serialization.DiscriminatedInterfaceSerializationProvider.GetSerializer(Type type, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Bson.Serialization.BsonSerializerRegistry.CreateSerializer(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.LookupSerializer(Expression expression, Type type)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.GetSerializer(Expression expression, Type type, IBsonSerializer defaultSerializer)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMember(MemberExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.FindKnownSerializers(Expression root, IBsonDocumentSerializer rootSerializer)
   at MongoDB.Driver.Linq.Linq3Implementation.Translators.TranslationContext.Create(Expression expression, IBsonSerializer serializer, TranslationContextData data)
   at MongoDB.Driver.Linq.Linq3Implementation.Translators.ExpressionToExecutableQueryTranslators.ExpressionToExecutableQueryTranslator.TranslateScalar[TDocument,TResult](MongoQueryProvider`1 provider, Expression expression)
   at MongoDB.Driver.Linq.Linq3Implementation.MongoQueryProvider`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at MongoDB.Driver.Linq.MongoQueryable.CountAsync[TSource](IMongoQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.Persistence.MongoDb.Stores.MongoDbStore`1.CountAsync(ISpecification`1 specification, CancellationToken cancellationToken)
   at Elsa.Server.Api.Endpoints.WorkflowDefinitions.List.Handle(String ids, String searchTerm, Nullable`1 page, Nullable`1 pageSize, Nullable`1 version, CancellationToken cancellationToken)
   at lambda_method305(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.HandleNoWorkflowsFoundAsync(HttpContext httpContext, IList`1 pendingWorkflows, Nullable`1 basePath)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IOptions`1 options, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IRouteMatcher routeMatcher, ITenantAccessor tenantAccessor, IEnumerable`1 contentParsers)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by brunomartinspro** [comment]
Hey!

I managed to reproduce this by having a higher version of MongoDB.Driver than the version 2.13.1.
Do you also have this package installed in a higher / lower version?

**Comment by steverb38** [comment]
Hi @brunomartinspro,

Thanks for the reply.

Our root project references Elsa.Persistence.MongoDb and so MongoDB.Driver (and that references MongoDB.Bson). But the root project also references other projects which use MongoDB.Driver. All projects are using the same versions of the Nuget packages.

I'm not sure I can remove any of the packages!

Steve.

**Comment by Juandavi1** [comment]
Hi ! 

I have already removed the Mongo Driver dependency but the issue persist :(

**Comment by steverb38** [comment]
Just tried with the 2.11 Elsa packages, and the problem is still there as I reported on 9th Feb.

**Comment by Slettan** [comment]
Same problem here.

I was able to solve it by downgrading to version 2.17.1 of `MongoDB.Driver`, but this "workaround" doe not work with Elsa 2.11 because `Elsa.Persistence.MongoDb` depends on version 2.19.0.
