### ISSUE TITLE
Watch Directory fires casting exception when retrying after error

### ISSUE THREAD

**Issue by williamverdolini** [elsa-workflows/elsa-core#3744]
Repro steps:
1. create a simple workflow like the this
    1. Watch-Directory (every trigger is good, eg on file created)
    2. Wait fo 20 secs
    3. Finish
2. run the workflow
3. stop the process during the "Wait" step

When the service starts again, we'll receive the following exception

![image](https://user-images.githubusercontent.com/6443266/221924804-17a27fe1-6cce-492e-900f-7962e284ce76.png)

Checking the code I thin the problem is here:

![image](https://user-images.githubusercontent.com/6443266/221925853-45fe67ba-4eb0-4563-8ded-e4cbc3776459.png)

probably it should be better with this:

![image](https://user-images.githubusercontent.com/6443266/221926078-7ba2501f-9600-4afb-ab32-93b675d64b1a.png)

If the fix is correct, I could open a quick PR.

**Comment by sfmskywalker** [comment]
That's likely the correct fix, presuming that `GetInput<FileSystemEvent>` will properly parse the JObject into a FileSystemEvent. Since it's broken now already, it's worth a try 👍🏻

**Comment by williamverdolini** [comment]
@sfmskywalker  I've opened the PR. 
The issue seems to affect only MongoDB. Tried on sqllite and it works because the FileSystemEvent type is persisted on $type field, while in MongoDB the input is a string.

SQL:
```
"WatchAndWaitWorkflow": {
      "$id": "6",
      "Input": {
        "$id": "7",
        "$type": "Elsa.Activities.File.Models.FileSystemEvent, Elsa.Activities.File",
        "changeType": 1,
        "directory": "X:\\xxxxx\\Elsa",
        "fileName": "try.txt",
        "fullPath": "X:\\xxxxx\\Elsa\\try.txt",
        "timeStamp": "2023-03-12T17:30:25.5117376+01:00"
      }
    }
```
MongoDb:
```
"ActivityData" : {
        "443da830e70947c98c9644ab331f24ab" : {
            "Input" : "{\"ChangeType\":1,\"Directory\":\"X:\\\\xxxx\",\"FileName\":\"leancost.json\",\"FullPath\":\"X:\\\\xxxx\\\\try.txt\",\"TimeStamp\":\"2023-03-12T17:59:22.7499959+01:00\"}"
        },
        "8ebcca60-d181-43e0-b763-785dfb5046d3" : {
            "Path" : "\"X:\\\\xxxx\"",
            "Pattern" : "\"*\"",
            "ChangeTypes" : "1",
            "NotifyFilters" : "1",
            "Output" : "null"
        }
    }
```

I've reproduced it and checked.

Only one note, during the check, I've build and run the dashboard with mongoDb persistance, but when I try to see definitions or instances I've got this error:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.InvalidCastException: Unable to cast object of type 'Elsa.Persistence.MongoDb.Serializers.ObjectSerializer' to type 'MongoDB.Bson.Serialization.Serializers.ObjectSerializer'.
         at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor(IDiscriminatorConvention discriminatorConvention, IBsonSerializer`1 interfaceSerializer)
         at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor(IDiscriminatorConvention discriminatorConvention)
         at MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer`1..ctor()
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
         at MongoDB.Bson.Serialization.BsonSerializationProviderBase.CreateSerializer(Type serializerType, IBsonSerializerRegistry serializerRegistry)
         at MongoDB.Bson.Serialization.BsonSerializationProviderBase.CreateGenericSerializer(Type serializerTypeDefinition, Type[] typeArguments, IBsonSerializerRegistry serializerRegistry)
         at MongoDB.Bson.Serialization.DiscriminatedInterfaceSerializationProvider.GetSerializer(Type type, IBsonSerializerRegistry serializerRegistry)
         at MongoDB.Bson.Serialization.BsonSerializerRegistry.CreateSerializer(Type type)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at MongoDB.Bson.Serialization.BsonSerializerRegistry.GetSerializer(Type type)
         at MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer(Type type)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.LookupSerializer(Expression expression, Type type)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.GetSerializer(Expression expression, Type type, IBsonSerializer defaultSerializer)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.GetSerializer(Expression expression, IBsonSerializer defaultSerializer)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMember(MemberExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
         at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMethodCall(MethodCallExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
         at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMethodCall(MethodCallExpression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
         at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.FindKnownSerializers(Expression root, IBsonDocumentSerializer rootSerializer)
         at MongoDB.Driver.Linq.Linq3Implementation.Translators.TranslationContext.Create(Expression expression, IBsonSerializer serializer, TranslationContextData data)
         at MongoDB.Driver.Linq.Linq3Implementation.Translators.ExpressionToExecutableQueryTranslators.ExpressionToExecutableQueryTranslator.TranslateScalar[TDocument,TResult](MongoQueryProvider`1 provider, Expression expression)
         at MongoDB.Driver.Linq.Linq3Implementation.MongoQueryProvider`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at MongoDB.Driver.Linq.MongoQueryable.CountAsync[TSource](IMongoQueryable`1 source, CancellationToken cancellationToken)
         at Elsa.Persistence.MongoDb.Stores.MongoDbStore`1.CountAsync(ISpecification`1 specification, CancellationToken cancellationToken)
         at Elsa.Server.Api.Endpoints.WorkflowDefinitions.List.Handle(String ids, String searchTerm, Nullable`1 orderBy, Nullable`1 sortBy, Nullable`1 page, Nullable`1 pageSize, Nullable`1 version, CancellationToken cancellationToken) in C:\dev\github\forked-elsa-core\elsa-core\src\server\Elsa.Server.Api\Endpoints\WorkflowDefinitions\List.cs:line 77
```

I couldn't figure out if it's a problem of my quick test setup....if you think it's not, I'll investigate on it

**Comment by sfmskywalker** [comment]
It might be an issue with the Elsa persistence implementation with MongoDB.
