### ISSUE TITLE
Incompatibility with net6 project + EFCore 7

### ISSUE THREAD

**Issue by montoner0** [elsa-workflows/elsa-core#3784]
I wonder why packages for EF7 are bound to net7 in Elsa since [its quite legit to use EF7 with net6](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew). With the configuration net6+EF7, Elsa throws a MethodNotFound exception when trying to apply migrations.

```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder`1<Microsoft.EntityFrameworkCore.Migrations.Operations.CreateIndexOperation> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateIndex(System.String, System.String, System.String, System.String, Boolean, System.String)'.
   at Elsa.Persistence.EntityFramework.SqlServer.Migrations.Initial.Up(MigrationBuilder migrationBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.StartupTasks.RunMigrations.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.StartupTasks.RunMigrations.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
```

**Comment by mohdali** [comment]
@montoner0 can you try adding explicit reference to `Microsoft.EntityFrameworkCore.Relational` version 7.0.0?

Before adding support to .NET 7, we had a dependency on `EFCore.BulkExtensions` which brought unwanted dependencies as a side effect. While adding support for .NET 7 we removed that dependency. However, it is still there for .NET 6 and below to avoid any sudden breaking changes.

Please check if this approach would work for you.

`<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.0" />`

**Comment by montoner0** [comment]
Unfortunately it didn't help. Still throws the same exception.

**Comment by mohdali** [comment]
@montoner0 I'm still trying to figure out why migrations don't work.

However, if I run the migrations under .NET 7 I'm able to run the persistence sample after explicitly defining below packages under .NET 6.

Can you check if that helps? I will try to find why migrations don't work in the meanwhile.

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
      <PackageReference Include="System.Text.Encodings.Web" Version="7.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.3" />
      <PackageReference Include="EFCore.BulkExtensions" Version="7.0.1" />
</ItemGroup>
```

**Comment by mohdali** [comment]
> I've tried to add the packages to both main and dbcontext projects but no luck. And I don't quite sure how it could help since the Elsa.Persistence.* assemblies are referencing efcore 6 assemblies.

Elsa.Persistence.* packages refer EF Core 6 as min version. However, if you explicitly specify EF Core 7 in your project, they are supposed to use it.

The problem is EF Core 7 introduced some changes to the `CreateIndex` method signature by introducing a new optional parameter which causes the `MissingMethodException`. So a pacakge compiled while targeting EF 6 will get the exception during runtime. The only solution is to recompile with EF 7 instead.

But that will force anyone on .NET 6 to upgrade to EF7 which may not be desirable.

It is easier to keep EF and .NET major versions in sync for the global usage I think.

In your case, you may be able to use EF Core 7 with .NET 6 if you run the migrations manually (from dotnet tools or create the database from a .NET 7 app). Assuming no other compatability issues arise during runtime.

**Comment by montoner0** [comment]
I'd rather avoid use of EF and NET in sync since net6 is LTS and net7 is not. 

Probably, it could be nice to extract the migrations into a separate package, so people could use the one they need or even allow devs to include the migrations inside their own app as it's done in https://github.com/appany/AppAny.Quartz.EntityFrameworkCore.Migrations.

**Comment by sfmskywalker** [comment]
I like it, I think we should do it. @mohdali is gonna give it a go. Thanks for the suggestions!
