### ISSUE TITLE
Passing dictionaries (Variables) as JavaScriptExpression

### ISSUE THREAD

**Issue by gztamas** [elsa-workflows/elsa-core#382]
Hi,

I am unable to express Variables instances (for example for passing inputs to a "child" workflow). According to your siggestion in Gitter, {"foo": "bar"} should work, but it does not. Apparently it's unhappy with the `:` token, but I'm not sure how I could json without `:` :).
Here's some code that's reproducing the issue, for your viewing pleasure.

```c#
using System;
using System.Threading.Tasks;
using Elsa.Activities.Console.Activities;
using Elsa.Activities.Console.Extensions;
using Elsa.Activities.Workflows.Activities;
using Elsa.Expressions;
using Elsa.Extensions;
using Elsa.Models;
using Elsa.Scripting.JavaScript;
using Elsa.Services;
using Elsa.Services.Models;
using MediatR;
using Microsoft.Extensions.DependencyInjection;

namespace ElsaSample
{
    internal static class Program
    {
        private static async Task Main()
        {
            var services = BuildServices();

            var evaluator = services.GetRequiredService<IWorkflowExpressionEvaluator>();
            var invoker = services.GetRequiredService<IWorkflowInvoker>();

            var context = await invoker.StartAsync<SomeWorkflow>();
            var expression = new JavaScriptExpression<Variables>("{\"foo\":\"bar\"}");
            
            var result = await evaluator.EvaluateAsync(expression, context, default);
            Console.WriteLine(result.GetVariable<string>("foo"));
        }

        private static IServiceProvider BuildServices()
        {
            return new ServiceCollection()
                .AddElsa()
                .AddConsoleActivities()
                .AddSingleton(Console.In)
                .AddMediatR(typeof(Program))
                .BuildServiceProvider();
        }

        private class SomeWorkflow : IWorkflow
        {
            public void Build(IWorkflowBuilder builder)
            {
                builder.StartWith<Signaled>(_ => _.Signal = new LiteralExpression("Whatever"))
                    .Then<WriteLine>(_ => _.TextExpression = new LiteralExpression("Cya"));
            }
        }
    }   
}
```

Produces:
```
Unhandled exception. Elsa.Exceptions.WorkflowException: Error while evaluating JavaScript expression "{"foo":"bar"}". Message: Line 1: Unexpected token :
   at Elsa.Expressions.WorkflowExpressionEvaluator.EvaluateAsync(IWorkflowExpression expression, Type type, WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken)
   at Elsa.Extensions.WorkflowExpressionEvaluatorExtensions.EvaluateAsync[T](IWorkflowExpressionEvaluator evaluator, IWorkflowExpression`1 expression, WorkflowExecutionContext workflowExecutionContext, CancellationToken cance
llationToken)
   at ElsaSample.Program.Main() in C:\Users\gat\Source\ElsaDictionaries\ElsaSample\Program.cs:line 33
   at ElsaSample.Program.<Main>()
```

**Comment by gztamas** [comment]
Apparently the way to define the variables instance as a JavaScriptExpression is:
`({"foo":{"value":"bar"}})`
