### ISSUE TITLE
Exception in Dashboard after it executed some workflows

### ISSUE THREAD

**Issue by rfrcarvalho** [elsa-workflows/elsa-core#386]
After I execute a workflow I'm no longer able to click the "/Elsa/workflow-definition" as I get the exception below:

```
Newtonsoft.Json.JsonSerializationException: Error converting value "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Elsa.Activities.Http.Models.StringValuesModel, Elsa.Activities.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib" to type 'Elsa.Activities.Http.Models.StringValuesModel'. Path 'TypeName', line 1, position 13284.
 ---> System.ArgumentException: Could not cast or convert from System.String to Elsa.Activities.Http.Models.StringValuesModel.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Elsa.Serialization.Handlers.ObjectHandler.Deserialize(JsonReader reader, JsonSerializer serializer, Type type, JToken value) in D:\a\1\s\aspnet-core\src\Elsa\core\Elsa.Abstractions\Serialization\Handlers\ObjectHandler.cs:line 19
   at Elsa.Converters.TypeNameHandlingConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\a\1\s\aspnet-core\src\Elsa\core\Elsa.Abstractions\Converters\TypeNameHandlingConverter.cs:line 57
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Elsa.Persistence.EntityFrameworkCore.DbContexts.ElsaContext.DeserializeScopes(String json) in D:\a\1\s\aspnet-core\src\Elsa\persistence\Elsa.Persistence.EntityFrameworkCore\DbContexts\ElsaContext.cs:line 182
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.ListByDefinitionAsync(String definitionId, CancellationToken cancellationToken) in D:\a\1\s\aspnet-core\src\Elsa\persistence\Elsa.Persistence.EntityFrameworkCore\Services\EntityFrameworkCoreWorkflowInstanceStore.cs:line 89
   at Elsa.Extensions.AsyncEnumerableExtensions.ToListAsync[T](Task`1 task) in D:\a\1\s\aspnet-core\src\Elsa\core\Elsa.Abstractions\Extensions\AsyncEnumerableExtensions.cs:line 12
   at Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.CreateWorkflowDefinitionListItemModelAsync(WorkflowDefinitionVersion workflowDefinition, CancellationToken cancellationToken) in D:\a\1\s\aspnet-core\src\Elsa\dashboard\Elsa.Dashboard\Areas\Elsa\Controllers\WorkflowDefinitionController.cs:line 187
   at Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.Index(CancellationToken cancellationToken) in D:\a\1\s\aspnet-core\src\Elsa\dashboard\Elsa.Dashboard\Areas\Elsa\Controllers\WorkflowDefinitionController.cs:line 64
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler) in D:\a\1\s\aspnet-core\src\Elsa\activities\Elsa.Activities.Http\Middleware\RequestHandlerMiddleware.cs:line 22
   at DevExpress.AspNetCore.Internal.BinaryStorageMiddleware.Invoke(HttpContext httpContext)
   at DevExpress.AspNetCore.Internal.ResourceManagerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

If I delete the entries in the ActivityInstances and WorkflowInstances it works again.

Anyone having this problem or know how to solve this?

Sometimes it gives an error about a HelpURL missing but I checked the all code and there's nothing with that.

**Comment by sfmskywalker** [comment]
Are you setting a variable from any of the activities by any chance? If so, what value? Perhaps a value is being set that doesn't serialize well.

**Comment by rfrcarvalho** [comment]
I am using 3 SetVariable and one of them is a list (Headers) of the Input. I'll try to change that SetVariable to just one value and see if it makes difference.

**Comment by rfrcarvalho** [comment]
This is an image of the workflow:
![image](https://user-images.githubusercontent.com/4267071/94591397-f3d72f00-027f-11eb-8504-864fcedfd21d.png)

It stores the lastResult().Body in a Variable called input to be accessed during the Workflow.
After the previous post, I changed so that instead of storing the Headers, I just store the Authorization header and the problem remains.

Any idea?

**Comment by lmartinjr** [comment]
I ran into the same problem if i had some workflow instances fail without completing due to issues while evaluating expressions (both Javascript and Liquid). I was able to duplicate the problem by allowing a workflow to complete successfully and i could revisit that page and then if a workflow failed while evaluating an expression it would throw the error. Do you know if you have instances where some of your workflow activities fail during processing? There is an issue i reported that I believe is the same as 341 that seems to be the cause of my problem. Not sure if this applies to your situation or not.

**Comment by rfrcarvalho** [comment]
If I use the packages directly from NuGet instead of using the source code, the problem with the success workflows goes away. Yes, I'm back to that problem that if one Workflow fails it shows the other exception. I'll wait for the next release as for now it's working with successful workflows.

**Comment by hyzx86** [comment]
: https://github.com/elsa-workflows/elsa-core/issues/411
I have the same problem this issue. 
I tried the nuget package and the source code of the dev branch. They have the same problem.

And no matter whether the workflow succeeds or fails, as long as there is a workflow instance, the workflow list cannot be opened.

**Comment by ssanderlin** [comment]
I was having the same issue. In my specific instance, it was throwing when I was trying to JSON.parse() a null value - I was intentionally triggering the workflow with an empty body with the expectation of breaking it - just not in this way. 

Regardless, I would expect that ELSA would be able to handle deserializing an exception where HelpLink is null.

``` json
{"FaultedActivityId":"<redacted>","Message":"Error while evaluating JavaScript expression \"JSON.parse(lastResult().Body)\". Message: Specified argument was out of the range of valid values. (Parameter 'column')\r\nActual value was 1.","Exception":{"StackTrace":"   at Elsa.Expressions.WorkflowExpressionEvaluator.EvaluateAsync(IWorkflowExpression expression, Type type, WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken)\r\n   at Elsa.Activities.SetVariable.OnExecuteAsync(WorkflowExecutionContext workflowContext, CancellationToken cancellationToken)\r\n   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)","Message":"Error while evaluating JavaScript expression \"JSON.parse(lastResult().Body)\". Message: Specified argument was out of the range of valid values. (Parameter 'column')\r\nActual value was 1.","Data":{},"InnerException":null,"HelpLink":null,"Source":"Elsa.Core","HResult":-2146233088}}
```
