### ISSUE TITLE
 Exception occurred while invoking workflows.

### ISSUE THREAD

**Issue by wzd24** [elsa-workflows/elsa-core#387]
When I test the Elsa.Dashboard.Web project, An Exception occurred while invoking workflow. pls help me to solve it, tks.

Exception details:
fail: Elsa.Activities.Timers.HostedServices.TimersHostedService[0]
      Exception occurred while invoking workflows.
System.ArgumentException: No such activity type: ReadLine (Parameter 'activityTypeName')
   at Elsa.Services.ActivityResolver.ResolveActivityType(String activityTypeName) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\ActivityResolver.cs:line 36
   at Elsa.Services.ActivityResolver.ResolveActivity(String activityTypeName, Action`1 setup) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\ActivityResolver.cs:line 45
   at Elsa.Services.WorkflowFactory.CreateActivity(ActivityDefinition definition) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\WorkflowFactory.cs:line 83
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Elsa.Services.WorkflowFactory.CreateWorkflow(WorkflowDefinitionVersion definition, Variables input, WorkflowInstance workflowInstance, String correlationId) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\WorkflowFactory.cs:line 50
   at Elsa.Services.WorkflowInvoker.StartManyAsync(IEnumerable`1 workflowDefinitions, Variables input, String correlationId, CancellationToken cancellationToken1) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\WorkflowInvoker.cs:line 245
   at Elsa.Services.WorkflowInvoker.StartManyAsync(String activityType, Variables input, String correlationId, Func`2 activityStatePredicate, CancellationToken cancellationToken) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\WorkflowInvoker.cs:line 179
   at Elsa.Services.WorkflowInvoker.TriggerAsync(String activityType, Variables input, String correlationId, Func`2 activityStatePredicate, CancellationToken cancellationToken) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\core\Elsa.Core\Services\WorkflowInvoker.cs:line 122
   at Elsa.Activities.Timers.HostedServices.TimersHostedService.ExecuteAsync(CancellationToken stoppingToken) in D:\Users\28070110\Source\Repos\elsa-workflows\elsa-core\src\activities\Elsa.Activities.Timers\HostedServices\TimersHostedService.cs:line 41

workflow file:
[workflow.zip](https://github.com/elsa-workflows/elsa-core/files/5302777/workflow.zip)

**Comment by 463728946** [comment]
.AddTimerActivities(options => options.Configure(x => x.SweepInterval = Duration.FromSeconds(1)))

**Comment by wzd24** [comment]
@463728946  Tks for response, I find the reason is not add .AddConsole().

**Comment by shinernath** [comment]
Add AddElsa function as below
services
                .AddElsa()
                .AddConsoleActivities()
                .AddTimerActivities(options => options.Configure(x => x.SweepInterval = Duration.FromSeconds(1)))
                .AddWorkflow<RecurringTaskWorkflow>();
