### ISSUE TITLE
Serialization and deserialization of 'System.IntPtr' instances are not supported.

### ISSUE THREAD

**Issue by CrazyToMin** [elsa-workflows/elsa-core#3976]
Hello
I often get the following error when using .net7
Serialization and deserialization of 'System.IntPtr' instances are not supported.
I hope you can help me to see what is the problem?
Thanks

**Comment by sfmskywalker** [comment]
Sure. I've never seen that happening myself, so you'll need to provide a little bit more context. Are you using custom activities, for example? If so, what do these look like? What does your project look like, is it a standard setup that can be found in documentation, are you using els 2 or 3, etc.

**Comment by CrazyToMin** [comment]
I use elsa 2, framework is abp7.0 , I do not use custom activities, I feel is net 7 error

**Comment by CrazyToMin** [comment]
And I hadn't had this problem before in the .net 5 framework, and after the upgrade it appeared

**Comment by sfmskywalker** [comment]
Do you have a stack trace we can look at?

**Comment by personball** [comment]
I got this problem too.

dotnet net7.0

```
    <PackageReference Include="Elsa" Version="2.12.0" />
    <PackageReference Include="Elsa.Activities.Console" Version="2.12.0" />
    <PackageReference Include="Elsa.Activities.Http" Version="2.12.0" />
    <PackageReference Include="Elsa.Activities.Temporal.Quartz" Version="2.12.0" />
    <PackageReference Include="Elsa.Designer.Components.Web" Version="2.12.0" />
    <PackageReference Include="Elsa.Persistence.EntityFramework.Postgresql" Version="2.12.0" />
    <PackageReference Include="Elsa.Server.Api" Version="2.12.0" />
```

```
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Volo.Abp.Auditing.JsonAuditSerializer.Serialize(Object obj)
   at Volo.Abp.Auditing.AuditingHelper.SerializeConvertArguments(IDictionary`2 arguments)
```

Disable abp auditing maybe a way to keep this away.
