### ISSUE TITLE
Unable to Add SQL Scripting

### ISSUE THREAD

**Issue by fshahin90** [elsa-workflows/elsa-core#4017]
```
dotnet: 7
Elsa Workflow : 2.11.1
```
I've Installed the [SQL Scripting Package](https://nugetprodusnc-northcentralus-01.regional.azure-api.net/packages/Elsa.Activities.Sql/) and added the `AddSqlScripting()` in Startup but when I open the designer and try to find the `SQL Scripting` section or fnctions
Startup Code:
```C#
using Elsa;
using Elsa.Scripting.Sql;
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Elsa.Persistence.EntityFramework.SqlServer;


var builder = WebApplication.CreateBuilder(args);
var elsaSection = builder.Configuration.GetSection("Elsa");
builder.Services.AddElsa(elsa=> 
    elsa.UseEntityFrameworkPersistence(ef=>ef.UseSqlServer("Server=localhost;Database=elsadb;Integrated Security=True;TrustServerCertificate=True"))
    .AddConsoleActivities()
    .AddHttpActivities(elsaSection.GetSection("Server").Bind)
    .AddQuartzTemporalActivities()
    .AddEmailActivities()
    .AddJavaScriptActivities()
    .AddSqlScripting()
    .AddWorkflowsFrom<Elsa.Persistence.EntityFramework.SqlServer.Startup>()
    );
builder.Services.AddElsaApiEndpoints();

builder.Services.AddCors(cors => cors.AddDefaultPolicy(policy => policy
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowAnyOrigin()
                .WithExposedHeaders("Content-Disposition")));

builder.Services.AddRazorPages();

var app = builder.Build();
app.UseCors()
    .UseHttpActivities()
    .UseRouting()
    .UseEndpoints(endpoints =>
    {
        // Elsa API Endpoints are implemented as regular ASP.NET Core API controllers.
        endpoints.MapControllers();
    });
app.UseStaticFiles();
app.UseRouting();
app.UseEndpoints(endpoint => { endpoint.MapFallbackToPage("/_Host"); });


app.Run();

```

what i get

![image](https://github.com/elsa-workflows/elsa-core/assets/29918683/365f1edd-93e5-41b2-b2e7-9297d055f982)

![image](https://github.com/elsa-workflows/elsa-core/assets/29918683/1f14e81e-4439-434f-8b0e-cefa685fbae2)

After searching and viewing the code in github found the following:
1. when adding the namespace `Elsa.Activities.Sql.Extensions` and adding `AddSqlServerActivities` to the config the following happens
- the items appear in the menu
![image](https://github.com/elsa-workflows/elsa-core/assets/29918683/3bc1431b-5364-4cc1-b2b0-f7c5ec6254d9)
- the `Execute SQL Query `modal appear but missing the fields to enter the query
![image](https://github.com/elsa-workflows/elsa-core/assets/29918683/fedb4972-dfbf-4f7e-b6ec-39a99b1e7679)
- the `Execute SQL Command` modal doesnt appear
2. If i added the following `AddActivitiesFrom<Elsa.Activities.Sql.Startup>()`  an error appear
```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Elsa.Activities.Sql.Activities.ExecuteSqlCommand Lifetime: Transient ImplementationType: Elsa.Activities.Sql.Activities.ExecuteSqlCommand': Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlCommand'.) (Error while validating the service descriptor 'ServiceType: Elsa.Activities.Sql.Activities.ExecuteSqlQuery Lifetime: Transient ImplementationType: Elsa.Activities.Sql.Activities.ExecuteSqlQuery': Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlQuery'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Activities.Sql.Activities.ExecuteSqlCommand Lifetime: Transient ImplementationType: Elsa.Activities.Sql.Activities.ExecuteSqlCommand': Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlCommand'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlCommand'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in D:\test\ElsaQuickstarts.Server.Dashboard\Program.cs:line 34
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Elsa.Activities.Sql.Activities.ExecuteSqlQuery Lifetime: Transient ImplementationType: Elsa.Activities.Sql.Activities.ExecuteSqlQuery': Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlQuery'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Elsa.Activities.Sql.Factory.ISqlClientFactory' while attempting to activate 'Elsa.Activities.Sql.Activities.ExecuteSqlQuery'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---
```

**Comment by mircotamburini** [comment]
It's already fixed by me
https://github.com/elsa-workflows/elsa-core/commit/6cd4808021c8ae52d87596a5fc57b52e935ce2c0

**Comment by fshahin90** [comment]
@mircotamburini 
thanks for the reply but if its fixed what am i missing in the configuration? or is it a missing dependency? below is the installed packages that i have installed
![image](https://github.com/elsa-workflows/elsa-core/assets/29918683/43818ab2-dc75-418f-a6be-a3a1f04c42e3)

**Comment by mohdali** [comment]
Fix is released in https://github.com/elsa-workflows/elsa-core/releases/tag/2.12.0

**Comment by fshahin90** [comment]
I have updated the pakages to the latest release 2.12.0 but still the problem havent been resolved the same error appears
here is the pakage reference
```xml
<ItemGroup>
  <PackageReference Include="Elsa" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Conductor" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Email" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Entity" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.File" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Http" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Sql" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Temporal.Hangfire" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Timers" Version="2.0.0-preview7.1545" />
  <PackageReference Include="Elsa.Activities.UserTask" Version="2.12.0" />
  <PackageReference Include="Elsa.Activities.Webhooks" Version="2.12.0" />
  <PackageReference Include="Elsa.Designer.Components.Web" Version="2.12.0" />
  <PackageReference Include="Elsa.Persistence.EntityFramework.Core" Version="2.12.0" />
  <PackageReference Include="Elsa.Persistence.EntityFramework.SqlServer" Version="2.12.0" />
  <PackageReference Include="Elsa.Persistence.EntityFrameworkCore" Version="1.5.5.1943" />
  <PackageReference Include="Elsa.Scripting.JavaScript" Version="2.12.0" />
  <PackageReference Include="Elsa.Scripting.Sql" Version="2.12.0" />
  <PackageReference Include="Elsa.Server.Api" Version="2.12.0" />
</ItemGroup>
```

if there is a working example for the SQL activities that I can compare the configuration with my configuration whould be appresiated

**Comment by mohdali** [comment]
@fshahin90 try using the extension method from the package instead. `AddSqlServerActivities`. It will add the factory and scripting support.

**Comment by fshahin90** [comment]
@mohdali Thanks that solved it. but shoulnt the line `elsa.AddActivitiesFrom<Elsa.Activities.Sql.Startup>()` add's it? just curious!

**Comment by mohdali** [comment]
> @mohdali Thanks that solved it. but shoulnt the line `elsa.AddActivitiesFrom<Elsa.Activities.Sql.Startup>()` add's it? just curious!

The recent change introduced a new injectable `SqlClientFactory` which allows you to extend the functionality and add more client types. E.g. if you need to connect to Oracle database instead. The extension method loads the default factory, but you can also provide your own.

Simply adding the activities doesn't define a factory, unfortunately.

**Comment by fshahin90** [comment]
OK thanks for the help
