### ISSUE TITLE
Error when attempting to delete workflow step

### ISSUE THREAD

**Issue by zejji** [elsa-workflows/elsa-core#4062]
I started using Elsa today and immediately ran into an issue when attempting to delete a workflow step in the visual workflow editor.

When attempting to delete a 'SetName' node I get the following JavaScript error in the Edge dev tools console and the node fails to delete:
```
 Cannot read properties of undefined (reading 'activityId')
    at ElsaWorkflowDesigner$1.removeA
[workflow-definition-e3bac827bc3742f18a2b75d05a0f498a (1).zip](https://github.com/elsa-workflows/elsa-core/files/11547755/workflow-definition-e3bac827bc3742f18a2b75d05a0f498a.1.zip)
ctivityInternal (p-6a7ea7d0.entry.js:2:448981)
    at p-6a7ea7d0.entry.js:2:444808
    at Array.forEach (<anonymous>)
    at ElsaWorkflowDesigner$1.removeSelectedActivities (p-6a7ea7d0.entry.js:2:444788)
    at p-ee0b9025.js:1:9279
    at async x.onDeleteActivityClick (p-46da2189.entry.js:1:20943)
```

I attach an exported workflow definition file which should reproduce the issue if you attempt to delete the node labelled 'Delete me please'.
[workflow-definition-e3bac827bc3742f18a2b75d05a0f498a (1).zip](https://github.com/elsa-workflows/elsa-core/files/11547759/workflow-definition-e3bac827bc3742f18a2b75d05a0f498a.1.zip)

I'm running the dashboard + server Docker image as follows:
```
docker run --rm -t -i -e ELSA__SERVER__BASEURL=http://localhost:13000 -e ASPNETCORE_ENVIRONMENT=Development -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest
```
The Elsa version is stated to be 2.13.

**Comment by daigs** [comment]
多刷新几次再右键删除就好了

**Comment by IsaacHayes1995** [comment]
Also getting the exact same error in version 2.12.0.
@zejji did you find a workaround?

**Comment by sfmskywalker** [comment]
Closing because this issue targets Elsa 2 or the legacy dashboard stack, which is no longer an actively supported target in this repository. Current UI work happens in Elsa Studio for Elsa 3. If you can still reproduce the underlying problem on a supported Elsa 3 + Elsa Studio setup, please open a new issue with fresh reproduction steps.
