### ISSUE TITLE
Unable to create workflow definitions via Api

### ISSUE THREAD

**Issue by MikeDLi** [elsa-workflows/elsa-core#4162]
Hi-

I've been trying to create a workflow definition by using the HelloWorld example:

curl --location --request POST 'https://localhost:5001/elsa/api/workflow-definitions' \
--header 'Authorization: ApiKey {api_key}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Hello World",
    "root": {
        "type": "Elsa.WriteLine",
        "text": "Hello World!"
    },
    "publish": true
}'

But it's throwing exceptions as follows:

An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Workflows.Api.Endpoints.WorkflowDefinitions.Post.Post.HandleAsync(SaveWorkflowDefinitionRequest request, CancellationToken cancellationToken)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Thanks

Mike

**Comment by MikeDLi** [comment]
Sorry I forgot mentioning that I'm using 3.0.0-rc1. Thx

**Comment by MikeDLi** [comment]
Hi-

Just to follow up. Using the 3.0.0-rc1 source code, the error occurs in file Elsa.Workflows.Api.Middleware.JsonSerializationErrorHandlerMiddleware.cs, line 14, InvokeAsync: JsonSerializationErrorHandlerMiddleware: httpContext throws an exception:

((Microsoft.AspNetCore.Http.DefaultHttpContext)httpContext).Session = '((Microsoft.AspNetCore.Http.DefaultHttpContext)httpContext).Session' threw an exception of type 'System.InvalidOperationException'

Any input is appreciated!

Thanks

Mike

**Comment by sfmskywalker** [comment]
Hi @MikeDLi !

I'm afraid I forgot to update the sample request to follow the new body structure for this API endpoint.
The following structure should work:

```json
{
    "model": {
        "name": "Hello World",
        "root": {
            "type": "Elsa.WriteLine",
            "text": "Hello World!"
        }
    },
    "publish": true
}
```

**Comment by sfmskywalker** [comment]
I have updated the sample in the documentation.

**Comment by MikeDLi** [comment]
Thank you so much!

Mike
