### ISSUE TITLE
How can I create a custom activity property that is a Dictionary?

### ISSUE THREAD

**Issue by dambros** [elsa-workflows/elsa-core#4252]
I am trying to create an activity that will have a checklist and I want each of the item to display the name but also have the ids attached.

```
public class MetricsActivity : Activity, IActivityPropertyOptionsProvider, IRuntimeSelectListProvider
{
    
    [ActivityInput(
        Hint = "Test",
        UIHint = ActivityInputUIHints.CheckList,
        OptionsProvider = typeof(MetricsActivity),
        DefaultSyntax = SyntaxNames.Json
    )]
    public IDictionary<string, string> Names { get; set; } = new Dictionary<string, string>();

    protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
    {
        Console.WriteLine("Hello World!");

        return Done();
    }

    public object? GetOptions(PropertyInfo property)
    {
        //values will come from a db
        var dictionary = new Dictionary<string, string>
        {
            {"key1", "value1"},
            {"key2", "value2"},
            {"key3", "value3"}
        };
        return new RuntimeSelectListProviderSettings(GetType(), dictionary);
    }

    public ValueTask<SelectList> GetSelectListAsync(object? context = null,
        CancellationToken cancellationToken = new CancellationToken())
    {
        var tList = (Dictionary<string, string>)context!;
        var items = tList.Select(x => new SelectListItem(x.Value, x.Key)).ToArray();
        return new ValueTask<SelectList>(new SelectList(items));
    }
}
```

On the dashboard this shows correctly, but when I try to run the workflow and get the value of Names, an exception is thrown saying:

```
An exception was thrown whilst setting 'MetricsActivity.Names'. See the inner exception for further details.
       ---> Elsa.Exceptions.ExpressionEvaluationException: Failed to evaluate expression
       ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.IDictionary`2[System.String,System.String]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
      To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
      Path '', line 1, position 1.
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
```

What is the correct way to do this please?

**Comment by arkhokhar** [comment]
how can you achieved that?
