### ISSUE TITLE
Elsa 3 Mongo persistence provider bug

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#4272]
Steps to reproduce:

1. From the designer add an HTTP Endpoint activity. 
2. Add an HTTP Response Activity. 
3. Connect the two Activities.
4. Publish

On Publish the error below is thrown. 

MongoDB.Driver.MongoBulkWriteException`1[Elsa.Workflows.Runtime.Entities.StoredTrigger]: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "Uncategorized", Code : 52, Message : "The dollar ($) prefixed field '$type' in 'Payload.$type' is not valid for storage." } ].
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Elsa.MongoDb.Common.MongoDbStore`1.SaveManyAsync(IEnumerable`1 documents, CancellationToken cancellationToken)
   at Elsa.MongoDb.Modules.Runtime.MongoTriggerStore.ReplaceAsync(IEnumerable`1 removed, IEnumerable`1 added, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.TriggerIndexer.IndexTriggersAsync(Workflow workflow, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.TriggerIndexer.IndexTriggersAsync(WorkflowDefinition definition, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Handlers.IndexWorkflowTriggersHandler.HandleAsync(WorkflowDefinitionPublished notification, CancellationToken cancellationToken)
   at Elsa.Mediator.PublishingStrategies.SequentialProcessingStrategy.PublishAsync(NotificationStrategyContext context)
   at Elsa.Mediator.Middleware.Notification.Components.NotificationHandlerInvokerMiddleware.InvokeAsync(NotificationContext context)
   at Elsa.Mediator.Middleware.Notification.NotificationPipeline.ExecuteAsync(NotificationContext context)
   at Elsa.Mediator.Services.DefaultMediator.SendAsync(INotification notification, IEventPublishingStrategy strategy, CancellationToken cancellationToken)
   at Elsa.Extensions.MediatorExtensions.SendAsync(INotificationSender publisher, INotification notification, CancellationToken cancellationToken)
   at Elsa.Workflows.Management.Services.WorkflowDefinitionPublisher.PublishAsync(WorkflowDefinition definition, CancellationToken cancellationToken)
   at Elsa.Workflows.Api.Endpoints.WorkflowDefinitions.Post.Post.HandleAsync(SaveWorkflowDefinitionRequest request, CancellationToken cancellationToken)
   at Elsa.Workflows.Api.Endpoints.WorkflowDefinitions.Post.Post.HandleAsync(SaveWorkflowDefinitionRequest request, CancellationToken cancellationToken)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by sfmskywalker** [comment]
Hi Rick,

When I trie to reproduce this issue, I ran into the following:

1. First attempt, workflow publishing failed because I didn't provide a path in the HTTP Endpoint activity - which fails validation and current throws an exception.
2. When want to retry, I first tried to delete the workflow I created to start with a clean slate. However, I then encountered a different issue with the MongoDB persistence provider.

When I fixed that, I was able to successfully publish the workflow as per your description.

If you're using the RC1 package from NuGet, or even the latest preview version from NuGet, I recommend trying out the latest preview build from [feedz.io](https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json) instead.

If you can still reproduce the reported issue using those packages, I would like to ask you to send me a small solution that demonstrates the issue so I can take a closer look.

**Comment by ricksearcy** [comment]
@sfmskywalker this appears to be an issue with the Mongo version we are using which was compatible with Elsa 2, but now does not appear to be. I upgraded to the latest Mongo version locally and the issue was resolved, but that leaves us with the problem of having to upgrade all our Mongo servers in order to use Elsa 3. Do you happen to know what the Mongo version requirements for ELsa 3 are?

**Comment by sfmskywalker** [comment]
Aha. Well, Elsa 3 itself does not directly impose any specific MongoDB version requirements. However, it's worth noting that it does utilize the latest MongoDB .NET driver. While Elsa isn't version-specific, the MongoDB .NET driver may have its own compatibility constraints with various MongoDB versions.

In other words, the MongoDB version requirements for Elsa 3 are indirectly determined by the MongoDB .NET driver version it uses. To clarify the version of MongoDB you would need, it may be helpful to refer to the compatibility documentation of the MongoDB .NET driver Elsa 3 is currently using, which is `MongoDB.Driver` package version `2.19.1`.
