### ISSUE TITLE
'Object reference not set to an instance of an object' error after restarting

### ISSUE THREAD

**Issue by johnwc** [elsa-workflows/elsa-core#4276]
Ever since adding hangfire, we now get the following error after restarting our k8s pods. It will eventually start after throwing this error a few times. It seems that each node will throw this error until one starts, then another will not throw and start etc... Like a node is locking something during start, and all others throw this error?

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.<>c.<QueryRecurringJobs>b__14_0(RecurringJobDto x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.DeleteRecurringJobs(String workflowDefinitionId)
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.UnscheduleAsync(String workflowDefinitionId, CancellationToken cancellationToken)
   at Elsa.Activities.Temporal.Common.Handlers.ScheduleTimers.Handle(TriggerIndexingFinished notification, CancellationToken cancellationToken)
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken)
   at Elsa.StartupTasks.IndexTriggers.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /src/Dashboard/Program.cs:line 213
```

**Comment by johnwc** [comment]
@sfmskywalker this is still happening, even with hangfire 1.8. I don't know what to look at for what is causing this. There is little to no logging with these classes as well.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.<>c.<QueryRecurringJobs>b__14_0(RecurringJobDto x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.DeleteRecurringJobs(String workflowDefinitionId)
   at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowDefinitionScheduler.UnscheduleAsync(String workflowDefinitionId, CancellationToken cancellationToken)
   at Elsa.Activities.Temporal.Common.Handlers.UnscheduleTimers.Handle(TriggersDeleted notification, CancellationToken cancellationToken)
   at MediatR.Wrappers.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification, CancellationToken theToken)
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.DeleteTriggersAsync(String workflowDefinitionId, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken)
   at Elsa.StartupTasks.IndexTriggers.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.StartupAsync(CancellationToken cancellationToken)
   at Elsa.HostedServices.StartupRunnerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /src/Dashboard/Program.cs:line 218
```

**Comment by sfmskywalker** [comment]
Some mor logging might help track down what variable specifically is null, if you want to add it to the `HangfireWorkflowDefinitionScheduler` class and it’s `QueryRecurringJobs`. Looking at its implementation, I suspect that maybe it returns null.

**Comment by johnwc** [comment]
It's 1 AM my time, think you could add some logging into 2.13 preview for us to be able to test in the morning?

**Comment by sfmskywalker** [comment]
I would if I could, but unfortunately I’m stacked with other obligations as it is, sorry.

**Comment by sfmskywalker** [comment]
Looks like I got a little break (and therefore you too I guess! 😉 ) leaving me with a small window to add some logging.

**Comment by sfmskywalker** [comment]
Based on the stack trace, it happens when `DeleteRecurringJobs` is called, which in turn calls `QueryRecurringJobs`, which uses a predicate to filter jobs of a given type:

```csharp
using var connection = _jobStorage.GetConnection();
return connection.GetRecurringJobs().Where(x => x.Job.Type == typeof(RunHangfireWorkflowDefinitionJob));
```

I suspect that any of these values can be null: `x` and `x.Job`.  The `connection` itself is never null, since the `GetConnection` method instantiates a new connection object for the active provider.

To try and confirm my suspicion, let me push the following change:

```csharp
return connection.GetRecurringJobs().Where(x => x?.Job?.Type == typeof(RunHangfireWorkflowDefinitionJob));
```

After which the issue should be gone.

**Comment by sfmskywalker** [comment]
I pushed this commit: 21914db8dc2db545ef50ca704b3ece999c579586

**Comment by johnwc** [comment]
That seemed to have fixed that specific error in that class. But it seems to be occurring in `Elsa.Retention.HostedServices.CleanupHostedService` as well. The bigger question here, is what is causing it to have null objects here?

**Comment by sfmskywalker** [comment]
That is indeed the question. Unfortunately that's a hard one to answer without being able to reproduce this on my local machine. If you have any clues how to reproduce this on a local machine on a fresh Elsa 2 installation (no custom code) then I might be able to help figure it out.

**Comment by sfmskywalker** [comment]
> But it seems to be occurring in `Elsa.Retention.HostedServices.CleanupHostedService` as well.

Do you happen to have a stack trace that might help better pinpoint the needle?

**Comment by johnwc** [comment]
This is as much as I can see from the pod log.

```
 Elsa.Retention.HostedServices.CleanupHostedService[0] Failed to perform cleanup this time around. Next cleanup attempt will happen in 00:10:00 System.NullReferenceException: Object reference not set to an instance of an object.
    at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowInstanceScheduler.<>c.<QueryRecurringJobs>b__14_0(RecurringJobDto x)
    at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
    at System.Linq.Enumerable.WhereListIterator`1.ToList()
    at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowInstanceScheduler.DeleteRecurringJobs(String workflowInstanceId)
    at Elsa.Activities.Temporal.Hangfire.Services.HangfireWorkflowInstanceScheduler.UnscheduleAsync(String workflowInstanceId, CancellationToken cancellationToken)
    at Elsa.Activities.Temporal.Common.Handlers.UnscheduleTimers.Handle(BookmarksDeleted notification, CancellationToken cancellationToken)
    at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
    at Elsa.Services.Bookmarks.BookmarkIndexer.DeleteBookmarksAsync(String workflowInstanceId, CancellationToken cancellationToken)
    at Elsa.Handlers.UpdateBookmarksAndRunPostTasks.Handle(ManyWorkflowInstancesDeleted notification, CancellationToken cancellationToken)
    at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
    at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.DeleteManyAsync(ISpecification`1 specification, CancellationToken cancellationToken)
    at Elsa.Retention.Jobs.CleanupJob.DeleteManyAsync(ICollection`1 workflowInstanceIds, CancellationToken cancellationToken)
    at Elsa.Retention.Jobs.CleanupJob.ExecuteAsync(CancellationToken cancellationToken)
    at Elsa.Retention.HostedServices.CleanupHostedService.ExecuteAsync(CancellationT
```
