### ISSUE TITLE
Serialization Exception

### ISSUE THREAD

**Issue by happtim** [elsa-workflows/elsa-core#4336]
I am using elas v3 version, an exception occurred when I tried to serialize the Activity using code.

State class inherits from Activity.
```
var stateA = new State()
{
    Name = "State A",
    Entry = new WriteLine( "Entry A"),
};
```
When serializing the State class, an exception was raised.

```
System.Exception: Expression of type Elsa.Expressions.LiteralExpression not found in registry

System.Exception
Expression of type Elsa.Expressions.LiteralExpression not found in registry
   at Elsa.Workflows.Management.Serialization.Converters.ExpressionJsonConverter.Write(Utf8JsonWriter writer, IExpression value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
...
```
I found that the exception occurs when writing json in the `ExpressionJsonConverter`. The type obtained from `Type expressionType = value.GetType();` value is `Elsa.Expressions.LiteralExpression`, but the registered name is `Literal`.

I specially exported the JSON from the designer as follows.
```
"text": { 
    "typeName": "String",
    "expression": {
      "type": "Literal",
      "value": "hellow"
    },
    "memoryReference": {
      "id": "8cbf6793-3cfd-46b9-beca-53e64edbebc1"
    }
  },
```

**Comment by sfmskywalker** [comment]
Hi @happtim , thanks for reporting this issue. Is there any chance you could share a small project that reproduces this issue?

**Comment by happtim** [comment]
Thank you for your reply. I have provided the test code below.

```
// Setup service container.
var services = new ServiceCollection();

// Add Elsa services.
services.AddElsa();

// Build service container.
var serviceProvider = services.BuildServiceProvider();

// Resolve a workflow runner to run the workflow.
var workflowRunner = serviceProvider.GetRequiredService<IWorkflowRunner>();

var apiSerializer = serviceProvider.GetRequiredService<IApiSerializer>();

// Define a simple workflow, which in this case is a very simple activity that writes something to the console:
var workflow = new WriteLine("Hello world!");

var serializerOptions = apiSerializer.CreateOptions();

// Ignore the root activity when serializing the workflow definition.
serializerOptions.Converters.Add(new JsonIgnoreCompositeRootConverterFactory());

var stringData = JsonSerializer.Serialize(workflow, serializerOptions);

// Run the workflow.
await workflowRunner.RunAsync(workflow);
```

the exception message below

```
 at Elsa.Workflows.Management.Serialization.Converters.ExpressionJsonConverter.Write(Utf8JsonWriter writer, IExpression value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Elsa.Workflows.Core.Serialization.Converters.JsonIgnoreCompositeRootConverter.Write(Utf8JsonWriter writer, IActivity value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`2.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at UserQuery.Main(), line 23
```

**Comment by sfmskywalker** [comment]
Hello,

Thank you for providing a detailed repro of the issue. We have some updates for you:

1. **Reproduction**: We were able to reproduce the issue on our end. Your detailed steps were very helpful.

2. **Bug Fix**: We identified the bug and have pushed a fix. You can find the commit here: [68a20de07f810a5f7bce65fe3d97151bca095124](https://github.com/elsa-workflows/elsa-core/commit/68a20de07f810a5f7bce65fe3d97151bca095124).

3. **Populating Registries**: To address the issue, you need to populate the registries. Here's the code snippet for that:

   ```csharp
   // Populate registries.
   var populator = serviceProvider.GetRequiredService<IRegistriesPopulator>();
   await populator.PopulateAsync();
   ```

4. **Complete Listing**: For clarity, here's the complete listing of the code:

   ```csharp
   using Elsa.Extensions;
   using Elsa.Workflows.Core.Activities;
   using Elsa.Workflows.Core.Contracts;
   using Elsa.Workflows.Runtime.Contracts;
   using Microsoft.Extensions.DependencyInjection;

   var services = new ServiceCollection();

   // Add Elsa services.
   services.AddElsa();

   // Build service container.
   var serviceProvider = services.BuildServiceProvider();

   // Populate registries.
   var populator = serviceProvider.GetRequiredService<IRegistriesPopulator>();
   await populator.PopulateAsync();

   // Resolve a workflow runner to run the workflow.
   var workflowRunner = serviceProvider.GetRequiredService<IWorkflowRunner>();

   // Define a simple workflow, which in this case is a very simple activity that writes something to the console:
   var workflow = new WriteLine("Hello world!");

   var activitySerializer = serviceProvider.GetRequiredService<IActivitySerializer>();

   var stringData = activitySerializer.Serialize(workflow);

   // Run the workflow.
   await workflowRunner.RunAsync(workflow);
   ```

5. **Latest Preview Package**: Please ensure that you pull the latest preview package to get the fix.

Thank you for bringing this to our attention. Let us know if you face any other issues.
