### ISSUE TITLE
Elsa v3: Exception when mapping HttpEndpoint result to variable 

### ISSUE THREAD

**Issue by schneidersympatient** [elsa-workflows/elsa-core#4395]
When trying to map the Output "Result" of an HTTP Endpoint to an variable (type HttpRequest or object) the following exception occurs:

```
System.NotSupportedException: Specified method is not supported. The unsupported member type is located on type 'System.Int64'. Path: $.HttpContext.Response.Body.Length.
 ---> System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.get_Length()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
```
Example workflow (it's just an HTTP Endpoint with the mapped variable):
[workflow-1.txt](https://github.com/elsa-workflows/elsa-core/files/12512339/workflow-1.txt)

I could reproduce this behavior with the Docker image from the documentation.

**Comment by sfmskywalker** [comment]
Hello @schneidersympatient 

This will happen when the storage provider of the variable is set to “Workflow”, which will attempt to serialize the value in order for it to be persisted inside of the workflow instance document.

In order to capture the output of the HTTP Endpoint activity in a workflow variable, one must ensure that the variable uses the Memory storage provider.

We will try and improve this UX by making sure only compatible variables can be used to capture non-serializable outputs.

**Comment by sfmskywalker** [comment]
Closing because this was traced to variable storage configuration rather than a runtime defect. The maintainer explained that persisting the HTTP result with Workflow storage causes serialization to fail, and that Memory storage is the supported choice for this output type.
