### ISSUE TITLE
Strange inability to Submit to Workflow

### ISSUE THREAD

**Issue by dammitjanet** [elsa-workflows/elsa-core#4504]
I have a workflow, one of the first Steps is a UserTask activity

![image](https://github.com/elsa-workflows/elsa-core/assets/952723/d994bc4d-3b63-412a-9b82-e32695281e5d)

This very basic workflow works just fine, I've created a test [application](https://github.com/dammitjanet/ElsaSandbox) to prove that it works.  The actual workflow, is similar but much larger and starts off like so.

![image](https://github.com/elsa-workflows/elsa-core/assets/952723/18b676b9-cb7a-41c9-80bc-9e983a74b7c3)

The 'Assign to Applicant for Payment' is a custom activity, that loads and saves one of my entities entity in context.  The Type for this is set correctly in the workflow definitions context, and that step does work with the result that the entity is updated with the status 'Waiting payment'

The next item, is a UserTask activity, whereby the application waits for a successful activity, however when the workflow reaches this step, the workflow execution fails with the following error.  Even if I remove the custom activity, I get the same issue

```
            try
            {
				WorkflowBlueprint? workflowBlueprint = await _elsaClient.WorkflowRegistry.GetByTagAsync(type.ToString(), VersionOptions.Latest, ct);
				if (workflowBlueprint != null)
				{
					string applicationId = objectId.ToString("N");
					var response = await _elsaClient.Workflows.ExecuteWorkflowAsync(workflowBlueprint.Id, new ExecuteWorkflowDefinitionRequest()
					{
						CorrelationId = applicationId,
						Input = new Elsa.Models.WorkflowInput()
					}, cancellationToken: ct);

					if (response != null && response.WorkflowInstance != null)
					{
						return response.WorkflowInstance;
					}
				}
			}
            catch
            {
            }

            return null;
```

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Elsa.Activities.UserTask.Bookmarks.UserTaskBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken)
   at Elsa.Services.BookmarkProvider`2.Elsa.Services.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkIndexer.ExtractBookmarksAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, IEnumerable`1 blockingActivities, CancellationToken cancellationToken)
   at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
   at Elsa.Services.Bookmarks.BookmarkIndexer.IndexBookmarksAsync(WorkflowInstance workflowInstance, CancellationToken cancellationToken)
   at Elsa.Handlers.UpdateBookmarksAndRunPostTasks.Handle(WorkflowExecutionFinished notification, CancellationToken cancellationToken)
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunWorkflowInternalAsync(WorkflowExecutionContext workflowExecutionContext, String activityId, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunWorkflowAsync(IWorkflowBlue
![Screenshot 2023-10-06 at 13 31 34](https://github.com/elsa-workflows/elsa-core/assets/952723/25252724-bfca-4220-b606-eee1f133f271)
print workflowBlueprint, WorkflowInstance workflowInstance, String activityId, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, CancellationToken cancellationToken)
   at Elsa.Services.Workflows.WorkflowLaunchpad.ExecuteStartableWorkflowAsync(StartableWorkflow startableWorkflow, WorkflowInput input, CancellationToken cancellationToken)
   at Elsa.Server.Api.Endpoints.Workflows.Execute.Handle(String workflowDefinitionId, ExecuteWorkflowDefinitionRequestModel request, CancellationToken cancellationToken)
```

**Comment by dammitjanet** [comment]
If took me a while, and I had to recreate the workflow from scratch to find the issue

The UserTasks had output properties as 'Transient' instead of as 'Default' - can't for the life of me work out where they were set, or why.

The only differences between when the workflow was created and recreated was the version 2.12 vs 2.13

```
      "propertyStorageProviders": {
        "$id": "7",
        "Output": "Transient",
        "Actions": "Transient"
      }
```
