### ISSUE TITLE
Elsa 3.0 errors when click on any workflow instance

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4641]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/4604

<div type='discussions-op-text'>

<sup>Originally posted by **markjones-WK** November  7, 2023</sup>
I am using the Elsa 3.0 latest docker image hub and after starting a workflow, I (and a co-worker of mine) are getting an error anytime when trying to open any workflow instance in the designer.  Any ideas on how to get around this?  

I am also getting errors when trying to open the workflow instance from elsa designer?

![image](https://github.com/elsa-workflows/elsa-core/assets/126109777/c7748499-8ff8-4e4b-a1c4-e57c6a8d7487)

2023-11-06 18:58:51 info: Microsoft.Hosting.Lifetime[14]
2023-11-06 18:58:51       Now listening on: http://[::]:80
2023-11-06 18:58:51 info: Microsoft.Hosting.Lifetime[0]
2023-11-06 18:58:51       Application started. Press Ctrl+C to shut down.
2023-11-06 18:58:51 info: Microsoft.Hosting.Lifetime[0]
2023-11-06 18:58:51       Hosting environment: Development
2023-11-06 18:58:51 info: Microsoft.Hosting.Lifetime[0]
2023-11-06 18:58:51       Content root path: /app
2023-11-06 18:58:54 warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
2023-11-06 18:58:54       Failed to determine the https port for redirect.
2023-11-06 18:58:59 warn: Microsoft.EntityFrameworkCore.Query[10102]
2023-11-06 18:58:59       The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
2023-11-06 18:58:59 warn: Microsoft.EntityFrameworkCore.Query[10102]
2023-11-06 18:58:59       The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
2023-11-06 18:58:59 fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
2023-11-06 18:58:59       An unhandled exception has occurred while executing the request.
2023-11-06 18:58:59       System.ArgumentNullException: Value cannot be null. (Parameter 'source')
2023-11-06 18:58:59          at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2023-11-06 18:58:59          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2023-11-06 18:58:59          at Elsa.Workflows.Runtime.Services.ActivityExecutionStatsService.GetStatsAsync(String workflowInstanceId, IEnumerable`1 activityNodeIds, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Runtime/Services/ActivityExecutionService.cs:line 26
2023-11-06 18:58:59          at Elsa.Workflows.Api.Endpoints.ActivityExecutions.Report.Report.ExecuteAsync(Request request, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Api/Endpoints/ActivityExecutions/Report/Endpoint.cs:line 33
2023-11-06 18:58:59          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
2023-11-06 18:58:59          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
2023-11-06 18:58:59          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-11-06 18:58:59          at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext) in /source/src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs:line 100
2023-11-06 18:58:59          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-11-06 18:58:59          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-11-06 18:58:59          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Let me know if more infomation is needed to help with this.

Thanks!
</div>

**Comment by sfmskywalker** [comment]
I can reproduce this issue with Elsa.AllInOne.Web.

**Comment by sfmskywalker** [comment]
Fixed via c4449a4b34afb8d4e89129e271a7a16cf09a0713
