### ISSUE TITLE
Running Migrate alteration throws exception

### ISSUE THREAD

**Issue by wenogg** [elsa-workflows/elsa-core#4822]
Hello,
I am trying out Alterations in Elsa 3 and was attempting to migrate a workflow instance from version 1 to version 2.  The workflow definitions are stored as json.

Trying to invoke the Migrate alteration results in exception, both using IAlterationRunner and IAlterationPlanScheduler.

Sample code:
https://github.com/wenogg/elsa-migrate-bug

The stacktrace is:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Workflows.ActivityExecutionContext.get_NodeId()
   at Elsa.Workflows.Services.WorkflowStateExtractor.<ExtractActiveActivityExecutionContexts>g__CreateActivityExecutionContextState|9_0(ActivityExecutionContext activityExecutionContext)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Elsa.Workflows.Services.WorkflowStateExtractor.ExtractActiveActivityExecutionContexts(WorkflowState state, WorkflowExecutionContext workflowExecutionContext)
   at Elsa.Workflows.Services.WorkflowStateExtractor.Extract(WorkflowExecutionContext workflowExecutionContext)
   at Elsa.Alterations.Core.Services.DefaultAlterationRunner.RunAsync(String workflowInstanceId, IEnumerable`1 alterations, CancellationToken cancellationToken)
   at Elsa.Alterations.Core.Services.DefaultAlterationRunner.RunAsync(IEnumerable`1 workflowInstanceIds, IEnumerable`1 alterations, CancellationToken cancellationToken)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__MigrateWorkflow|1>d.MoveNext() in C:\repos\elsa-migrate-bug\ElsaAlterationMigrateBug\Program.cs:line 58
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\repos\elsa-migrate-bug\ElsaAlterationMigrateBug\Program.cs:line 32
   at Program.<Main>(String[] args)
```

Thanks so much

**Comment by sfmskywalker** [comment]
Thank you for reporting this issue. We'll look into it.

**Comment by sfmskywalker** [comment]
I can confirm the issue. Working on a fix.
