### ISSUE TITLE
StartAt activities throw with Elsa.MongoDb 3.0.5

### ISSUE THREAD

**Issue by RainerAtSpirit** [elsa-workflows/elsa-core#4866]
Steps to reproduce. Create two workflows with a StartAt activity.

Execute the first one.

A record get created in bookmarks.

Execute the second.

It throws:

```console
MongoDB.Driver.MongoCommandException: Command findAndModify failed: Plan executor error during findAndModify :: caused by :: E11000 duplicate key error collection: CorasCloud_WorkFlowV3.bookmarks index: BookmarkId_1 dup key: { BookmarkId: null }.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocolAsync(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindAndModifyOperationBase`1.ExecuteAttemptAsync(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Elsa.MongoDb.Common.MongoDbStore`1.SaveAsync[TResult](TDocument document, Expression`1 selector, CancellationToken cancellationToken)
   at Elsa.MongoDb.Modules.Runtime.MongoBookmarkStore.SaveAsync(StoredBookmark record, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.BookmarkUpdater.StoreBookmarksAsync(String workflowInstanceId, IEnumerable`1 bookmarks, String correlationId, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.BookmarkUpdater.UpdateBookmarksAsync(UpdateBookmarksRequest request, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.BookmarksPersister.PersistBookmarksAsync(WorkflowExecutionContext context, Diff`1 diff)
   at Elsa.Workflows.Runtime.Middleware.Workflows.PersistBookmarkMiddleware.InvokeAsync(WorkflowExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Workflows.PersistentVariablesMiddleware.InvokeAsync(WorkflowExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Workflows.ScheduleBackgroundActivitiesMiddleware.InvokeAsync(WorkflowExecutionContext context)
   at Elsa.Workflows.Pipelines.WorkflowExecution.WorkflowExecutionPipeline.ExecuteAsync(WorkflowExecutionContext context)
   at Elsa.Workflows.Services.WorkflowRunner.RunAsync(WorkflowExecutionContext workflowExecutionContext)
   at Elsa.Workflows.Services.WorkflowRunner.RunAsync(Workflow workflow, RunWorkflowOptions options, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.WorkflowHost.StartWorkflowAsync(StartWorkflowHostOptions options, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(IWorkflowHost workflowHost, StartWorkflowRuntimeOptions options)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(IWorkflowHost workflowHost, StartWorkflowRuntimeOptions options)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.StartWorkflowAsync(String definitionId, StartWorkflowRuntimeOptions options)
   at Elsa.Workflows.Api.Endpoints.WorkflowDefinitions.Execute.Execute.HandleAsync(Request request, CancellationToken cancellationToken)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at CorasCloud.WorkFlow.Server.Middleware.JwtMiddleware.Invoke(HttpContext httpContext, IWorkFlowContext ctx) in C:\cc\CorasCloud2023\CorasCloud.WorkFlow.Server\Middleware\JwtMiddleware.cs:line 46
   at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

The error is caused by the BookmarkId index, which requires unique values.

![image](https://github.com/elsa-workflows/elsa-core/assets/581644/1ae5b51e-7cdf-4df8-981d-a9bec63ba3ca)

![image](https://github.com/elsa-workflows/elsa-core/assets/581644/3140d054-d040-4899-8c70-77e296f90b67)

However, the payload for a Bookmark in mongo doesn't have that property, so it will fail.
 
![image](https://github.com/elsa-workflows/elsa-core/assets/581644/4e1fa7b2-81c8-48dd-a93a-a48411f9e023)

**Comment by RainerAtSpirit** [comment]
As a temporary workaround we decided to delete the BookmarkId index, which wasn't used by the system anyway.

![image](https://github.com/elsa-workflows/elsa-core/assets/581644/98a83f10-1eeb-4392-915a-4323b6f1396b)
