### ISSUE TITLE
Cannot resolve scoped service 'Elsa.Workflows.Runtime.Services.BackgroundTaskDispatcher' from root provider

### ISSUE THREAD

**Issue by ManojTiwari-NGI** [elsa-workflows/elsa-core#4906]
Hi,
I worked on some of the sample applications provided in ELSA guides. One of them is https://v3.elsaworkflows.io/docs/guides/external-app-integration.

This application ran very well as per documentation. 
However, when I took the source code (elsa-core) and built the solution. I chose "Elsa.Server.Web" as a startup project. I made the necessary changes in 

"Program.cs" and 
// Configure ASP.NET authentication/authorization.
// Default Identity features for authentication/authorization.
// Use email activities.

"app_settings.json" e.g. "Webhooks" and "AllowedHosts" entries, as specified in the guide.

My development environment is on Windows 10.

I am getting the following error. What could be the reason? I would appreciate your help in this regard.

warn: Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware[0]
      An exception was caught from a downstream middleware component
      System.InvalidOperationException: Cannot resolve scoped service 'Elsa.Workflows.Runtime.Services.BackgroundTaskDispatcher' from root provider.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Elsa.Workflows.Runtime.Features.WorkflowRuntimeFeature.<>c.<.ctor>b__0_9(IServiceProvider sp) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Runtime\Features\WorkflowRuntimeFeature.cs:line 89
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Elsa.Workflows.WorkflowExecutionContext.GetRequiredService[T]() in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Contexts\WorkflowExecutionContext.cs:line 400
         at Elsa.Workflows.ActivityExecutionContext.GetRequiredService[T]() in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Contexts\ActivityExecutionContext.cs:line 489
         at Elsa.Workflows.Runtime.Activities.RunTask.ExecuteAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Runtime\Activities\RunTask.cs:line 98
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.IActivity.ExecuteAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Abstractions\Activity.cs:line 218
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Middleware\Activities\DefaultActivityInvokerMiddleware.cs:line 103
         at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Runtime\Middleware\Activities\BackgroundActivityInvokerMiddleware.cs:line 42
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Middleware\Activities\DefaultActivityInvokerMiddleware.cs:line 64
         at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Middleware\Activities\NotificationPublishingMiddleware.cs:line 29
         at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Middleware\Activities\ExecutionLogMiddleware.cs:line 41
         at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context) in D:\ELSA3.0\els-core-github\src\modules\Elsa.Workflows.Core\Middleware\Activities\ExceptionHandlingMiddleware.cs:line 47

![image](https://github.com/elsa-workflows/elsa-core/assets/89379943/f6261ef0-217a-4354-bea4-82e64a466b9f)

**Comment by ManojTiwari-NGI** [comment]
Thank you so much for your reponse. As requested please have a look at the following files:

[appsettings.json](https://github.com/elsa-workflows/elsa-core/files/14210508/appsettings.json)
I added the following entry into appsettings.json
![image](https://github.com/elsa-workflows/elsa-core/assets/89379943/e03000e6-9f77-4ff0-8d3e-76e0841f9c64)

Please see "Program.cs" attached here as "Program.txt"
[Program.txt](https://github.com/elsa-workflows/elsa-core/files/14210553/Program.txt)
.

**Comment by ManojTiwari-NGI** [comment]
When I debugged, I found that CorrelationId is null. What should I do to fix the issue?
![image](https://github.com/elsa-workflows/elsa-core/assets/89379943/06a16bdc-0a49-47f3-afc0-3204065717dd)

**Comment by AngrySKL** [comment]
I am facing the same issue, did you find the workaround or solution?

**Comment by AngrySKL** [comment]
> I am facing the same issue, did you find the workaround or solution?

I was trying the Elsa.Samples.AspNet.RunTaskIntegration sample btw.

**Comment by ManojTiwari-NGI** [comment]
> I am facing the same issue, did you find the workaround or solution?

No. I am still trying to find a solution.

**Comment by enycaltran** [comment]
Hello.
At the moment I found this workaround:
in my project, I linked source code of Elsa.Workflows.Runtime rather than the nuget package...
Then in the method Apply of the class Elsa.Workflows.Runtime.Features.WorkflowRuntimeFeature, I added the row:
.AddSingleton<BackgroundTaskDispatcher>()

under 

.AddScoped<BackgroundTaskDispatcher>()

In that way, Dependency Injection is able to find BackgroundTaskDispatcher when it needed in a Singleton scope.

**Comment by zesmaili** [comment]
> Hello. At the moment I found this workaround: in my project, I linked source code of Elsa.Workflows.Runtime rather than the nuget package... Then in the method Apply of the class Elsa.Workflows.Runtime.Features.WorkflowRuntimeFeature, I added the row: .AddSingleton()
> 
> under
> 
> .AddScoped()
> 
> In that way, Dependency Injection is able to find BackgroundTaskDispatcher when it needed in a Singleton scope.

hi 
I also encountered a problem and it was solved with the same solution. Will this be solved in the next releases?
