### ISSUE TITLE
Docker image for server+studio latest fails with dependency error

### ISSUE THREAD

**Issue by briannoyes** [elsa-workflows/elsa-core#4969]
When starting docker image as shown in getting started, the server throws an error on startup:
Unhandled exception. System.InvalidOperationException: No service for type 'Elsa.MassTransit.Contracts.IEndpointChannelFormatter' has been registered.

**Comment by FangJY** [comment]
> Getting this as well

me too

**Comment by ArieGato** [comment]
The Dependency error is not occurring anymore. But it appears that the kestrel server is not starting.

This is the output of the `latest` tag
```
elsa-server  |       System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
elsa-server  |        ---> System.DllNotFoundException: Could not load /usr/lib/aarch64-linux-gnu/libpython3.11.so with flags RTLD_NOW | RTLD_GLOBAL: /usr/lib/aarch64-linux-gnu/libpython3.11.so: cannot open shared object file: No such file or directory
elsa-server  |          at Python.Runtime.Platform.PosixLoader.Load(String dllToLoad)
elsa-server  |          at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName)
elsa-server  |          at Python.Runtime.Runtime.Delegates..cctor()
elsa-server  |          --- End of inner exception stack trace ---
elsa-server  |          at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
elsa-server  |          at Python.Runtime.Runtime.Py_IsInitialized()
elsa-server  |          at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
elsa-server  |          at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
elsa-server  |          at Python.Runtime.Runtime.Initialize(Boolean initSigs)
elsa-server  |          at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
elsa-server  |          at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
elsa-server  |          at Python.Runtime.PythonEngine.Initialize()
elsa-server  |          at Elsa.Python.HostedServices.PythonGlobalInterpreterManager.StartAsync(CancellationToken cancellationToken) in /source/src/modules/Elsa.Python/HostedServices/PythonGlobalInterpreterManager.cs:line 35
elsa-server  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
elsa-server  |       No XML encryptor configured. Key {188e4a36-a462-4720-b1e4-8636657cb76c} may be persisted to storage in unencrypted form.
```

It is missing:

```
elsa-server  | info: Microsoft.Hosting.Lifetime[14]
elsa-server  |       Now listening on: http://[::]:8080
elsa-server  | info: Microsoft.Hosting.Lifetime[0]
elsa-server  |       Application started. Press Ctrl+C to shut down.
elsa-server  | info: Microsoft.Hosting.Lifetime[0]
elsa-server  |       Hosting environment: 'Development'
elsa-server  | info: Microsoft.Hosting.Lifetime[0]
elsa-server  |       Content root path: /app
```

**Comment by johnvarney612** [comment]
Same error as previous post. Web page not responding

**Comment by sfmskywalker** [comment]
@ArieGato Are you running this from a Windows machine or something else? I have heard about this error before from someone else who is also running on Windows, so I am trying to understand if it has anything to do with that.

**Comment by johnvarney612** [comment]
@sfmskywalker Yes, the new docker commands worked. Thanks

**Comment by briannoyes** [comment]
And I can confirm it works on MacOS ARM (M2 Max). Thanks for getting that updated!

**Comment by ArieGato** [comment]
@sfmskywalker I'm working on Windows, although I don't think this has any influence on the case.

I tested with the current latest image (`sha-e48c5e2`) and that works correctly. I then tested with tag `sha-640e888` from a day ago. That image fails to start.

As a side note I think the environment variable `-e HTTP_PORTS=8080` is not necessary. The base image defaults to 8080 as of .net 8.
