### ISSUE TITLE
System.ObjectDisposedException within Integration Tests

### ISSUE THREAD

**Issue by truthz03** [elsa-workflows/elsa-core#4988]
Hi,

I have an integration test for my whole app but sometimes the test fails because of an System.ObjectDisposedException thrown by some Elsa classes.
The test uses the TestServer class from Microsoft to host the whole application.
After the test has finished I call Dispose on the TestServer to cleanup everything.
Now sometimes I get the following error:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Elsa.Mediator.Middleware.Command.MiddlewareExtensions.<>c__DisplayClass0_0`1.<UseMiddleware>b__0(CommandMiddlewareDelegate next)
   at Elsa.Mediator.Middleware.Command.CommandPipelineBuilder.Build()
   at Elsa.Mediator.Middleware.Command.CommandPipeline.Setup(Action`1 setup)
   at Elsa.Mediator.Middleware.Command.CommandPipeline.CreateDefaultPipeline()
   at Elsa.Mediator.Middleware.Command.CommandPipeline.get_Pipeline()
   at Elsa.Mediator.Middleware.Command.CommandPipeline.InvokeAsync(CommandContext context)
   at Elsa.Mediator.Services.DefaultMediator.SendAsync(ICommand command, ICommandStrategy strategy, CancellationToken cancellationToken)
   at Elsa.Mediator.Services.DefaultMediator.SendAsync(ICommand command, CancellationToken cancellationToken)
   at Elsa.Scheduling.ScheduledTasks.ScheduledCronTask.<SetupTimer>b__10_0(Object _, ElapsedEventArgs _)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Within my test I add a workflow programmatically with this code `elsa.AddWorkflow<ElsaTestWorkflow>();`
```
public class ElsaTestWorkflow : WorkflowBase
{
    protected override void Build(IWorkflowBuilder builder)
    {
        builder.Name = "Test Workflow2";
        builder.Root = new Sequence
        {
            Activities =
            {
                new Cron
                {
                    CronExpression = new("0 0/1 * * * ?"),
                    CanStartWorkflow = true
                },
                new WriteLine("Test Workflow triggered")
            }
        };
    }
}
```

I think the problem is that something from Elsa will not be disposed correctly while calling TestServer.Dispose and therefore the Cron activity inside the workflow will trigger again and again, even if the IServiceProvider is already disposed.

Is it possible to stop Elsa completely or to dispose everything before I dispose the TestServer or is this a bug which should be fixed by you?

Elsa Version: 3.0.5

**Comment by sfmskywalker** [comment]
Any chance you can share with us a stripped down version of your integration test that we can look at?

**Comment by truthz03** [comment]
Hi

First I tried to implement the bot's suggestion and called `testServer.Host.StopAsync` before `testServer.Dispose`.
Unfortunately that doesn't help. Upon further testing, I found that `StopAsync` is called by all `IHostedServices` even when calling `testServer.Dispose`. It is also important here that when calling `testServer.Dispose`, the `StopAsync` is waited for before all other services are `Disposed`, so an explicit call to `testServer.Host.StopAsync` cannot make a difference.

Here is a stripped down version of my integration test. It doesn't fail always but if you start it 2 or 3 times it should fail at least once. Within VisualStudio you also will not see the red "test failed" icon. If the test fails it simple becomes the "not passed" icon.
[ElsaIntegrationTest.zip](https://github.com/elsa-workflows/elsa-core/files/14401974/ElsaIntegrationTest.zip)
![image](https://github.com/elsa-workflows/elsa-core/assets/14071920/a554f95b-0e79-4283-a367-20b58e11108b)


I hope you found the problem and can fix it.

Thanks Thomas
