### ISSUE TITLE
EF Core SQL lite migration problem

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#518]
When I run the following command to initialize sqlite db I have an error:
```
SET EF_CONNECTIONSTRING="Data Source=c:\data\elsa.db;Cache=Shared"
dotnet ef database update --context SqliteContext
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Set the EF_CONNECTIONSTRING environment variable to a valid SQLite connection string. E.g. SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa.db;Cache=Shared;
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass16_0.<FindContextFactory>b__1()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
PS C:\Users\dust6\Source\Repos\Coding4Fun-Elsa\src\Elsa.Blazor.DemoClient> GET EF_CONNECTIONSTRIN
GET : Le terme «GET» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès 
existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ GET EF_CONNECTIONSTRIN
+ ~~~
    + CategoryInfo          : ObjectNotFound: (GET:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Also your [example](https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard) in the getting started is not working if you run this command

`SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa-dashboard.db;Cache=Shared`
you have this error:
```
Cache=Shared : Le terme «Cache=Shared» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un  
chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 53
+ SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa.db;Cache=Shared
+                                                     ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Cache=Shared:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 ```
I think the syntaxe is `SET EF_CONNECTIONSTRING=Data Source="c:\data\elsa-dashboard.db;Cache=Shared"`

**Comment by sfmskywalker** [comment]
What happens if you try

`SET EF_CONNECTIONSTRING="Data Source=c:\data\elsa-dashboard.db;Cache=Shared"`?

**Comment by xiaolele1314** [comment]
you should run the command in windows's cmd
like this：
![image](https://user-images.githubusercontent.com/42064919/102167033-81620c80-3ec8-11eb-955c-2d5bd6e8c63c.png)

**Comment by sfmskywalker** [comment]
Exactly.

And now it's even better: migrations now run by default when using the EF Core provider, like so:

```csharp
services
    .AddElsa(elsa => elsa
        // Configure Elsa to use the Entity Framework Core persistence provider using Sqlite.
        .UseEntityFrameworkPersistence(ef=>
        {
            ef.UseSqlite("Data Source=elsa.db;Cache=Shared", db => db.MigrationsAssembly(typeof(SqliteElsaContextFactory).Assembly.GetName().Name));
        }));
```

Notice that I specified the migrations assembly for **Sqlite** in the above code snippet. The type `SqliteElsaContextFactory` lives there. If you wanted to use migrations for SQL Server, simply use the `SqlServerElsaContextFactory` as the assembly marker type.

Elsa ships with separate package per EF Core DB provider (just Sqlite and SQL Server for now), but you are of course free to maintain your own migrations.
