### ISSUE TITLE
Fork Activity causes errors

### ISSUE THREAD

**Issue by defunky** [elsa-workflows/elsa-core#5204]
1. Create a workflow with just fork activity or a fork activity with a bunch of console writelines.
2. Run it
3. ELSA UI throws exception with 404 error when it redirects to instance page
4. Instance overview page says the instance is suspended, clicking on it causes designer to throw again

Delay activity causes similar issues

**Comment by sfmskywalker** [comment]
Although I could not reproduce getting an error, I did notice that the Fork (flow) activity doesn't complete, which is a bug.

<img width="2552" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/20e0f0c2-cf1e-4adb-a412-5ac926a1d2bf">

@defunky  What Elsa version did you try?

**Comment by defunky** [comment]
@sfmskywalker

3.1.2. I also get the same behaviour on the delay node if I just drag it in and run

The exception thrown:
``` 
Microsoft.AspNetCore.Components.Web.ErrorBoundary[100]
      Unhandled exception rendering component: Response status code does not indicate success: 404 (Not Found).
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
         at Elsa.Studio.Workflows.Services.WorkflowInstanceObserverFactory.CreateAsync(String workflowInstanceId, CancellationToken cancellationToken)
         at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.WorkflowInstanceDetails.ObserveWorkflowInstanceAsync()
         at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.WorkflowInstanceDetails.OnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Elsa.Studio.Components.StudioComponentBase.InvokeWithBlazorServiceContext(Func`1 func)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)```

**Comment by sfmskywalker** [comment]
I can't seem to reproduce that behavior. Could you share with me detailed steps to arrive at this result? Or, of possible, attach a (simplified) solution with the projects?

**Comment by defunky** [comment]
never mind I'm a dumbass, it was due to signalr not being registered correctly with realtime workflows being enabled. It would be nice to server to throw an exception or log a warning to let you know signalr isn't registered
