### ISSUE TITLE
[BUG] Wrong RuntimeDBContext in 3.1.2 for Oracle

### ISSUE THREAD

**Issue by b0rv3g4r4** [elsa-workflows/elsa-core#5230]
## Description

In the SetupOracle of RuntimeDbContext, the SerializedKeyValuePair is bad defined

## Steps to Reproduce
To help us identify the issue more quickly, please follow these guidelines:

1. **Detailed Steps**: 
We are upgrading to 3.1.2 using a Oracle provider for Elsa and when we generate the migrations for Oracle we found in the Runtime module a problem with SerializedKeyValuePair
2. **Code Snippets**: 
`modelBuilder.Entity<SerializedKeyValuePair>().Property("Value").HasColumnType("NCLOB");`

3. **Attachments**:

4. **Reproduction Rate**: 

5. **Video/Screenshots**: 

6. **Additional Configuration**:

## Expected Behavior
The context defines a property "SerializedValue" for SerializedKeyValuePair

## Actual Behavior
The context defines a property "Value" for SerializedKeyValuePair

## Environment
- **Elsa Package Version**:  3.1.2

## Log Output
```
System.InvalidOperationException: The property 'Value' cannot be added to the type 'SerializedKeyValuePair' because no property type was specified and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.Property(String propertyName)
   at Elsa.EntityFrameworkCore.Modules.Runtime.RuntimeElsaDbContext.SetupForOracle(ModelBuilder modelBuilder)
   at Elsa.EntityFrameworkCore.Common.ElsaDbContextBase.OnModelCreating(ModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()`
```

**Comment by sfmskywalker** [comment]
Merged
