### ISSUE TITLE
[BUG] How do I fix the SwitchCase expression serialization error in Elsa3 workflows?

### ISSUE THREAD

**Issue by btcromesh** [elsa-workflows/elsa-core#5474]
I'm working with Elsa 3 (latest and greatest) workflows and trying to define a Switch activity with cases that include conditions. However, I'm encountering the following error:

```csharp
System.NotSupportedException: Serialization and deserialization of 'System.Func`2[[Elsa.Expressions.Models.ExpressionExecutionContext, Elsa.Expressions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.ValueTask`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' instances is not supported.
```

Here is the code that causes the error:
```csharp
protected override void Build(IWorkflowBuilder builder)
{
    var transactionCommandVariable = new Variable<IFlowCommand<TransactionPayload>>();

    builder.Root = new Sequence
    {
        Activities =
        {
            new ReceiveCommandActivity(loggerFactory.CreateLogger<ReceiveCommandActivity>())
            {
                Name = "ReceiveCommand",
                CanStartWorkflow = true,
                Result = new(transactionCommandVariable) // Set the variable to the output of the activity.
            },
            new Switch()
            {
                Cases =
                {
                    new SwitchCase()
                    {
                        Label = "create transaction",
                        Condition = Expression.DelegateExpression(ctx => transactionCommandVariable.Get(ctx) is FlowCommand<CreateTransactionPayload>),
                        Activity = new Sequence
                        {
                            Activities =
                            {
                                new ValidateCreateTransactionCommandActivity(
                                    assetRepository,
                                    walletRepository,
                                    txValidator,
                                    loggerFactory.CreateLogger<ValidateCreateTransactionCommandActivity>())
                                {
                                    Command = new(transactionCommandVariable),
                                },
                                new CreateTransactionActivity(
                                    txnRepository,
                                    mapper,
                                    eventPublisher,
                                    config,
                                    loggerFactory.CreateLogger<CreateTransactionActivity>())
                                {
                                    Command = new(transactionCommandVariable),
                                }
                            }
                        }
                    },
```

The error message suggests that serialization and deserialization of System.Func instances are not supported. How can I fix the `SwitchCase` expression so that it works correctly?

Additional Information:
- I'm using Elsa version 3.1.3.
- The transactionCommandVariable is a workflow variable holding the transaction command.
- The condition is supposed to check if the command is of type `FlowCommand<CreateTransactionPayload>`.

Error is thrown from here:
```csharp

public class JsonIgnoreCompositeRootConverter : JsonConverter<IActivity>
{
	public override IActivity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		throw new NotImplementedException();
	}

	[UnconditionalSuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "<Pending>")]
	public override void Write(Utf8JsonWriter writer, IActivity? value, JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		PropertyInfo[] obj = value?.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public) ?? Array.Empty<PropertyInfo>();
		JsonSerializerOptions options2 = new JsonSerializerOptions(options);
		PropertyInfo[] array = obj;
		foreach (PropertyInfo propertyInfo in array)
		{
			if (propertyInfo.GetCustomAttribute<JsonIgnoreAttribute>() == null && propertyInfo.GetCustomAttribute<JsonIgnoreCompositeRootAttribute>() == null)
			{
				string propertyName = options.PropertyNamingPolicy?.ConvertName(propertyInfo.Name) ?? propertyInfo.Name;
				writer.WritePropertyName(propertyName);
				object value2 = propertyInfo.GetValue(value);
				if (value2 == null)
				{
					writer.WriteNullValue();
				}
				else
				{
// ERROR
					JsonSerializer.Serialize(writer, value2, options2);
				}
			}
		}
		writer.WriteEndObject();
	}
}
```

Any help to resolve this issue would be greatly appreciated!

I also went through elsa-core/main github codebase but could not find any unit tests that would help me.

**Comment by btcromesh** [comment]
I tried what the Genie suggested but here's what I ran into:

after installing `Elsa.JavaScript` nuget
```csharp
 [18:11:38 WRN] An exception was caught from a downstream middleware component
System.Exception: Could not find an descriptor for expression type "JavaScript".
   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync(Expression expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync[T](Expression expression, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Workflows.Activities.Switch.FindMatchingCasesAsync(ExpressionExecutionContext context)
   at Elsa.Workflows.Activities.Switch.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.IActivity.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)
```

**Comment by sfmskywalker** [comment]
Thanks for the repro steps. It looks like this is the same issue as reported via #4781
