### ISSUE TITLE
[BUG]Jint.Runtime.JavaScriptException+JavaScriptErrorWrapperException

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5536]
at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord)
   at Jint.Engine.<>c__DisplayClass92_0.<Execute>b__0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Evaluate(Script script)
   at Jint.Engine.Evaluate(String code, String source, ParserOptions parserOptions)
   at Jint.Engine.Evaluate(String code)
   at Elsa.JavaScript.Services.JintJavaScriptEvaluator.ExecuteExpressionAndGetResult(Engine engine, String expression)
   at Elsa.JavaScript.Services.JintJavaScriptEvaluator.EvaluateAsync(String expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options, Action`1 configureEngine, CancellationToken cancellationToken)
   at Elsa.JavaScript.Expressions.JavaScriptExpressionHandler.EvaluateAsync(Expression expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync(Expression expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync[T](Expression expression, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Workflows.Activities.Flowchart.Activities.FlowSwitch.FindMatchingCasesAsync(ExpressionExecutionContext context)
   at Elsa.Workflows.Activities.Flowchart.Activities.FlowSwitch.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.IActivity.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
