### ISSUE TITLE
[BUG] ELSA 2  - Elsa.Activities.Rpa.Web fails to download chrome driver

### ISSUE THREAD

**Issue by hcfv** [elsa-workflows/elsa-core#5665]
## Description
When instantiating a workflow that requires the nuget Elsa.Activities.Rpa.Web and to the activities presented on it requires during execution time that a chromedriver is downloaded
If the chrome version presented on the machine executing the code is before version 115 everything is downloaded as expected but when the chrome version is equal or after 115 then it can no longer download it due to changes on the API called. More details can be presented here

```
System.Exception: ChromeDriver version not found for Chrome version 126.0.6478
   at Elsa.Activities.Rpa.Web.Services.ChromeDriverInstaller.Install(String chromeVersion, Boolean forceDownload) in C:\Users\hugo.vilaca\source\repos\elsa-core\src\activities\Elsa.Activities.Rpa.Web\Services\ChromeDriverInstaller.cs:line 41
   at Elsa.Activities.Rpa.Web.Services.BrowserFactory.OpenAsync(String driverType, Object options, CancellationToken cancellationToken) in C:\Users\hugo.vilaca\source\repos\elsa-core\src\activities\Elsa.Activities.Rpa.Web\Services\BrowserFactory.cs:line 40
   at Elsa.Activities.Rpa.Web.OpenBrowser.OnExecuteAsync(ActivityExecutionContext context) in C:\Users\hugo.vilaca\source\repos\elsa-core\src\activities\Elsa.Activities.Rpa.Web\Activities\OpenBrowser.cs:line 46
   at Elsa.Services.Workflows.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, IActivity activity, CancellationToken cancellationToken) in C:\Users\hugo.vilaca\source\repos\elsa-core\src\core\Elsa.Core\Services\Workflows\WorkflowRunner.cs:line 393
```

## Steps to Reproduce
To help us identify the issue more quickly, please follow these guidelines:

1. **Detailed Steps**: 
Execute the attached workflow in any Elsa 2 with the RPA activity instantiated with a chrome version equal or above 115 and the following errors happens
![image](https://github.com/elsa-workflows/elsa-core/assets/143083587/57c47e03-b77b-44c6-8271-bccddc848c17)

3. **Attachments**:
[rpa-fail-download-driver.json](https://github.com/user-attachments/files/15990320/rpa-fail-download-driver.json)

4. **Reproduction Rate**:  
Every time that ChromeVersion is newer than 115

Providing a comprehensive and clear description will greatly assist in diagnosing the problem quickly and accurately. If you're unable to share some of the requested information publicly, please note that, and we can arrange for secure information transfer.

## Expected Behavior
ChromeDriver is download as expected and the workflows executes successfully

## Actual Behavior
Workflow fails with the above error

## Environment
- **Elsa Package Version**: Elsa 2.x
- **Operating System**: Windows 11
- **Browser and Version**: Chrome 126

**Comment by sfmskywalker** [comment]
Fixed via https://github.com/elsa-workflows/elsa-core/pull/5690

Thanks for your contribution!
