### ISSUE TITLE
使用sqlserver，报错：System.ArgumentException: Keyword not supported: 'cache'.

### ISSUE THREAD

**Issue by fengwei9** [elsa-workflows/elsa-core#5795]

**Comment by fengwei9** [comment]
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.ArgumentException: Keyword not supported: 'cache'.
         at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
         at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
         at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
         at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
         at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
         at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
         at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
         at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
         at Elsa.EntityFrameworkCore.Common.RunMigrationsHostedService`1.StartAsync(CancellationToken cancellationToken) in /Users/fengwei/Documents/workspace/elsa/src/modules/Elsa.EntityFrameworkCore.Common/RunMigrationsHostedService.cs:line 28
         at Elsa.EntityFrameworkCore.Common.RunMigrationsHostedService`1.StartAsync(CancellationToken cancellationToken) in /Users/fengwei/Documents/workspace/elsa/src/modules/Elsa.EntityFrameworkCore.Common/RunMigrationsHostedService.cs:line 28
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)

**Comment by fengwei9** [comment]
![image](https://github.com/user-attachments/assets/a45fe381-b656-49df-813f-f7a84c26d5b4)
自动创建了三张表，然后就报错了

**Comment by fengwei9** [comment]
是因为elsa 需要sqlserver2016以上的版本，已经自测没有问题
