### ISSUE TITLE
[BUG] C# Script raises "The type or namespace name 'Http' does not exist"

### ISSUE THREAD

**Issue by ghazisarhan** [elsa-workflows/elsa-core#5852]
## Description
Workflow raises an error when using types within Elsa.Http from C# Script while no error when using Javascript.

## Steps to Reproduce
Please check attached workflow JSON file.

1. **Attachments**:
[test-cs-script.json](https://github.com/user-attachments/files/16421639/test-cs-script.json)

2. **Reproduction Rate**: every time.

## Expected Behavior
No error

## Actual Behavior
Workflow raises the error:
(9,14): error CS0234: The type or namespace name 'Http' does not exist in the namespace 'Elsa' (are you missing an assembly reference?)

## Environment
- **Elsa Package Version**:  Elsa 3.1.3
- **Operating System**: Windows 10
- **Browser and Version**: Firefox 128.0

## Log Output
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.TryGetPrecedingExecutors(Script lastExecutedScriptInChainOpt, CancellationToken cancellationToken)
   at Elsa.CSharp.Services.CSharpEvaluator.EvaluateAsync(String expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options, Func`2 configureScriptOptions, Func`2 configureScript, CancellationToken cancellationToken)
   at Elsa.CSharp.Expressions.CSharpExpressionHandler.EvaluateAsync(Expression expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync(Expression expression, Type returnType, ExpressionExecutionContext context, ExpressionEvaluatorOptions options)
   at Elsa.Extensions.ActivityExecutionContextExtensions.EvaluateInputPropertyAsync(ActivityExecutionContext context, ActivityDescriptor activityDescriptor, InputDescriptor inputDescriptor)
   at Elsa.Extensions.ActivityExecutionContextExtensions.EvaluateInputPropertiesAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.EvaluateInputPropertiesAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)

## Related Issues
Might be related to #5260

**Comment by ghazisarhan** [comment]
Nevermind, I was missing something, I replaces:
```C#
elsa.UseCSharp();
```
With:
```C#
elsa.UseCSharp(csharp => csharp.Assemblies.Add(typeof(Program).Assembly));
```
and it worked.
