### ISSUE TITLE
[BUG] Unhandled exception. System.Exception: Activity descriptor not found

### ISSUE THREAD

**Issue by chenzuo** [elsa-workflows/elsa-core#5856]
## Description
the example of `ConsoleApp.Bookmarks` run fail.

PS D:\work\treem\github\elsa-core\samples\console\Elsa.Samples.ConsoleApp.Bookmarks> dotnet run
Unhandled exception. System.Exception: Activity descriptor not found
   at Elsa.Workflows.IdentityGraphService.AssignInputOutputsAsync(IActivity activity) in D:\work\treem\github\elsa-core\src\modules\Elsa.Workflows.Core\Services\IdentityGraphService.cs:line 59
   at Elsa.Workflows.IdentityGraphService.AssignIdentitiesAsync(ICollection`1 flattenedList) in D:\work\treem\github\elsa-core\src\modules\Elsa.Workflows.Core\Services\IdentityGraphService.cs:line 49
   at Elsa.Workflows.WorkflowGraphBuilder.BuildAsync(Workflow workflow, CancellationToken cancellationToken) in D:\work\treem\github\elsa-core\src\modules\Elsa.Workflows.Core\Services\WorkflowGraphBuilder.cs:line 17
   at Elsa.Workflows.WorkflowRunner.RunAsync(Workflow workflow, RunWorkflowOptions options, CancellationToken cancellationToken) in D:\work\treem\github\elsa-core\src\modules\Elsa.Workflows.Core\Services\WorkflowRunner.cs:line 97
   at Program.<Main>$(String[] args) in D:\work\treem\github\elsa-core\samples\console\Elsa.Samples.ConsoleApp.Bookmarks\Program.cs:line 36
   at Program.<Main>(String[] args)

**Comment by sfmskywalker** [comment]
Fixed
