### ISSUE TITLE
[BUG] Elsa.HttpEndpoint: System.InvalidOperationException: Synchronous operations are disallowed.

### ISSUE THREAD

**Issue by volker-knoess** [elsa-workflows/elsa-core#5867]
## Description
The HTTP Endpoint run into an error when an XML is send with the Content-Type 
application/xml

## Steps to Reproduce
Build a simple workflow with Elsa Studio with HTTP Endpoint and HTTP Response. Set the Parsed Content to variable type object or string (storage workflow or memory should not matter). 

![image](https://github.com/user-attachments/assets/4ebeddcb-26b0-463c-9cc2-c38d56b5ec3d)

4. **Reproduction Rate**:  every time

5. **Video/Screenshots**: Error in Elsa Studio
![image](https://github.com/user-attachments/assets/42f391d8-5f73-4244-88f6-23173c7a64a9)

7. **Additional Configuration**: Nothing specific, Elsa v3.1.3 from Nuget

## Expected Behavior
No System.InvalidOperationException, XML content should be in the variable as string or a better in a more specific object (e.g. XDocument)

## Actual Behavior
See under 5.

## Screenshots
If possible, add screenshots or screen recordings to help explain the problem.

## Environment
- **Elsa Package Version**: Elsa v3.1.3 from Nuget
- **Operating System**: Windows 10
- **Browser and Version**: Dosen't matter the error is in the console log as warning and visible in Elsa Studio.

## Log Output
warn: Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware[0]
      An exception was caught from a downstream middleware component
      System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
         at System.IO.StreamReader.ReadSpan(Span`1 buffer)
         at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
         at System.Xml.XmlTextReaderImpl.ReadData()
         at System.Xml.XmlTextReaderImpl.InitTextReaderInput(String baseUriStr, Uri baseUri, TextReader input)
         at System.Xml.XmlTextReader..ctor(TextReader input)
         at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
         at Elsa.Http.Parsers.XmlHttpContentParser.ReadAsync(Stream content, Type returnType, CancellationToken cancellationToken)
         at Elsa.Extensions.HttpActivityExecutionContextExtensions.ParseContentAsync(ActivityExecutionContext context, Stream content, String contentType, Type returnType, CancellationToken cancellationToken)
         at Elsa.Http.HttpEndpoint.ParseContentAsync(ActivityExecutionContext context, HttpRequest httpRequest)
         at Elsa.Http.HttpEndpoint.HandleRequestAsync(ActivityExecutionContext context, HttpContext httpContext)
         at Elsa.Http.HttpEndpoint.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.IActivity.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)

## Troubleshooting Attempts
Tried to copy the HttpEndpoint over to my code, it's compiling and the activity is coming in Elsa studio but in this case the activity is not activated and a 404 is coming. It seems it takes only the Elsa HttpEndpoint and not my copy. Is it possible to create also your own HttpEnpoints?

## Additional Context
The error comes only with  Content-Type application/xml other types seems to work same content with text/plain works fine.

## Related Issues
I don't thinks so the other seems to address different things.

**Comment by V0idSt4r** [comment]
I encountered the same problem. You can read more about it here [https://github.com/dotnet/runtime/issues/12711](https://github.com/dotnet/runtime/issues/12711)

You need to allow AllowSynchronousIO as a workaround:

`builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
`
