### ISSUE TITLE
[BUG] Can´t save CodeActivity from example. Error "..must bind to an object property or field on deserialization."

### ISSUE THREAD

**Issue by sturlath** [elsa-workflows/elsa-core#5893]
I was trying to get input/outputs to work and it was constantly failing when saving so I tried the [Sum activity from the docs](https://v3.elsaworkflows.io/docs/core-concepts/activity#input-and-output) and it also fails.

Just add this 
```csharp
public class Sum : CodeActivity<int>
{
    public Sum(Variable<int> a, Variable<int> b, Variable<int> result)
    {
        A = new(a);
        B = new(b);
        Result = new(result);
    }

    public Input<int> A { get; set; } = default!;
    public Input<int> B { get; set; } = default!;

    protected override void Execute(ActivityExecutionContext context)
    {
        var input1 = A.Get(context);
        var input2 = B.Get(context);
        var result = input1 + input2;
        context.SetResult(result);
    }
}
```

and press save

![image](https://github.com/user-attachments/assets/71810f58-16d4-42fb-a473-10660470bab8)

and you get timeout

![image](https://github.com/user-attachments/assets/1a0ab258-3941-4578-8f55-653620cc974e)

Looking into the logs I see this error message 
> Each parameter in the deserialization constructor on type 'Marel.DFS.BrokerOnboarding.Workflows.Activities.Sum' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.

And this stacktrace
```
System.InvalidOperationException: Each parameter in the deserialization constructor on type 'Marel.DFS.BrokerOnboarding.Workflows.Activities.Sum' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(JsonElement element, Type returnType, JsonSerializerOptions options)
   at Elsa.Workflows.Services.ActivityFactory.Create(Type type, ActivityConstructorContext context)
   at Elsa.Workflows.Services.ActivityDescriber.<>c__DisplayClass4_0.<DescribeActivityAsync>b__9(ActivityConstructorContext context)
   at Elsa.Workflows.Serialization.Converters.ActivityJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Elsa.Workflows.Activities.Flowchart.Serialization.FlowchartJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(JsonElement element, Type returnType, JsonSerializerOptions options)
   at Elsa.Workflows.Services.ActivityFactory.Create(Type type, ActivityConstructorContext context)
   at Elsa.Workflows.Services.ActivityDescriber.<>c__DisplayClass4_0.<DescribeActivityAsync>b__9(ActivityConstructorContext context)
   at Elsa.Workflows.Serialization.Converters.ActivityJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at FastEndpoints.RequestBinder`1.BindJsonBody(HttpRequest httpRequest, JsonSerializerContext serializerCtx, CancellationToken cancellation)
   at FastEndpoints.RequestBinder`1.BindAsync(BinderContext ctx, CancellationToken cancellation)
   at FastEndpoints.Endpoint`2.BindRequestAsync(EndpointDefinition def, HttpContext ctx, List`1 failures, CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Elsa.Http.Middleware.HttpWorkflowsMiddleware.InvokeAsync(HttpContext httpContext, IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

I´m able to save some built in activities but it seems that I can´t save the CodeActivity ones.

Elsa version **3.2.0-rc4**

**Comment by michaelfp** [comment]
Hey I figure out that this sample is incorrect, in your contructor you need to set the same type. In you public property is Input type. So you need in your constructor change from "Variable" class to "Input". And you don't need to include the results in the constructor too. Change that and test , it will work.

I struggle with that to be able to figure out with this  issue. 

Sampe Code

` public class AppendToArray : CodeActivity<string[]>
 {
     // Propriedades públicas para o Input
     public Input<string[]> ArrayOfData { get; set; } = default!;
     public Input<object> Item { get; set; } = default!;

     // Construtor padrão necessário para serialização
     public AppendToArray() { }

     // Construtor que inicializa as propriedades, se necessário
     public AppendToArray(Input<string[]> arrayOfData, Input<object> item)
     {
         ArrayOfData = arrayOfData;
         Item = item;
     }

     // Método de execução da atividade
     protected override void Execute(ActivityExecutionContext context)
     {
         var array = ArrayOfData.Get(context) ?? Array.Empty<string>();
         var itemToAdd = Item.Get(context)?.ToString() ?? string.Empty;

         var newArray = array.Append(itemToAdd).ToArray(); // Certifique-se de que o array seja do tipo string[]

         context.SetResult(newArray);
     }
 }`

**Comment by sfmskywalker** [comment]
Indeed, the key should be to add a default constructor.
I'll update the documentation.

Thanks!
