### ISSUE TITLE
[BUG]ELsa3.0.3 Studio bug

### ISSUE THREAD

**Issue by cuong21951** [elsa-workflows/elsa-core#5998]
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Studio.Login.Services.DefaultCredentialsValidator.ValidateCredentialsAsync(String username, String password, CancellationToken cancellationToken)
   at Elsa.Studio.Login.Pages.Login.Login.ValidateCredentials(String username, String password)
   at Elsa.Studio.Login.Pages.Login.Login.TryLogin()
   at Elsa.Studio.Components.StudioComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Elsa.Studio.Components.StudioComponentBase.InvokeWithBlazorServiceContext(Func`1 func)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Rend
I got this when trying to connecto the server. I'm using Elsa Blazor Server.

**Comment by sfmskywalker** [comment]
Do you have more specific steps to reproduce? Perhaps a sample project?
