### ISSUE TITLE
[BUG] Fork throws exception when deserializing Completed property of previous activity name.  

### ISSUE THREAD

**Issue by joe-mills** [elsa-workflows/elsa-core#6000]
## Description
I have two approval activities in a Fork activity.  When I complete the second activity, the following code fails in Fork.cs

Fork.cs
Line 65
```
// Append activity to set of completed activities.
        var completedActivityIds = targetContext.UpdateProperty<HashSet<string>>("Completed", set =>
        {
            set ??= new HashSet<string>();
            set.Add(completedChildActivityId);
            return set;
        });

```
The first approval activity  correctly serializes the activity name and saves it to Completed property.

On completion, the second approval activity fails because it can't deserialize the Completed property before adding its own name

Exception

```
Elsa.Expressions.Exceptions.TypeConversionException: Failed to deserialize {"$values":["CreateApprovalTask1"],"_type":"String[]"} to System.Collections.Generic.HashSet`1[System.String]
 ---> System.Text.Json.JsonException: A '$values' metadata property must always be preceded by other metadata properties, such as '$id' or '$type'. Path: $.$values | LineNumber: 0 | BytePositionInLine: 11.
```

## Steps to Reproduce

Create a FlowChart workflow with 2 approval tasks (activity with bookmark) in a Fork

Resume workflow at first bookmark - works
Resume workflow at second bookmark - error

```
var options = new ResumeWorkflowRuntimeParams()
            {
                BookmarkId = task.BookmarkId,
            };

            await workflowRuntime.ResumeWorkflowAsync(task.WorkflowInstanceId, options);
```

Abbreviated worklow

 ```
 List<string> roles = ["testrole1", "testrole2"];
        ICollection<IActivity> approvalActivities = new List<IActivity>();
        foreach (var role in roles)
        {
            approvalActivities.Add(
                new CreateApprovalTask
                {
                    ApprovalId = new Input<Guid>(context => approvalId.Get<Guid>(context)),
                    UserName = new Input<string>(context => userName.Get<string>(context)!),
                    DisplayName = new Input<string>(context => displayName.Get<string>(context)!),
                    Name = $"CreateApprovalTask{role}"
                }
            );
        }

        var forkApproval = new Fork
        {
            JoinMode = ForkJoinMode.WaitAll,
            Branches = approvalActivities
        };

        var approvalCompleteWrite = new WriteLine("Approval Complete");

        var end = new WriteLine("End Material Approval");

        builder.Root = new Flowchart
        {
            Start = start,
            Activities =
            {
                start,
                createMaterialApproval,
                forkApproval,
                approvalCompleteWrite,
                end
            },
            Connections =
            {
                new Connection(start, createMaterialApproval),
                new Connection(createMaterialApproval, correlate),
                new Connection(correlate, forkApproval),
                new Connection(forkApproval, approvalCompleteWrite),
                new Connection(approvalCompleteWrite, end),
            }
        };
```

3. **Attachments**:
Flowchart state after first approval

```
 {
                "$id": "30",
                "id": "4518b244420f23c4",
                "parentContextId": "62ca75922c46a783",
                "scheduledActivityNodeId": "Workflow1:Flowchart1:Fork1",
                "ownerActivityNodeId": "Workflow1:Flowchart1",
                "properties": {
                    "$id": "31",
                    "Completed": {
                        "$id": "32",
                        "$values": [
                            "CreateApprovalTask1"
                        ],
                        "_type": "String[]"
                    }
                },
                "activityState": {
                    "$id": "33",
                    "JoinMode": "WaitAll"
                },
                "dynamicVariables": {
                    "$id": "34",
                    "$values": []
                },
                "status": "Running",
                "startedAt": "2024-10-04T09:54:16.2750808+00:00"
            },
```

Flowchart state after second approval and exception

```
,
            {
                "$id": "16",
                "id": "4518b244420f23c4",
                "parentContextId": "62ca75922c46a783",
                "scheduledActivityNodeId": "Workflow1:Flowchart1:Fork1",
                "ownerActivityNodeId": "Workflow1:Flowchart1",
                "properties": {
                    "$id": "17",
                    "Completed": {
                        "\\\\$values": {
                            "$id": "18",
                            "$values": [
                                "CreateApprovalTask1"
                            ],
                            "_type": "Object[]"
                        }
                    }
                },
                "activityState": {
                    "$id": "19",
                    "JoinMode": "WaitAll"
                },
                "dynamicVariables": {
                    "$id": "20",
                    "$values": []
                },
                "status": "Running",
                "startedAt": "2024-10-04T09:54:16.2750808+00:00"
            }
```

4. **Reproduction Rate**: Indicate how often the bug occurs when following these steps (e.g., "every time", "intermittently: about 50% of the time").
5. 
every time

## Environment

<PackageReference Include="Elsa" Version="3.2.0" />

## Log Output

An exception was caught from a downstream middleware component
Elsa.Expressions.Exceptions.TypeConversionException: Failed to deserialize {"$values":["CreateApprovalTask1"],"_type":"String[]"} to System.Collections.Generic.HashSet`1[System.String]
 ---> System.Text.Json.JsonException: A '$values' metadata property must always be preceded by other metadata properties, such as '$id' or '$type'. Path: $.$values | LineNumber: 0 | BytePositionInLine: 11.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.ThrowHelper.ThrowJsonException_MetadataStandaloneValuesProperty(ReadStack& state, ReadOnlySpan`1 propertyName)
   at System.Text.Json.JsonSerializer.TryReadMetadata(JsonConverter converter, JsonTypeInfo jsonTypeInfo, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
   --- End of inner exception stack trace ---
   at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
   at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
   at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo[T](Object value, ObjectConverterOptions converterOptions)
   at Elsa.Extensions.DictionaryExtensions.TryGetValue[TKey,T](IDictionary`2 dictionary, TKey key, T& value)
   at Elsa.Workflows.ActivityExecutionContext.GetProperty[T](String key)
   at Elsa.Workflows.ActivityExecutionContext.UpdateProperty[T](String key, Func`2 updater)
   at Elsa.Workflows.Activities.Fork.CompleteChildAsync(ActivityCompletedContext context)
   at Elsa.Workflows.Behaviors.ScheduledChildCallbackBehavior.OnActivityCompletedAsync(ActivityCompleted signal, SignalContext context)
   at Elsa.Workflows.Behavior.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
   at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
   at Elsa.Extensions.ActivityExecutionContextExtensions.SendSignalAsync(ActivityExecutionContext context, Object signal)
   at Elsa.Workflows.ActivityExecutionContext.CompleteActivityAsync(Object result)
   at Workflow.Services.Workflows.Activities.CreateApprovalTask.CompleteActivityAsync(ActivityExecutionContext context) in D:\work\biocats\Workflow\Workflow.Services\Workflows\Elsa\Activities\CreateApprovalTask.cs:line 83
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)
## Troubleshooting Attempts
Describe any steps you have taken to troubleshoot or resolve the issue yourself.

## Additional Context
Add any other context about the problem here. This could include the frequency of the issue (e.g., intermittent, every time), conditions under which the issue appears, etc.

## Related Issues
Link to any related issues here.

**Comment by joe-mills** [comment]
As a workaround I have hacked the Context properties in the bookmark callback just before the Activity is completed

 ```
 public async ValueTask CompleteActivityAsync(ActivityExecutionContext context)
    {
        const string completedKey = "Completed";
        var properties = context.ParentActivityExecutionContext?.Properties;
        if (properties != null && properties.ContainsKey(completedKey))
        {
            var completedExpando = properties[completedKey];
            var completedJson = JsonSerializer.Serialize(completedExpando);
            var completedHashSet = DeserializeToHashSet(completedJson);
            properties[completedKey] = completedHashSet;
        }
        await context.CompleteActivityAsync();
```

**Comment by middiu** [comment]
I'm facing the same problem.
My solution was to create a custom Fork component, with exactly the same code of the original code, but with the exception of
````
 // Append activity to the set of completed activities.
 var completedActivityIds = targetContext.UpdateProperty<IEnumerable<string>>("Completed", set =>
 {
     set ??= new List<string>();
     var newSet = set.ToList();
     newSet.Add(completedChildActivityId);
     return newSet;
 });
````

in my case the workflow state after a bookmark looks like:
```
{
                "id": "a549104f861ce626",
                "parentContextId": "1b6b9dc53b83eb36",
                "scheduledActivityNodeId": "Workflow1:Sequence1:CustomFork1",
                "ownerActivityNodeId": "Workflow1:Sequence1",
                "properties": {
                    "Completed": [
                        "Sequence10",
                        "Sequence14",
                        "Sequence18",
                        "Sequence22",
                        "Sequence26",
                        "Sequence30",
                        "Sequence34",
                        "Sequence38"
                    ]
                },
                "activityState": {
                    "JoinMode": "WaitAll"
                },
                "dynamicVariables": [],
                "status": "Running",
                "startedAt": "2025-06-10T07:04:25.1106418+00:00"
            },
````
and the Property "Completed" is deserialized as List<string>, and then the system is not able to convert automatically to HashSet.
the issue is definitely coming from the JSON serialization/deserialization.

Cheers
