### ISSUE TITLE
[BUG] Got an error while trying to create mongo indices for SerializedKeyValuePair

### ISSUE THREAD

**Issue by yusianglin11010** [elsa-workflows/elsa-core#6001]
## Description
I'm encountering an issue with MongoDB index creation in my application using Elsa. During the app startup, Elsa attempts to create MongoDB collection indices. This process works fine for most collections, except for the key_value_pairs collection when trying to create an index for SerializedKeyValuePair.Key.

Upon investigation into the MongoDB.Driver, I found that if SerializedKeyValuePair.Key is defined without a setter, the MongoDB driver doesn't register it in BsonClassMapSerializer.BsonClassMap.

![image (8)](https://github.com/user-attachments/assets/74d22e7b-bf35-45c7-8f1a-1e192159e178)

Consequently, an exception is thrown when the MongoDB.Driver attempts to translate the expression:

![image (9)](https://github.com/user-attachments/assets/b6bb2e05-11bf-4efe-97d7-3bf5eaad6d88)

I've tried two potential solutions:

1. Modify the definition of SerializedKeyValuePair:
Currently, SerializedKeyValuePair.Key is defined as:
```c#
    public string Key => Id;
```
Changing it to the following resolves the issue:

```c#
    public string Key
    {
        get => Id;

        // HACK: to make Key field be register into mongo BsonClassMapSerializer.BsonClassMap
        private set { }
    }
```
This solution works, but I'm unsure if it's the best approach. To maintain the identity between SerializedKeyValuePair.Key and Entity.Id, I always set Id to the value.
 
2. Alter the index creation behavior for SerializedKeyValuePair:
Change from:
 
```c# 
new(indexBuilder.Ascending(x => x.Key))
```
to 
```c#
new(indexBuilder.Ascending(nameof(SerializedKeyValuePair)))
````

## Steps to Reproduce

2. **Code Snippets**: 
```c#
using Elsa.Extensions;
using Elsa.MongoDb.Extensions;
using Elsa.MongoDb.Modules.Management;
using Elsa.MongoDb.Modules.Runtime;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddElsa(elsa =>
{
    elsa.UseMongoDb("mongodb://root:example@localhost:27017/Test996?authSource=admin");
    
    elsa.UseWorkflowManagement(management => { management.UseMongoDb(); });
    elsa.UseWorkflowRuntime(runtime => { runtime.UseMongoDb(); });
    elsa.UseWorkflowsApi();
    elsa.AddWorkflowsFrom<Program>();
});

var app = builder.Build();
app.UseWorkflowsApi();
app.UseWorkflows();
app.Run();
```
4. **Reproduction Rate**: This issue occurs consistently (every time)

## Expected Behavior
The index should be created correctly without errors.

## Actual Behavior
An error is thrown by the MongoDB.Driver:
```
 MongoDB.Driver.Linq.ExpressionNotSupportedException: Expression not supported: x.Key.
```

## Environment
- **Elsa Package Version**: Main branch
- **Operating System**: Windows 11

## Log Output
Error call stack:
```
 MongoDB.Driver.Linq.ExpressionNotSupportedException: Expression not supported: x.Key.
         at MongoDB.Driver.Linq.Linq3Implementation.Translators.ExpressionToFilterTranslators.ToFilterFieldTranslators.MemberExpressionToFilterFieldTranslator.Translate(TranslationContext context, MemberExpression memberExpression) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\Linq\Linq3Implementation\Translators\ExpressionToFilterTranslators\ToFilterFieldTranslators\MemberExpressionToFilterFieldTranslator.cs:line 137
         at MongoDB.Driver.Linq.Linq3Implementation.Translators.ExpressionToFilterTranslators.ToFilterFieldTranslators.ExpressionToFilterFieldTranslator.Translate(TranslationContext context, Expression expression) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\Linq\Linq3Implementation\Translators\ExpressionToFilterTranslators\ToFilterFieldTranslators\ExpressionToFilterFieldTranslator.cs:line 30
         at MongoDB.Driver.Linq.Linq3Implementation.LinqProviderAdapterV3.TranslateExpressionToField[TDocument](LambdaExpression expression, IBsonSerializer`1 documentSerializer, IBsonSerializerRegistry serializerRegistry) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\Linq\Linq3Implementation\LinqProviderAdapterV3.cs:line 91
         at MongoDB.Driver.ExpressionFieldDefinition`1.Render(RenderArgs`1 args) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\FieldDefinition.cs:line 329
         at MongoDB.Driver.DirectionalIndexKeyDefinition`1.Render(RenderArgs`1 args) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\IndexKeysDefinitionBuilder.cs:line 488
         at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.<CreateCreateIndexRequests>b__41_0(CreateIndexModel`1 m) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\MongoCollectionImpl.cs:line 1705
         at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at MongoDB.Driver.Core.Operations.CreateIndexesOperation..ctor(CollectionNamespace collectionNamespace, IEnumerable`1 requests, MessageEncoderSettings messageEncoderSettings) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver.Core\Core\Operations\CreateIndexesOperation.cs:line 58
         at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.CreateCreateIndexesOperation(IEnumerable`1 requests, CreateManyIndexesOptions options) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\MongoCollectionImpl.cs:line 1691
         at MongoDB.Driver.MongoCollectionImpl`1.MongoIndexManager.CreateManyAsync(IClientSessionHandle session, IEnumerable`1 models, CreateManyIndexesOptions options, CancellationToken cancellationToken) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\MongoCollectionImpl.cs:line 1530
         at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken) in C:\Users\yusiang\dotnet\mongo-csharp-driver\src\MongoDB.Driver\MongoCollectionImpl.cs:line 1435
         at Elsa.MongoDb.Modules.Runtime.CreateIndices.<>c__DisplayClass9_0.<<CreateKeyValueIndices>b__0>d.MoveNext() in C:\Users\yusiang\dotnet\elsa-core\src\modules\Elsa.MongoDb\Modules\Runtime\CreateIndices.cs:line 164
      --- End of stack trace from previous location ---
         at Elsa.MongoDb.Helpers.IndexHelpers.CreateAsync[T](IMongoCollection`1 collection, Func`3 func) in C:\Users\yusiang\dotnet\elsa-core\src\modules\Elsa.MongoDb\Helpers\IndexHelpers.cs:line 10
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

**Comment by yusianglin11010** [comment]
Hi @sfmskywalker!
After more additional research, I think I've identified the root cause of the issue. It appears that the `SerializedKeyValuePair.Key` property is not being registered in the BsonClassMap.

Currently, we're using AutoMap() for the mapping:

```c#
BsonClassMap.TryRegisterClassMap<SerializedKeyValuePair>(map =>
{
    map.AutoMap();
    map.SetIgnoreExtraElements(true); // Needed for missing ID property
});
```

After this execution, only `SerializedKeyValuePair.SerializedValue` is registered in the `BsonClassMap._declaredMemberMaps`, which causes an error when creating the indices.

We could manually register the attribute like this:

```c#
BsonClassMap.TryRegisterClassMap<SerializedKeyValuePair>(map =>
{
    map.AutoMap();
    map.SetIgnoreExtraElements(true); // Needed for missing ID property
    map.MapProperty(c => c.Key)
        .SetElementName("Key_1");
});
```

I propose three potential solutions to fix this bug. Please let me know which one you prefer, or if there are any other considerations I might have overlooked. I'd be happy to open a pull request with the chosen solution.

1. Add a private setter for `SerializedKeyValuePair.Key`
2. Avoid using expressions when creating MongoDB indices; use `new(indexBuilder.Ascending(nameof(SerializedKeyValuePair)))` instead
3. Manually register `SerializedKeyValuePair.Key` into BsonClassMap

**Comment by sfmskywalker** [comment]
Hi @yusianglin11010 , thanks for the investigation & the report! I don't have any strong opinions and I will defer to the solution you deem best as part of your PR. Many thanks!

**Comment by yusianglin11010** [comment]
Thank you for your feedback, @sfmskywalker. I've opened a pull request to address this issue. I've chosen to manually register SerializedKeyValuePair.Key to BsonClassMap, as I believe this is the much appropriate solution that avoids potential impacts on other persistence implementations.
The pull request implements the fix and includes a detailed description of the changes made. I'd appreciate your review when you have a chance. If you have any questions or need any adjustments, please let me know, and I'll be happy to make the necessary changes.
You can find the pull request here: https://github.com/elsa-workflows/elsa-core/pull/6036

**Comment by sfmskywalker** [comment]
Thanks @yusianglin11010 , that makes perfect sense. I have reviewed, approved & merged your PR. Many thanks!
