### ISSUE TITLE
ComputeBookmarkHash  in HttpWorkflowsMiddleware 

### ISSUE THREAD

**Issue by mehmet-hoke** [elsa-workflows/elsa-core#6161]
In HttpWorkflowsMiddleware class, ComputeBookmarkHash method

private string ComputeBookmarkHash(IServiceProvider serviceProvider, string path, string method)
{
var bookmarkPayload = new HttpEndpointBookmarkPayload(path, method);
var bookmarkHasher = serviceProvider.GetRequiredService();
var activityTypeName = ActivityTypeNameHelper.GenerateTypeName();
return bookmarkHasher.Hash(activityTypeName, bookmarkPayload);
}

ActivityTypeNameHelper.GenerateTypeName();

in this line it uses HttpEndpoint as a constant. But it records to the Bookmarks table with its customized name (in my case Elsa.HRVHTTPEndpoint) and creates the hash value in this way.
Therefore, it cannot find the record with the Hash value created with HttpEndpoint and the worklow does not continue.

Different type names work when creating(HRVHTTPEndpoint) a bookmark and consuming(HTTPEndpoint)

**Comment by dmq-kmd** [comment]
I have the exact same issue. The mismatch between HttpEndpoint and the customized name (Elsa.HRVHTTPEndpoint) causes the workflow to fail when trying to retrieve the bookmark. @sfmskywalker Are there any plans to address this in the near future? 🙂

**Comment by sfmskywalker** [comment]
Although I cannot commit to a timeline, this is definitely something I wish to add support for ("this" referring to the ability to derive custom activities from existing ones, without having to duplicate bookmarking resumption logic).

**Comment by sfmskywalker** [comment]
I assigned it to the 3.4 milestone to keep my eyes on it, but as with any items added to any milestone, it is subject to be removed from scope if it would otherwise take too long for the milestone release to be delivered.

**Comment by dmq-kmd** [comment]
I've made the necessary changes to the code that caused the problem:

This line:
var activityTypeName = ActivityTypeNameHelper.GenerateTypeName<HttpEndpoint>();

always assumes that activityTypeName comes from HttpEndpoint.

However, I don't have permission to publish my branch and create a PR. Is there a way you could grant me access? 🙂

**Comment by sfmskywalker** [comment]
Reviewing the PR takes time, despite it being a small one. The PR targets a specific case, whereas I am looking for an approach that allows for trigger inheritance universally and not only this case. This may or may not be feasible, which will become clear when investigating the options in more detail. All of this takes time.

You say that not including this PR renders triggers useless. I don’t see how that’s the case, given that I see many users successfully use many triggers, including HTTP Endpoint. Perhaps you can elaborate this point to make sure I’m not missing some important detail.

Thank you.

**Comment by dmq-kmd** [comment]
Let me clarify the issue in more detail.

In HttpWorkflowsMiddleware.cs, the following line is used:

var activityTypeName = ActivityTypeNameHelper.GenerateTypeName<HttpEndpoint>();

This line generates the activity type name as "Elsa.HttpEndpoint", which is then used in the hash computation:

var bookmarkHasher = serviceProvider.GetRequiredService<IStimulusHasher>();
var activityTypeName = ActivityTypeNameHelper.GenerateTypeName<HttpEndpoint>();
return bookmarkHasher.Hash(activityTypeName, bookmarkPayload);


Since the computed hash must exactly match the stored hash for the trigger to be located, this creates a significant limitation:

The hash lookup requires an exact activity type match.

Since the middleware always uses "Elsa.HttpEndpoint" as the activity type name, any trigger that does not have this exact name will never be found.
This means that workflows using custom HTTP triggers (e.g., "MyNamespace.CustomHttpTrigger") will not be found.
Effectively, only one HTTP trigger can exist.

If we try to create multiple custom HTTP triggers with different activity type names, none of them will match "Elsa.HttpEndpoint", and they will not be recognized when the workflow is executed.
This forces users to always use the built-in HttpEndpoint trigger, even if they want to extend or customize it.


If you try to create a custom HttpEndpoint trigger you will see the problem

**Comment by sfmskywalker** [comment]
Thank you for elaborating. Yes, I got that. There is a limitation of deriving your own type of HTTP Endpoint, as you explained clearly.
However, that is not the same as not being able to add different HTTP Endpoints in different workflows, which is the primary use case of this activity. That does not mean we shouldn't allow them to be extended. On the contrary, it makes a lot of sense. 

Out of curiosity, what is your reason for deriving custom HTTP endpoints?

**Comment by dmq-kmd** [comment]
My idea is to integrate Elsa with an external system. For example, if I want to create a trigger like OnTaskClosed, I could define a dedicated trigger with that name. Then, whenever a task is closed in my external system, it could send a request to a specific Elsa endpoint that listens for OnTaskClosed events.

By having custom triggers like this, I can define multiple event-specific HTTP endpoints in Elsa, making the integration more structured and easier to manage. This way, instead of relying on a generic HttpEndpoint and manually handling the logic for different event types, I can create dedicated triggers that map directly to specific external system events.

**Comment by sfmskywalker** [comment]
Thanks for that. Yes, makes perfect sense.

As I said, I'll need time to review the PR. Upon first look, there were some changes that I would need to understand better in terms of potential ramifications.

Until then, another way to provide domain specific triggers based on HTTP Endpoint could be to implement a custom [ActivityProvider](https://docs.elsaworkflows.io/extensibility/custom-activities#activity-providers) that reuses the same HTTP Endpoint activity class, but provides logical derivatives.

For example, it could generate a `OnTaskClosed` activity that is essentially the HTTP Endpoint activity, but with preconfigured fields such as the URL and Verb, and a different name and description.

Unless your custom HTTP Endpoint requires custom logic, this should achieve the same result.

**Comment by dmq-kmd** [comment]
Thank you! 

It would be awesome if there was another way, although I cannot make it work. Not sure if I should open a new question?

Anyway, I tried to create the ActivityProvider:

using Elsa.Extensions;
using Elsa.Http;
using Elsa.Workflows;
using Elsa.Workflows.Models;

namespace ElsaServer.Triggers
{
    public class CustomHttpTriggerProvider(IActivityFactory activityFactory) : IActivityProvider
    {
        public ValueTask<IEnumerable<ActivityDescriptor>> GetDescriptorsAsync(CancellationToken cancellationToken = default)
        {
            var activities = new List<ActivityDescriptor>
            {
                CreateHttpTrigger("OnTaskCreated", "/tasks/created", "POST")
            };

            return new(activities);
        }

        private ActivityDescriptor CreateHttpTrigger(string name, string path, string method)
        {
            return new ActivityDescriptor
            {
                TypeName = "Test trigger",
                Name = name,
                DisplayName = $"Trigger: {name}",
                Description = $"Triggered when a task is created.",
                Category = "Test Triggers",
                IsStart = true,
                Kind = ActivityKind.Trigger,
                Constructor = context =>
                {
                    var activity = activityFactory.Create<HttpEndpoint>(context);
                    activity.CanStartWorkflow = true;
                    activity.Path = new Input<string>(path);
                    return activity;
                }
            };
        }
    }
}


However, I am not allowed to set any of the inputs in the HttpEndpoint activity it seems:

![Image](https://github.com/user-attachments/assets/48ce7eee-7986-4809-88a0-67d0e6e734ff) 


Stacktrace:
   at Elsa.Expressions.Models.ExpressionExecutionContext.GetBlock(MemoryBlockReference blockReference)
   at Elsa.Expressions.Models.ExpressionExecutionContext.GetBlock(Func`1 blockReference)
   at Elsa.Extensions.ExpressionExecutionContextExtensions.Get[T](ExpressionExecutionContext context, Input`1 input)
   at Elsa.Http.HttpEndpoint.GetBookmarkPayloads(ExpressionExecutionContext context)
   at Elsa.Http.HttpEndpoint.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Activity.Elsa.Workflows.IActivity.ExecuteAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
   at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)

**Comment by sfmskywalker** [comment]
Yeah, that's a good idea actually to open a new issue 👍🏻 
the reason you're not seeing any input properties is because now your activity provider is responsible for describing those as well. However, there's a helper available that can create the full activity descriptor, including its inputs, for you. You can then tweak that descriptor to your liking, including setting the type, etc.

**Comment by dmq-kmd** [comment]
Created new issue #6512

**Comment by sfmskywalker** [comment]
@dmq-kmd In 3.5, there will be an even easier way to create custom HTPT Endpoint activities. It will be as simple as the following example:

```csharp
public class CustomHttpEndpoint : HttpEndpointBase
{
    protected override HttpEndpointOptions GetOptions()
    {
        return new()
        {
            Path = "my-path",
            Methods = [HttpMethods.Get],
        };
    }

    protected override async ValueTask OnHttpRequestReceivedAsync(ActivityExecutionContext context, HttpContext httpContext)
    {
        httpContext.Response.StatusCode = 200;
        await httpContext.Response.WriteAsync("Hello World", context.CancellationToken);
    }
}
```
