### ISSUE TITLE
[BUG] Workflow Instances shows 500 (Internal Server Error) if the Workflow has a variable of type JSON

### ISSUE THREAD

**Issue by ghazisarhan** [elsa-workflows/elsa-core#6245]
## Description
Workflow Instances shows 500 (Internal Server Error) if the Workflow has a variable of type JSON

## Steps to Reproduce
1. **Detailed Steps**: 
Create new workflow in Elsa Studio.
Create a variable of type JSON called Variable1.
Place HttpEndpoint in the workflow, set a path name, set the supported methods to POST and in Output tab set the ParsedContent to Variable1.
Place HttpResponse in the workflow, set the Content to Variable and set it to Variable1.
Set the ContectType of HttpResponse to application/json.
Connect the Outcome of the HttpEndpoint to the Input of HttpResponse.
Publish the workflow.
Call the endpoint using POST from any REST client providing any valid JSON in the body.
The workflow should echo back the JSON which was sent in the body.
Open the Workflow instance in Elsa Studio.
After few seconds you will see 500 (Internal Server Error) and the below error in the console.

2. **Attachments**:
Attached workflow definition for easy import:
[test-expando-object-variable.json](https://github.com/user-attachments/files/18263203/test-expando-object-variable.json)

3. **Reproduction Rate**:
4. Every Time

## Expected Behavior
No error

## Actual Behavior
Elsa Studio shows 500 (Internal Server Error) and the below error in the console.

## Environment
- **Elsa Package Version**: Elsa 3.3.0 RC4
- **Operating System**: Windows 10
- **Browser and Version**: Firefox 133.0.3

## Log Output
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.Dynamic.ExpandoObject'.
         at System.Text.Json.ThrowHelper.ThrowInvalidCastException_DeserializeUnableToAssignValue(Type typeOfValue, Type declaredType)
         at System.Text.Json.JsonSerializer.UnboxOnRead[T](Object value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromNodeAsObject(JsonNode node, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize(JsonNode node, Type returnType, JsonSerializerOptions options)
         at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
         at Elsa.Workflows.VariablePersistenceManager.LoadVariablesAsync(WorkflowExecutionContext workflowExecutionContext, IEnumerable`1 excludeTags)
         at Elsa.Workflows.DefaultWorkflowInstanceVariableReader.GetVariables(WorkflowExecutionContext workflowExecutionContext, IEnumerable`1 excludeTags, CancellationToken cancellationToken)
         at Elsa.Workflows.Management.Services.WorkflowInstanceVariableManager.GetVariablesAsync(String workflowInstanceId, IEnumerable`1 excludeTags, CancellationToken cancellationToken)
         at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
         at Elsa.Workflows.Api.Endpoints.WorkflowInstances.Variables.List.List.HandleAsync(CancellationToken cancellationToken)
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at Elsa.Http.Middleware.HttpWorkflowsMiddleware.InvokeAsync(HttpContext httpContext, IServiceProvider serviceProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by ghazisarhan** [comment]
Related to #6247
