### ISSUE TITLE
Elsa try to instantiate next available workflow.

### ISSUE THREAD

**Issue by wassimlaribi** [elsa-workflows/elsa-core#635]
hello
i use TriggerSignalAsync to trigger a signal, it works fine, however when the execution finish, it will try to instantiate the next workflow (i have 2 other disabled)
and it end up with the an exception

Cannot instantiate disabled workflow definitions.
at Elsa.Services.WorkflowFactory.CreateWorkflow(WorkflowDefinitionVersion definition, Variables input, WorkflowInstance workflowInstance, String correlationId)
at Elsa.Services.WorkflowInvoker.d__21.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Elsa.Services.WorkflowInvoker.<StartManyAsync>d__18.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Elsa.Services.WorkflowInvoker.d__16.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Elsa.Activities.Workflows.Extensions.WorkflowInvokerExtensions.d__0.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at JadeOrchestrator.Controllers.JadeWorkFlowController.d__4.MoveNext() 

How to reproduce: 
- create 2 worflows in Elsa dashboard 
- run the first workflow with TriggerSignalAsync() 
- elsa will run the first one and try to run second one as well.

**Comment by sfmskywalker** [comment]
Can you provide the workflow definitions themselves (export as JSON) please?

**Comment by craigfowler** [comment]
It looks like this issue is either resolved or has been waiting for feedback for a very long time.  Are you happy for it to be closed?  If we have no further replies then it will be automatically closed.

**Comment by wassimlaribi** [comment]
hi, sorry for the late reply. the issue is still there, below the json export for the workflows 

workflow1:
{"activities":[{"id":"d15e467f-35b0-4de2-961f-02febe407e03","type":"Signaled","left":403,"top":39,"state":{"signal":{"expression":"OnPriceRequestReceived","syntax":"Literal"},"name":"","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"daca3e1c-96e3-4539-8c0f-d6c0bc163f25","type":"PricingActivity","left":1056,"top":31,"state":{},"blocking":false,"executed":false,"faulted":false},{"id":"2a0cd9d6-9045-4782-995d-6cf65d7c2407","type":"MarginActivity","left":1008,"top":260,"state":{},"blocking":false,"executed":false,"faulted":false},{"id":"f07e2bee-15f3-4452-9fe7-1e3eb9ac7a26","type":"Finish","left":405,"top":211,"state":{},"blocking":false,"executed":false,"faulted":false}],"connections":[{"sourceActivityId":"daca3e1c-96e3-4539-8c0f-d6c0bc163f25","destinationActivityId":"2a0cd9d6-9045-4782-995d-6cf65d7c2407","outcome":"Done"},{"sourceActivityId":"2a0cd9d6-9045-4782-995d-6cf65d7c2407","destinationActivityId":"f07e2bee-15f3-4452-9fe7-1e3eb9ac7a26","outcome":"Done"},{"sourceActivityId":"d15e467f-35b0-4de2-961f-02febe407e03","destinationActivityId":"daca3e1c-96e3-4539-8c0f-d6c0bc163f25","outcome":"Done"}]}
 
 
 workflow2:
{"activities":[{"id":"27ef426d-b367-4c7b-8d70-0895a9be9d3d","type":"CreateUser","left":451,"top":132,"state":{"userName":{"expression":"{{ Input.RegistrationModel.Name }}","syntax":"Liquid"},"email":{"expression":"{{ Input.RegistrationModel.Email }}","syntax":"Liquid"},"password":{"expression":"{{ Input.RegistrationModel.Password }}","syntax":"Liquid"},"name":"CreateUser","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"e40b865b-45fe-4b9a-a175-07b383ec270c","type":"SendEmail","left":792,"top":30,"state":{"from":{"expression":"noreply@acme.com","syntax":"Literal"},"to":{"expression":"{{ Activities.CreateUser.User.Email }}","syntax":"Liquid"},"subject":{"expression":"Activate your account!","syntax":"Literal"},"body":{"expression":"<p>Welcome, {{ Activities.CreateUser.User.Name }}!</p>\r\n<p>Please <a href=\"{{ 'Activate' | signal_url }}\">activate your account </a> within the next 5 minutes.</p>","syntax":"Liquid"},"name":"","title":"Send Activation Link Email","description":"Send an email containing an activation link."},"blocking":false,"executed":false,"faulted":false},{"id":"0a2e2845-2285-440a-b04d-788cf64cbe83","type":"Fork","left":862,"top":296,"state":{"branches":["Activate","Timeout"],"name":"","title":"","description":"Split execution"},"blocking":false,"executed":false,"faulted":false},{"id":"972d6758-074a-4a8b-8299-24c38f869d75","type":"TimerEvent","left":1243,"top":430,"state":{"timeoutExpression":{"expression":"00:02:30","syntax":"Literal"},"name":"","title":"Wait for 2.5 minutes","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"25baaf68-9b4c-4feb-915c-97f624971da9","type":"ActivateUser","left":112,"top":728,"state":{"userId":{"expression":"{{ Activities.CreateUser.User.Id }}","syntax":"Liquid"},"name":"","title":"","description":"Activate the created user."},"blocking":false,"executed":false,"faulted":false},{"id":"9aa36a20-73b1-4fea-98fb-c2a7325783bf","type":"SendEmail","left":85,"top":1009,"state":{"from":{"expression":"noreply@acme.com","syntax":"Literal"},"to":{"expression":"{{ Activities.CreateUser.User.Email }}","syntax":"Liquid"},"subject":{"expression":"Thanks for activating!","syntax":"Literal"},"body":{"expression":"<p>Hi {{ Activities.CreateUser.User.Name }},</p>\r\n<p>Thanks for activating your account!</p>","syntax":"Liquid"},"name":"","title":"Send Activation Confirmation Email","description":"Send an email confirming that the account has been activated."},"blocking":false,"executed":false,"faulted":false},{"id":"d20bdef7-ca1e-4a1c-ae5c-f0a05ee3749e","type":"SendEmail","left":1574,"top":617,"state":{"from":{"expression":"noreply@acme.com","syntax":"Literal"},"to":{"expression":"{{ Activities.CreateUser.User.Email }}","syntax":"Liquid"},"subject":{"expression":"Don't forget to activate your account!","syntax":"Literal"},"body":{"expression":"<p>Hi {{ Activities.CreateUser.User.Name }}!</p>\r\n<p>Please don't forget to <a href=\"{{ 'Activate' | signal_url }}\">activate your account </a> within the next 2 minutes.</p>","syntax":"Liquid"},"name":"","title":"Send Reminder Email","description":"Send a reminder email that the user's time is running out!"},"blocking":false,"executed":false,"faulted":false},{"id":"f4c6664c-05b4-4b50-94a4-422cbf109629","type":"TimerEvent","left":1079,"top":766,"state":{"timeoutExpression":{"expression":"00:02:30","syntax":"Literal"},"name":"","title":"Wait for 2.5 minutes","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"eb3cd99d-51b8-45b9-8209-7573c04fae60","type":"DeleteUser","left":1483,"top":980,"state":{"userId":{"expression":"{{ Activities.CreateUser.User.Id }}","syntax":"Liquid"},"name":"","title":"","description":"Delete the created user."},"blocking":false,"executed":false,"faulted":false},{"id":"117b0481-2050-4c13-a4c1-a47d81a7851a","type":"SendEmail","left":1020,"top":1219,"state":{"from":{"expression":"noreply@acme.com","syntax":"Literal"},"to":{"expression":"{{ Activities.CreateUser.User.Email }}","syntax":"Liquid"},"subject":{"expression":"Sorry to see you go","syntax":"Literal"},"body":{"expression":"<p>Hi {{ Activities.CreateUser.User.Name }},</p>\r\n<p>We're sorry to see you go. We look forward to having you again!</p>","syntax":"Liquid"},"name":"","title":"Send Account Deleted Email","description":"Send the user an email confirming that their account has been deleted."},"blocking":false,"executed":false,"faulted":false},{"id":"3eb399d3-29f4-495a-81cf-91a7b178cfe5","type":"Signaled","left":295,"top":430,"state":{"signal":{"expression":"Activate","syntax":"Literal"},"name":"","title":"Activation Link Clicked","description":"Wait for user to click the activation link."},"blocking":false,"executed":false,"faulted":false},{"id":"9adb0f3c-f5d2-41bc-b297-930b0bdd4f9a","type":"Finish","left":607,"top":1632,"state":{},"blocking":false,"executed":false,"faulted":false},{"id":"b9f580b0-6d27-4566-9203-8e6f57e8b6b6","type":"WriteHttpResponse","left":85,"top":1476,"state":{"statusCode":"200","content":{"expression":"<p>Hi {{ Activities.CreateUser.User.Name }},</p>\r\n<p>Thanks for activating your account!</p>","syntax":"Liquid"},"contentType":"text/html","responseHeaders":{"expression":"","syntax":"Literal"},"name":"","title":"Display Activation Confirmation Page","description":"Display a page confirming that the account has been activated."},"blocking":false,"executed":false,"faulted":false}],"connections":[{"sourceActivityId":"27ef426d-b367-4c7b-8d70-0895a9be9d3d","destinationActivityId":"e40b865b-45fe-4b9a-a175-07b383ec270c","outcome":"Done"},{"sourceActivityId":"e40b865b-45fe-4b9a-a175-07b383ec270c","destinationActivityId":"0a2e2845-2285-440a-b04d-788cf64cbe83","outcome":"Done"},{"sourceActivityId":"0a2e2845-2285-440a-b04d-788cf64cbe83","destinationActivityId":"972d6758-074a-4a8b-8299-24c38f869d75","outcome":"Timeout"},{"sourceActivityId":"25baaf68-9b4c-4feb-915c-97f624971da9","destinationActivityId":"9aa36a20-73b1-4fea-98fb-c2a7325783bf","outcome":"Done"},{"sourceActivityId":"972d6758-074a-4a8b-8299-24c38f869d75","destinationActivityId":"d20bdef7-ca1e-4a1c-ae5c-f0a05ee3749e","outcome":"Done"},{"sourceActivityId":"d20bdef7-ca1e-4a1c-ae5c-f0a05ee3749e","destinationActivityId":"f4c6664c-05b4-4b50-94a4-422cbf109629","outcome":"Done"},{"sourceActivityId":"f4c6664c-05b4-4b50-94a4-422cbf109629","destinationActivityId":"eb3cd99d-51b8-45b9-8209-7573c04fae60","outcome":"Done"},{"sourceActivityId":"eb3cd99d-51b8-45b9-8209-7573c04fae60","destinationActivityId":"117b0481-2050-4c13-a4c1-a47d81a7851a","outcome":"Done"},{"sourceActivityId":"0a2e2845-2285-440a-b04d-788cf64cbe83","destinationActivityId":"3eb399d3-29f4-495a-81cf-91a7b178cfe5","outcome":"Activate"},{"sourceActivityId":"3eb399d3-29f4-495a-81cf-91a7b178cfe5","destinationActivityId":"25baaf68-9b4c-4feb-915c-97f624971da9","outcome":"Done"},{"sourceActivityId":"117b0481-2050-4c13-a4c1-a47d81a7851a","destinationActivityId":"9adb0f3c-f5d2-41bc-b297-930b0bdd4f9a","outcome":"Done"},{"sourceActivityId":"9aa36a20-73b1-4fea-98fb-c2a7325783bf","destinationActivityId":"b9f580b0-6d27-4566-9203-8e6f57e8b6b6","outcome":"Done"},{"sourceActivityId":"b9f580b0-6d27-4566-9203-8e6f57e8b6b6","destinationActivityId":"9adb0f3c-f5d2-41bc-b297-930b0bdd4f9a","outcome":"Done"}]}

**Comment by wassimlaribi** [comment]
hello
any update on this issue please ?
looks like TriggerSignalAsync trigger all the available workflow., means Elsa works only with a single workflow.

**Comment by sfmskywalker** [comment]
I tried top copy & paste your JSON into JSON files, but something seems wrong with the formatting. It would be helpful if you could attach a zip file with the workflow exports as-is.

**Comment by wassimlaribi** [comment]
no need to use my json, just create 2 differents workflow and instanciate the second one, you should see that TriggerSignalAsync will execute the the first one before. 
it's complicate for me to copy paste files in github due to the security policy of my company.

**Comment by sfmskywalker** [comment]
No worries. I think I understand. Are both workflows using the same signal name?

**Comment by wassimlaribi** [comment]
no, different signal name

**Comment by sfmskywalker** [comment]
I tried to reproduce the reported behavior, but unsuccessfully. Here's what I did:

1. Create 2 workflows: the first one is triggered by a signal called "accepted"; the second one is triggered by a signal called "rejected".
2. I invoked `TriggerSignalAsync` with "accepted".

The result was as is it should be: workflow 1 executed, but not workflow 2.
If you are you able to reproduce this issue using a new project from scratch that you can share then I can take a look.

Thanks.
