### ISSUE TITLE
TriggerAsync causes DbUpdateConcurrencyException or deadlock

### ISSUE THREAD

**Issue by pawelsudo1** [elsa-workflows/elsa-core#642]
Hi,
I'm working with .net 5 and i'm using ELSA 1.5.0
EFCore with Azure SQL Server.
My workflow looks something like this:

![image](https://user-images.githubusercontent.com/32904861/108318760-a3298980-71c0-11eb-9163-2934bf057000.png)

and is started and resumed (triggerAsync) by http request. The workflow is resumed right after it is started (few seconds). I check if there are any BlockingActivities.
Periodically resume by the method below causes DbUpdateConcurrencyException or deadlock (the exact exception below)
![image](https://user-images.githubusercontent.com/32904861/108319197-51353380-71c1-11eb-8922-a9f78a299560.png)

`IWorkflowEventHandler thrown from Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler by DbUpdateConcurrencyException Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to  affect1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.SaveAsync(WorkflowInstance instance, CancellationToken cancellationToken)
   at Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler.SaveWorkflowAsync(Workflow workflow, CancellationToken cancellationToken)
   at Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler.InvokingHaltedActivitiesAsync(WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken)
   at Elsa.Services.WorkflowInvoker.<>c__DisplayClass23_0.<<FinalizeWorkflowExecutionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Extensions.InvokeExtensions.InvokeAsync[T](IEnumerable`1 events, Func`2 dispatch, ILogger logger)`

How can I safely resume workflow in this case in the current version and will the problem be solved in version 2.0?

**Comment by spokeDev** [comment]
I have only encountered the DbUpdateConcurrencyException if two instances of a workflow are executed at roughly the same time. Possible in your case?

**Comment by pawelsudo1** [comment]
Yes, it is possible, as mentioned before, I run the workflow and when it reaches activity Signaled is halted.
Then based on:
`var workflowInstance = await _workflowInstanceStore.GetByCorrelationIdAsync(correlationId.ToString()); `  
`if (workflowInstance?.BlockingActivities == null) {}`

I try to predict that workflow instance is halted and resume it.
Is there a better way to make sure that the workflow instance is ready to resume?

**Comment by sfmskywalker** [comment]
This issue is one of the reasons I did a complete rewrite of the EF Core persistence provider for Elsa 2.0 as well as many other aspects. Since you already use the workflow builder API, I recommend using the Elsa 2.0 preview packages from MyGet going forward. Elsa 2 is under active development, so any issues found there will be picked up more quickly.

**Comment by craigfowler** [comment]
Closing, since this has been marked **wontfix**.
