### ISSUE TITLE
To avoid regressions, tests should be re-enabled for v2 CI builds

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#653]
## Running tests in CI builds was disabled
The `appveyor.yml` file in the v2 feature branch currently has the running of tests disabled for CI builds.

https://github.com/elsa-workflows/elsa-core/blob/b2d68593317364e52e6908ecd04cd7dead46dc64/appveyor.yml#L44

## Also some failing tests
It seems that some tests have become broken in the v2 branch though (perhaps going unnnoticed?).  If they still fail in CI builds when tests are re-enabled then they will need to be revisited because they will break the build.  _This comes with the caveat that I ran them on a GNU/Linux environment_, so my failures running locally could plausibly be an environment-specific problem.

```
  Failed Runs workflows provided by storage provider [169 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Elsa.Services.WorkflowFactory.InstantiateAsync(IWorkflowBlueprint workflowBlueprint, String correlationId, String contextId, CancellationToken cancellationToken) in /home/craig/Projects/Elsa Workflow/src/core/Elsa.Core/Services/WorkflowFactory.cs:line 26
   at Elsa.Services.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, Object input, String correlationId, String contextId, CancellationToken cancellationToken) in /home/craig/Projects/Elsa Workflow/src/core/Elsa.Core/Services/WorkflowRunner.cs:line 96
   at Elsa.Core.IntegrationTests.StorageProvider.StorageWorkflowProviderTests.Test01() in /home/craig/Projects/Elsa Workflow/test/integration/Elsa.Core.IntegrationTests/StorageProvider/StorageWorkflowProviderTests.cs:line 27
--- End of stack trace from previous location ---
  Failed Sets the workflow output to the specified value [275 ms]
  Error Message:
   Assert.Equal() Failure
Expected: accb00f8-4624-4f65-8707-d8c24374f3b6
Actual:   FinishOutput { Output = accb00f8-4624-4f65-8707-d8c24374f3b6, Outcomes = System.String[] }
  Stack Trace:
     at Elsa.Core.IntegrationTests.Workflows.FinishWorkflowTests.Test01() in /home/craig/Projects/Elsa Workflow/test/integration/Elsa.Core.IntegrationTests/Workflows/FinishWorkflowTests.cs:line 27
--- End of stack trace from previous location ---

Failed!  - Failed:     2, Passed:     2, Skipped:     0, Total:     4, Duration: 964 ms
```

and

```
  Failed Saving a new workflow definition returns HTTP 201. [65 ms]
  Error Message:
   Refit.ApiException : Response status code does not indicate success: 400 (Bad Request).
  Stack Trace:
     at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
--- End of stack trace from previous location ---
   at Elsa.ComponentTests.Clients.RestClient.WorkflowDefinitions.SaveTests.Post01() in /home/craig/Projects/Elsa Workflow/test/component/Elsa.ComponentTests/Clients/RestClient/WorkflowDefinitions/SaveTests.cs:line 22
--- End of stack trace from previous location ---

Failed!  - Failed:     1, Passed:     2, Skipped:     0, Total:     3, Duration: 1 s
```

**Comment by sfmskywalker** [comment]
I'll openly deny that I haven't paid any attention to the failing tests 🙈 
But yes, the tests have been neglected for a long time for reasons. It's not you. It's not me either as I disclaimed. They are just broken. I wouldn't mind for them to be removed altogether if it makes it easier to rewrite them, since significant aspects of Elsa have changed since these tests were written.

**Comment by craigfowler** [comment]
Sure thing, what I might do tonight is see if I can easily repair any of those failing ones (at least one of them looked like an easy fix).  Then if you don't mind I'll re-enable them in AppVeyor so they're running again?

**Comment by sfmskywalker** [comment]
Sounds good to me, thank you.

**Comment by sfmskywalker** [comment]
Just merged your PR. I also invited you as a member with Triage powers, which should enable you to close tickets if you like. Let me know if it doesn't work.
