### ISSUE TITLE
Exception when starting activity with HTTP Endpoint

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#857]
Latest source compiled and Monolith started.
Simple workflow with HTTP Endpoint and response.

I get following exception when triggering endpoint:

Elsa.Exceptions.LockAcquisitionException: Failed to acquire a lock on correlation ID 
   at Elsa.Dispatch.Handlers.ExecuteWorkflowDefinition.Handle(ExecuteWorkflowDefinitionRequest request, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Dispatch\Handlers\ExecuteWorkflowDefinition.cs:line 63
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Elsa.Dispatch.Handlers.TriggerWorkflows.StartWorkflowsAsync(TriggerWorkflowsRequest request, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Dispatch\Handlers\TriggerWorkflows.cs:line 96
   at Elsa.Dispatch.Handlers.TriggerWorkflows.Handle(TriggerWorkflowsRequest request, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Dispatch\Handlers\TriggerWorkflows.cs:line 82
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IMediator mediator) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\activities\Elsa.Activities.Http\Middleware\HttpRequestMiddleware.cs:line 28
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Please advise what did I do wrong?

**Comment by sfmskywalker** [comment]
It’s not you; it’s me. I will fix.

**Comment by tomy2105** [comment]
OK, I'll be, eagerly :), awaiting :).

**Comment by tomy2105** [comment]
In addition it seems that you moved some projects in the latest commits, and now when compiling I get ElsaDashboard.Samples.Monolith and ElsaDashboard.Samples.Server complain about not being able to reference ElsaDashboard.Samples.WebAssembly because the expect it in the old path (src/samples/dashboard and not it is src/samples/dashboard/blazor)

**Comment by sfmskywalker** [comment]
You're right. Interestingly enough, I didn't notice because it builds fine on my local machine. But the path indeed is incorrect. Will fix too :)

**Comment by sfmskywalker** [comment]
I can't seem to repro the issue anymore. I know it was there and that I fixed it, so I thought maybe this is a regression or some different scenario, but it seems to be looking good. A lot of changes have been pushed since you reported this, so odds are the problem will have vanished for you too when you pull latest. Let me know either way. Thanks!

**Comment by tomy2105** [comment]
Yes, the exception is fixed now with latest code obtained just now, thank you very much.

There still seems to be wrong path to Webassembly project in ElsaDashboard.Samples.Server project (the Monolith project is fixed).

And just out of curiosity, any reason ElsaDashboard.Samples.AspNetCore.Monolith is targeted at .NET 6.0 and others are .NET 5.0?

**Comment by sfmskywalker** [comment]
Fixed the path in the other project as well 👍🏻 
Regarding .NET 6.0, there's no special reason. I installed the .NET 6.0 preview bits, which causes it to be the default SDK when creating new projects. It's OK to change it to .NET 5.0.
