### ISSUE TITLE
InvalidOperationException when executing Elsa.Dashboard.Web sample project

### ISSUE THREAD

**Issue by cando** [elsa-workflows/elsa-core#87]
Hello,
I'm getting the following error when executing Elsa.Dashboard.Web from latest source (Windows 7 x64, .NET Core 2.2 installed):
```

System.InvalidOperationException
  HResult=0x80131509
  Message=Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'Elsa.Dashboard'.
  Source=Microsoft.Extensions.FileProviders.Embedded
  StackTrace:
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestParser.Parse(Assembly assembly, String name)
   at Microsoft.Extensions.FileProviders.ManifestEmbeddedFileProvider..ctor(Assembly assembly, String root)
   at Elsa.Dashboard.Options.StaticAssetsConfigureOptions.PostConfigure(String name, StaticFileOptions options) in elsa-core\src\dashboard\Elsa.Dashboard\Options\StaticAssetsConfigureOptions.cs:line 30
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

When compiling i get this warning:

`GenerateEmbeddedFilesManifest was set, but no EmbeddedResource items were found that could be added to the manifest.	Elsa.Dashboard	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.fileproviders.embedded\2.2.0\build\netstandard2.0\Microsoft.Extensions.FileProviders.Embedded.targets.
`
Please let me know if i can help with more information.
Thanks.

**Comment by sfmskywalker** [comment]
Which reminds me I should update the reader to provide instructions when running the dashboard from source, which include:

1. Execute `gulp build` from the directory `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`

Actually I can’t think of another step :)

**Comment by sfmskywalker** [comment]
@cando Thanks for the PR :)
