### ISSUE TITLE
Problem with latest Elsa and SQLLite

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#930]
Latest elsa from code.
Started without existing database, get following exception when starting....
Do I need to change something on my part, or....? I used ElsaDashboard.Samples.AspNetCore.Monolith.

```text
info: Elsa.Runtime.StartupRunner[0]
      Running startup task IndexTriggers
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      The entity type 'Bookmark' is configured to use schema 'Elsa'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      The entity type 'WorkflowDefinition' is configured to use schema 'Elsa'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      The entity type 'WorkflowExecutionLogRecord' is configured to use schema 'Elsa'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      The entity type 'WorkflowInstance' is configured to use schema 'Elsa'. SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (15ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."Data", "w"."DefinitionId", "w"."DeleteCompletedInstances", "w"."Description", "w"."DisplayName", "w"."IsLatest", "w"."IsPublished", "w"."IsSingleton", "w"."Name", "w"."PersistenceBehavior", "w"."Tag", "w"."TenantId", "w"."Version"
      FROM "WorkflowDefinitions" AS "w"
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Elsa.Persistence.EntityFramework.Core.ElsaContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowDefinitions'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowDefinitions'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Comment by tomy2105** [comment]
Another error I got from previous build that I cannot understand, on azure instance app server, elsa won't start.
Last I have from logs is:

2021-05-04 11:41:24.317 +00:00 [Information] Elsa.Runtime.StartupRunner: Running startup task ContinueRunningWorkflows
2021-05-04 11:41:24.356 +00:00 [Debug] Elsa.Services.DistributedLockProvider: Acquiring a lock on ContinueRunningWorkflows
2021-05-04 11:41:24.384 +00:00 [Debug] Elsa.Services.DistributedLockProvider: Lock acquired on ContinueRunningWorkflows
2021-05-04 11:41:24.394 +00:00 [Debug] Microsoft.EntityFrameworkCore.Query: Compiling query expression:'DbSet<WorkflowInstance>().Where(x => (int)x.WorkflowStatus == (int)__WorkflowStatus_0)'
2021-05-04 11:41:24.445 +00:00 [Debug] Microsoft.EntityFrameworkCore.Query: Generated query execution expression:'queryContext => new SingleQueryingEnumerable<WorkflowInstance>((RelationalQueryContext)queryContext,RelationalCommandCache.SelectExpression(Projection Mapping:EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: WorkflowInstance.Id (string) Required PK AfterSave:Throw, 0], [Property: WorkflowInstance.CancelledAt (Nullable<Instant>), 1], [Property: WorkflowInstance.ContextId (string) Index, 2], [Property: WorkflowInstance.ContextType (string) Index, 3], [Property: WorkflowInstance.CorrelationId (string) Index, 4], [Property: WorkflowInstance.CreatedAt (Instant) Required Index, 5], [Property: WorkflowInstance.Data (no field, string) Shadow, 6], [Property: WorkflowInstance.DefinitionId (string) Required Index, 7], [Property: WorkflowInstance.FaultedAt (Nullable<Instant>) Index, 8], [Property: WorkflowInstance.FinishedAt (Nullable<Instant>) Index, 9], [Property: WorkflowInstance.LastExecutedAt (Nullable<Instant>) Index, 10], [Property: WorkflowInstance.Name (string) Index, 11], [Property: WorkflowInstance.TenantId (string) Index, 12], [Property: WorkflowInstance.Version (int) Required Index, 13], [Property: WorkflowInstance.WorkflowStatus (WorkflowStatus) Required Index, 14], }SELECT w.Id, w.CancelledAt, w.ContextId, w.ContextType, w.CorrelationId, w.CreatedAt, w.Data, w.DefinitionId, w.FaultedAt, w.FinishedAt, w.LastExecutedAt, w.Name, w.TenantId, w.Version, w.WorkflowStatusFROM WorkflowInstances AS wWHERE w.WorkflowStatus == @__WorkflowStatus_0),Func<QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator, WorkflowInstance>,Elsa.Persistence.EntityFramework.Core.ElsaContext,False,False)'
2021-05-04 11:41:24.455 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Command: Creating DbCommand for 'ExecuteReader'.
2021-05-04 11:41:24.455 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Command: Created DbCommand for 'ExecuteReader' (0ms).
2021-05-04 11:41:24.463 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Connection: Opening connection to database 'main' on server 'elsa.db'.
2021-05-04 11:41:24.500 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Connection: Opened connection to database 'main' on server 'C:\home\site\wwwroot\elsa.db'.
2021-05-04 11:41:24.503 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Command: Executing DbCommand [Parameters=[@__WorkflowStatus_0='?'], CommandType='Text', CommandTimeout='30']SELECT "w"."Id", "w"."CancelledAt", "w"."ContextId", "w"."ContextType", "w"."CorrelationId", "w"."CreatedAt", "w"."Data", "w"."DefinitionId", "w"."FaultedAt", "w"."FinishedAt", "w"."LastExecutedAt", "w"."Name", "w"."TenantId", "w"."Version", "w"."WorkflowStatus"FROM "WorkflowInstances" AS "w"WHERE "w"."WorkflowStatus" = @__WorkflowStatus_0
2021-05-04 11:41:24.514 +00:00 [Information] Microsoft.EntityFrameworkCore.Database.Command: Executed DbCommand (14ms) [Parameters=[@__WorkflowStatus_0='?'], CommandType='Text', CommandTimeout='30']SELECT "w"."Id", "w"."CancelledAt", "w"."ContextId", "w"."ContextType", "w"."CorrelationId", "w"."CreatedAt", "w"."Data", "w"."DefinitionId", "w"."FaultedAt", "w"."FinishedAt", "w"."LastExecutedAt", "w"."Name", "w"."TenantId", "w"."Version", "w"."WorkflowStatus"FROM "WorkflowInstances" AS "w"WHERE "w"."WorkflowStatus" = @__WorkflowStatus_0
2021-05-04 11:41:24.514 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Command: A data reader was disposed.
2021-05-04 11:41:24.514 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Connection: Closing connection to database 'main' on server 'C:\home\site\wwwroot\elsa.db'.
2021-05-04 11:41:24.521 +00:00 [Debug] Microsoft.EntityFrameworkCore.Database.Connection: Closed connection to database 'main' on server 'elsa.db'.
2021-05-04 11:41:24.521 +00:00 [Debug] Microsoft.EntityFrameworkCore.Update: SaveChanges starting for 'ElsaContext'.
2021-05-04 11:41:24.521 +00:00 [Debug] Microsoft.EntityFrameworkCore.ChangeTracking: DetectChanges starting for 'ElsaContext'.
2021-05-04 11:41:24.521 +00:00 [Debug] Microsoft.EntityFrameworkCore.ChangeTracking: DetectChanges completed for 'ElsaContext'.
2021-05-04 11:41:24.521 +00:00 [Debug] Microsoft.EntityFrameworkCore.Update: SaveChanges completed for 'ElsaContext' with 0 entities written to the database.
2021-05-04 11:41:24.523 +00:00 [Information] Elsa.StartupTasks.ContinueRunningWorkflows: Found no workflows with status 'Running'. Nothing to resume<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 500.30 - Internal Server Error</title><style type="text/css"></style>
</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.30 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x8007023e</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://120Days:80/</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,30,0x8007023e,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>
</fieldset>
</div>
</div>
</body>
</html>

**Comment by craigfowler** [comment]
It looks as if the migrations haven't run.  But - at first glance everything looks right.  I'mma try and repro this myself and I'll get back to you!

**Comment by craigfowler** [comment]
I think I can see the root cause here.  [This commit] alters the default behaviour for auto-running migrations.  It means that they no longer auto-run, and that means that sample projects using EF will no longer "just work", they'll need the migrations running manually.

It kind of seems things got a little bit muddled during some refactoring/method overloading work though, because that's not the intent.  Migrations should only not auto-run if you have chosen to use non-pooled DB contexts.  Fix inbound!

[This commit]: 9e273dc96415b7c652b384248f54f852f7045b06

**Comment by sfmskywalker** [comment]
My bad, I brokes it.

What I don't yet quite understand however, is why can't we autorun migrations for single DbContexts? In the majority of cases, we'll use ElsaContext. If someone chooses to use a custom context or additional ones, they can always choose to manage their own migrations, right?

**Comment by craigfowler** [comment]
It's not so much about single DB contexts (you could be using pooled contexts with a pool size of 1).  It's about non-pooled contexts which means that we specifically do not want DB contexts reused between different DI lifetime scopes.

If the dev/admin of the app has selected non-pooled then they probably have a reason why they chose that.
In my mind: Logically if you do not want contexts to be reused, then you want more manual control over how they are created and/or how they are configured before they are used.  You also want each context to have the opportunity to differ in some manner.  In my use-case for this that's because I'm running a multi-tenant application, so I want each context to have its own connection string which is determined at the time of usage and can't be determined during application startup.  During app startup it's indeterminate, because we are not in the context of "a current tenant".

Perhaps it's overkill to _outright prevent migrations from auto-running_ in that circumstance, but it should probably be the default not to run them.  I could put in another PR if you'd like in order to add the auto-run migrations option to the non-pooled EF methods, but with a default of false rather than true (leaving the normal/pooled ones with a default of true as it is not)?

**Comment by sfmskywalker** [comment]
I see now, that makes sense!

Then yes, let's enable auto-run migrations for non-pooled contexts all the same, but opt-in. I will make the changes.

Thanks for clarifying.

**Comment by AizenSousuke** [comment]
Where are the migration files?
