### ISSUE TITLE
Switch Activity and Workflow Instance viewer problems.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#936]
Create simple workflow that contains Switch activity.
![Workflow Definition](https://user-images.githubusercontent.com/7658839/117151906-cc1deb80-adb9-11eb-9bf3-4610223e406d.png)

[workflow-definition-TestSwitch.zip](https://github.com/elsa-workflows/elsa-core/files/6427623/workflow-definition-TestSwitch.zip)

Execute it and go to the Workflow instance viewer.
As viewer loads you'll have an System.NullReferenceException (which is displayed in console and caught by debugger):

	warn: Elsa.Expressions.ExpressionEvaluator[0]
		  Failed to evaluate expression input.Method == "GET" using syntax JavaScript
		  TypeError: Cannot read property 'Method' of null
	warn: Elsa.Expressions.ExpressionEvaluator[0]
		  Failed to evaluate expression [{"name":"GET","syntax":"JavaScript","expressions":{"JavaScript":"input.Method == \"GET\""}}] using syntax Switch
		  System.NullReferenceException: Object reference not set to an instance of an object.
			 at Elsa.Expressions.ExpressionEvaluator.EvaluateAsync[T](String expression, String syntax, ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Expressions\ExpressionEvaluator.cs:line 27
			 at Elsa.Activities.ControlFlow.SwitchHandler.EvaluateCasesAsync(IEnumerable`1 caseModels, ActivityExecutionContext context, CancellationToken cancellationToken)+MoveNext() in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Activities\ControlFlow\Switch\SwitchHandler.cs:line 39
			 at Elsa.Activities.ControlFlow.SwitchHandler.EvaluateCasesAsync(IEnumerable`1 caseModels, ActivityExecutionContext context, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
			 at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
			 at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
			 at Elsa.Activities.ControlFlow.SwitchHandler.EvaluateAsync(String expression, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Activities\ControlFlow\Switch\SwitchHandler.cs:line 26
			 at Elsa.Expressions.ExpressionEvaluator.EvaluateAsync(String expression, String syntax, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Expressions\ExpressionEvaluator.cs:line 43

In addition (don't know if it is connected to the exception above) the Workflow instance doesn't display switch outputs well.
Only default one is shown and acitvities connected to non-default ones are "hanging" next to start.

![Workflow Instance](https://user-images.githubusercontent.com/7658839/117152550-67af5c00-adba-11eb-8a4e-c5c2c3419550.png)

**Comment by matt4446** [comment]
@tomy2105 A quick guess - Have you tried for the JS expression:
`return input.Method === "GET";`

**Comment by tomy2105** [comment]
@matt4446 tried and it behaves the same.

And I'm afraid I don't see why this would help. 
This workflow (and the expression in Switch) works ok when triggered. 
However when Workflow Instance is viewed it seems that it tries to evaluate expressions again (why?) and fails.

**Comment by sfmskywalker** [comment]
Fixed
