### ISSUE TITLE
Elsa 2 - HTTP Response not working in this case

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#955]
Hello,

I try to reproduce an alternative version of the document approval guide.
https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval

The problem is that in the third branch of the fork (Remind), the HTTP Response return an error.

![image](https://user-images.githubusercontent.com/43779018/117650499-1378f300-b191-11eb-95eb-f9293b2c2477.png)

The error is : `System.ArgumentNullException: 'Value cannot be null. (Parameter 'baseUri')'` in "Elsa.Activities.Http".

This is the code in the last HTTP Response : 
```liquid
Remind : <a href="{{ "Approve" | signal_url }}">Approve</a> or <a href="{{ "Reject" | signal_url }}"">Reject</a>
```

And with this code nothing happens, the timer just loops infinitely :
```html
<h1>Remind</h1>
```

**Comment by riatdyl** [comment]
The exact same code that is in the last HTTP Response is working in the other ones :
![image](https://user-images.githubusercontent.com/43779018/117655417-550c9c80-b197-11eb-9fbf-cae52252d994.png)

Do you need to have completed a signal before using the HTTP Response activitiy ?

**Comment by sfmskywalker** [comment]
Yes, it makes sense. Keep in mind that the `Timer` activity causes the workflow to run in the background, where there is no HTTP context whatsoever.

This is in contrast to triggering a signal via the Approve/Reject links in the emails, which happens via an HTTP request. When that happens, the workflow executes within the context of that HTTP request, which means you can write an HTTP response.

That being said, we might consider registering a 'fake' HTTP context for background operations. Although it won't be able to write a real HTTP response, at least nothing will break.

**Comment by riatdyl** [comment]
Okay thank you. I'm just unable to use mails in the entreprise, this is why I tried the HTTP Response solution.

This was just to make tests so it's not a big deal.

**Comment by sfmskywalker** [comment]
Sure, got it. What you might try instead then is the **Write Line** activity - you will be able to see output in the console window.

**Comment by xolott** [comment]
I have this exact issue. I'm replicating the `User Registration Sample` from this [medium post](https://sipkeschoorstra.medium.com/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50) but it keep failing when trying to send the remainder email:

```
Elsa.Services.Workflows.WorkflowRunner[0]
      Failed to run workflow ac177c535e8c4cdb96a9d0d2e10a2586
      Elsa.Exceptions.CannotSetActivityPropertyValueException: An exception was thrown whilst setting 'SendEmail.Body'. See the inner exception for further details.
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'baseUri')
         at System.Uri..ctor(Uri baseUri, String relativeUri)
         at Elsa.Activities.Http.Services.DefaultAbsoluteUrlProvider.ToAbsoluteUrl(String relativePath)
         at Elsa.Activities.Http.Extensions.ActivityExecutionContextExtensions.GenerateSignalUrl(ActivityExecutionContext context, String signal)
         at Elsa.Activities.Http.Liquid.SignalUrlFilter.ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext context)
         at Elsa.Scripting.Liquid.Extensions.TemplateContextExtensions.<>c__DisplayClass0_1.<AddFilters>b__0(FluidValue input, FilterArguments arguments, TemplateContext ctx)
```

Is there a way to solve this? Or this is a known issue?

**Comment by sfmskywalker** [comment]
Hi @xolott,  I'm unaware of this issue. Could you send me an export of your workflow that I can try out?

**Comment by xolott** [comment]
This is my current workflow. You will see that there is a `SetVariable` activity with the name `Set ActivateSignalUrl`. I'm using this method as a workaround.

On this file, I had modified the use of the variable to the Liquid Expression `{{ 'Activate' | signal_url }}` to reproduce my issue. This will fail with this stack trace:

**Elsa Version**: 2.1.1.463

```
warn: Elsa.Services.Workflows.WorkflowRunner[0]
      Failed to run workflow 8319f84c8e624dfb917c1f478c789f0e
      Elsa.Exceptions.CannotSetActivityPropertyValueException: An exception was thrown whilst setting 'SendEmail.Body'. See the inner exception for further details.
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'baseUri')
         at System.Uri..ctor(Uri baseUri, String relativeUri)
         at Elsa.Activities.Http.Services.DefaultAbsoluteUrlProvider.ToAbsoluteUrl(String relativePath)
         at Elsa.Activities.Http.Extensions.ActivityExecutionContextExtensions.GenerateSignalUrl(ActivityExecutionContext context, String signal)
         at Elsa.Activities.Http.Liquid.SignalUrlFilter.ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext context)
         at Elsa.Scripting.Liquid.Extensions.TemplateContextExtensions.<>c__DisplayClass0_1.<AddFilters>b__0(FluidValue input, FilterArguments arguments, TemplateContext ctx)
         at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
         at Fluid.Ast.OutputStatement.<WriteToAsync>g__Awaited|7_0(ValueTask`1 t, TextWriter w, TextEncoder enc, TemplateContext ctx)
         at Fluid.Parser.FluidTemplate.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, IReadOnlyList`1 statements, Int32 startIndex)
         at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
         at Elsa.Scripting.Liquid.Services.LiquidTemplateManager.RenderAsync(String source, TemplateContext context, TextEncoder encoder)
         at Elsa.Scripting.Liquid.Services.LiquidHandler.EvaluateAsync(String expression, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken)
         at Elsa.Expressions.ExpressionEvaluator.EvaluateAsync(String expression, String syntax, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.ExpressionActivityPropertyValueProvider.GetValueAsync(ActivityExecutionContext context, CancellationToken cancellationToken)
         at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.ActivityActivator.ActivateActivityAsync(ActivityExecutionContext context, Type type, CancellationToken cancellationToken)
         at Elsa.Providers.ActivityTypes.TypeBasedActivityProvider.<>c__DisplayClass6_0.<<CreateActivityTypeAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Elsa.Services.Workflows.WorkflowRunner.RunCoreAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken)
         at Elsa.Services.Workflows.WorkflowRunner.RunAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken)
```


[workflow-definition-register-user.zip](https://github.com/elsa-workflows/elsa-core/files/6865336/workflow-definition-register-user.zip)

**Comment by sfmskywalker** [comment]
Thanks for that. Would you mind also sending me the project, or at least the custom activities like `CreateUser`?

**Comment by xolott** [comment]
This is my test project. You will find that I changed the architecture a bit, to separate my business logic to the workflow layer.

[server-elsa.zip](https://github.com/elsa-workflows/elsa-core/files/6869239/server-elsa.zip)

**Comment by sfmskywalker** [comment]
Perfect. I was able to reproduce the issue and drill into the source code by replacing the packages with project references. 

As it turns out, the issue is that the `HttpActivityOptions.BaseUrl` is `null`.

From `Startup`, these settings are configured like this:

```csharp
.AddHttpActivities(elsaSection.GetSection("Server").Bind)
```

But in `appsettings.json`, the configuration looks like this:

```json
"Elsa": {
    "Http": {
      "BaseUrl": "http://localhost:5002"
    },
...
```

The fix is to rename the `"Http"` section to `"Server"`, or to change the section being accessed from the Startup class. Then the SendEmail activity will start to work in response to the time out events.

The reason the BaseUrl is used is because when Elsa executes in the background, there is no HTTP context to infer the fully-qualified signal URL from.

As I was troubleshooting this, I realized it would have been easier to understand the root cause if the exception were a little bit more helpful, so I'm pushing a change that handles this particular case by throwing a (hopefully) more helpful exception:

```
There was no base URL configured, which means no absolute URL can be generated from outside the context of an HTTP request. Please make sure that `HttpActivityOptions` is configured correctly. The configuration key used in most Elsa samples is usually: "Elsa:Server:BaseUrl"
```

**Comment by xolott** [comment]
Thanks! That was a bit confusing. In some places it says "Http" and in
others "Server". There should be an official and standard configuration
name, at least in the documentation.

Thanks again!

**Comment by sfmskywalker** [comment]
I understand. In fact you’re not the first to note this. I even confused myself at some point.

However, the application configuration isn’t dictated by Elsa - it’s up to the application to decide if and how they want to structure the configuration sections.

Case in point: it’s our own Startup class that reads “Elsa:Server”. We’re free to change it to e.g. “Elsa:Remote” or anything else. Just as long we also update our configuration source such as appsettings.json.
